/** SIGEE Enterprise RC12.0.10A.26 — Fluxo sequencial de irregularidades e encaminhamento ao MP. */
(function(window){
'use strict';
if(window.__SIGEE_LEGALIZACAO_SERVICE_RC1210A26__)return;
window.__SIGEE_LEGALIZACAO_SERVICE_RC1210A26__=true;
const MOD='LEGALIZACAO';
function client(){try{return window.SIGEE_SUPABASE?.criarCliente?.()||window.SIGEE_SUPABASE_CLIENT||null;}catch(_){return null;}}
function user(){return window.SIGEE_SESSION?.getUser?.()||window.usuarioLogado||null;}
function master(){return window.SIGEE_MODULOS?.ehMaster?.(user())===true;}
function nteId(){return window.SIGEE_MODULOS?.nteNoModulo?.(MOD,user()) ?? user()?.nte_id ?? null;}
function assertAccess(){if(!window.SIGEE_MODULOS?.podeAcessar?.(MOD,user()))throw new Error('Acesso ao módulo Legalização não autorizado.');}
function scoped(q){const n=nteId();return !master()&&n!=null?q.eq('nte_id',n):q;}
function clean(v){const s=String(v??'').trim();return s||null;}
function digits(v,max=99){const s=String(v??'').replace(/\D/g,'').slice(0,max);return s||null;}
function cpfValido(v){const d=digits(v,11)||'';if(d.length!==11||/^(\d)\1{10}$/.test(d))return false;for(let t=9;t<11;t++){let soma=0;for(let i=0;i<t;i++)soma+=Number(d[i])*(t+1-i);let dig=(soma*10)%11;if(dig===10)dig=0;if(dig!==Number(d[t]))return false;}return true;}
function cnpjValido(v){const d=digits(v,14)||'';if(d.length!==14||/^(\d)\1{13}$/.test(d))return false;const calc=t=>{const pesos=t===12?[5,4,3,2,9,8,7,6,5,4,3,2]:[6,5,4,3,2,9,8,7,6,5,4,3,2];const soma=d.slice(0,t).split('').reduce((a,n,i)=>a+Number(n)*pesos[i],0),r=soma%11;return r<2?0:11-r;};return calc(12)===Number(d[12])&&calc(13)===Number(d[13]);}
function telefoneValido(v,obrigatorio=false){const d=digits(v,11)||'';return !d&&!obrigatorio||[10,11].includes(d.length);}
function intOrNull(v){const n=parseInt(v,10);return Number.isFinite(n)?n:null;}
function upper(v){return String(v||'').trim().toUpperCase();}
function today(){return new Date().toISOString().slice(0,10);}
function currentUserId(){return user()?.id??null;}
let resumoCache=null,resumoCacheEm=0;const RESUMO_TTL=120000;
const escolaCache=new Map();
function depPrivada(v){const d=upper(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'');return d.includes('PARTICULAR')||d.includes('PRIVAD');}
function escolaParaInstituicao(escola,extensao=null){const dep=escola?.dependencia_adm||escola?.dependencia||'',priv=depPrivada(dep),tipoExt=upper(extensao?.tipo_cadastro),redeExt=upper(extensao?.rede);return {...(extensao||{}),id:extensao?.id||null,prontuario_id:extensao?.id||null,escola_id:escola?.id,nte_id:extensao?.nte_id??escola?.nte_id,nome_instituicao:extensao?.nome_instituicao||escola?.nome_escola||escola?.nome,cod_inep:extensao?.cod_inep||escola?.cod_mec,municipio:extensao?.municipio||escola?.municipio,tipo_cadastro:tipoExt|| (priv?'PRIVADA':'PUBLICA'),rede:redeExt||(priv?'PRIVADA':(upper(dep).includes('MUNICIPAL')?'MUNICIPAL':(upper(dep).includes('FEDERAL')?'FEDERAL':'ESTADUAL'))),natureza:extensao?.natureza||(priv?'PRIVADA':`PUBLICA_${upper(dep)||'NAO_CLASSIFICADA'}`),dependencia_adm:dep,situacao_funcional:escola?.situacao_funcional||escola?.situacao||null,situacao_regulatoria:extensao?.situacao_regulatoria||'A_CONFERIR',prontuario_habilitado:true,dados_importados_status:extensao?.dados_importados_status||'A_CONFERIR',origem:extensao?.origem||'CATALOGO_SIGEE'};}
async function obterEscolaMestre(escolaId){if(!escolaId)return null;const k=String(escolaId);if(escolaCache.has(k))return escolaCache.get(k);const c=client(),{data,error}=await c.from('escolas_sigee').select('id,cod_mec,nome_escola,nome,municipio,nte_id,nte,dependencia_adm,dependencia,situacao_funcional,situacao,status_acervo,acervo,local_acervo,ativo').eq('id',escolaId).maybeSingle();if(error)throw error;if(data)escolaCache.set(k,data);return data||null;}
async function oneScoped(table,id){assertAccess();const c=client();let q=c.from(table).select('*').eq('id',id);q=scoped(q);const {data,error}=await q.maybeSingle();if(error)throw error;if(!data)throw new Error('Registro não encontrado na sua abrangência.');if(table==='legalizacao_instituicoes'&&data.escola_id){const escola=await obterEscolaMestre(data.escola_id);if(escola)return escolaParaInstituicao(escola,data);}return data;}
function aplicarFiltrosCatalogo(q,filtros={}){
  if(filtros.situacao)q=q.eq('situacao_regulatoria',filtros.situacao);
  const tipo=upper(filtros.tipoCadastro);
  if(tipo)q=q.eq('tipo_cadastro',tipo);
  if(filtros.codInep){const cod=digits(filtros.codInep,20);if(cod)q=q.eq('cod_inep',cod);}
  else if(filtros.buscaNome){const b=String(filtros.buscaNome).trim().replace(/[,()]/g,' ');if(b)q=q.ilike('nome_instituicao',`%${b}%`);}
  else if(filtros.busca){const b=String(filtros.busca).trim().replace(/[,()]/g,' ');if(b)q=q.or(`nome_instituicao.ilike.%${b}%,municipio.ilike.%${b}%,cod_inep.ilike.%${b}%,cnpj.ilike.%${b}%,cod_sec.ilike.%${b}%`);}
  return q;
}
async function contarFonteInstituicoes(tabela,filtros={},somenteNovas=false){
  const c=client();let q=c.from(tabela).select('*',{count:'exact',head:true});if(somenteNovas)q=q.is('escola_id',null);q=aplicarFiltrosCatalogo(scoped(q),filtros);const {count,error}=await q;if(error)throw error;return Number(count||0);
}
async function buscarFaixaInstituicoes(tabela,filtros={},inicio=0,fim=49,somenteNovas=false){
  if(fim<inicio)return[];const c=client();let q=c.from(tabela).select('*').order('nome_instituicao',{ascending:true});if(somenteNovas)q=q.is('escola_id',null);q=aplicarFiltrosCatalogo(scoped(q),filtros);const {data,error}=await q.range(inicio,fim);if(error)throw error;return(data||[]).map(x=>somenteNovas?{...x,prontuario_id:x.id,origem:x.origem||'CADASTRO_LEGALIZACAO'}:x);
}
async function consultarInstituicoes(filtros={}){
  assertAccess();const c=client();if(!c)throw new Error('Cliente Supabase indisponível.');
  const page=Math.max(1,intOrNull(filtros.page)||1),pageSize=Math.min(100,Math.max(10,intOrNull(filtros.pageSize)||50)),from=(page-1)*pageSize,to=from+pageSize-1;
  // O catálogo histórico é baseado na view legalizacao_catalogo_v. Instituições criadas diretamente
  // em Legalização ainda não possuem escola_id e, por isso, precisam ser agregadas à consulta.
  const [novasTotal,catalogoTotal]=await Promise.all([contarFonteInstituicoes('legalizacao_instituicoes',filtros,true),contarFonteInstituicoes('legalizacao_catalogo_v',filtros,false)]);
  const total=novasTotal+catalogoTotal,items=[];
  if(from<novasTotal){const fimNovas=Math.min(to,novasTotal-1);items.push(...await buscarFaixaInstituicoes('legalizacao_instituicoes',filtros,from,fimNovas,true));}
  if(items.length<pageSize&&to>=novasTotal){const inicioCatalogo=Math.max(0,from-novasTotal),quantidade=pageSize-items.length;items.push(...await buscarFaixaInstituicoes('legalizacao_catalogo_v',filtros,inicioCatalogo,inicioCatalogo+quantidade-1,false));}
  return {items,total,page,pageSize,pages:Math.max(1,Math.ceil(total/pageSize))};
}
async function listarInstituicoes(filtros={}){return (await consultarInstituicoes(filtros)).items;}
async function contarInstituicoes(filtros={}){assertAccess();const [novas,catalogo]=await Promise.all([contarFonteInstituicoes('legalizacao_instituicoes',filtros,true),contarFonteInstituicoes('legalizacao_catalogo_v',filtros,false)]);return novas+catalogo;}
async function contarTabela(table,configurar){const c=client();let q=c.from(table).select('id',{count:'exact',head:true});if(configurar)q=configurar(q);const {count,error}=await q;if(error)throw error;return Number(count||0);}
async function listScoped(table,select='*',limit=1000){const c=client();if(!c)throw new Error('Cliente Supabase indisponível.');let q=c.from(table).select(select);q=scoped(q);const {data,error}=await q.limit(limit);if(error)throw error;return data||[];}
async function safeListScoped(table,select='*',limit=1000){try{return await listScoped(table,select,limit);}catch(err){console.warn('[Legalização] fonte opcional indisponível:',table,err?.message||err);return[];}}
async function safeChildren(table,select,inst){try{const c=client();const {data,error}=await c.from(table).select(select).limit(2500);if(error)throw error;const ids=new Set((inst||[]).map(i=>String(i.id)));return(data||[]).filter(o=>ids.has(String(o.instituicao_id)));}catch(err){console.warn('[Legalização] fonte complementar indisponível:',table,err?.message||err);return[];}}
async function resumo(force=false){
  assertAccess();if(!force&&resumoCache&&Date.now()-resumoCacheEm<RESUMO_TTL)return resumoCache;const ano=new Date().getFullYear();
  const safe=async p=>{try{return await p;}catch(err){console.warn('[Legalização] contador opcional indisponível:',err?.message||err);return 0;}};
  const [instituicoes,emCredenciamento,ofertasCriticas,carimbosCriticos,emDescredenciamento,fiscalizacoes,averiguacoes]=await Promise.all([
    contarInstituicoes(),contarInstituicoes({situacao:'EM_CREDENCIAMENTO'}),
    safe(contarTabela('legalizacao_ofertas',q=>q.or(`situacao.in.(EM_ANALISE,EM_RENOVACAO,A_VENCER,VENCIDA),ano_fim_vigencia.lte.${ano+1}`))),
    safe(contarTabela('legalizacao_autorizacoes_carimbo',q=>q.in('situacao',['A_VENCER','VENCIDA','EM_RENOVACAO','EM_AUTORIZACAO']))),
    safe(contarTabela('legalizacao_processos',q=>scoped(q).eq('tipo','DESCREDENCIAMENTO').eq('status','EM_ANDAMENTO'))),
    safe(contarTabela('legalizacao_fiscalizacoes',q=>scoped(q).not('status','in','(REGULARIZADA,ARQUIVADA)'))),
    safe(contarTabela('legalizacao_averiguacoes',q=>scoped(q).not('status','in','(ARQUIVADA,NAO_CONFIRMADA,VINCULADA_INSTITUICAO)')))
  ]);
  resumoCache={instituicoes,emCredenciamento,ofertasCriticas,carimbosCriticos,emDescredenciamento,fiscalizacoes,averiguacoes};resumoCacheEm=Date.now();return resumoCache;
}
async function idsInstituicoesNoEscopo(){
  assertAccess();if(master())return null;const c=client(),n=nteId();if(n==null)return[];const ids=[];let inicio=0;const lote=1000;while(true){const {data,error}=await c.from('legalizacao_instituicoes').select('id').eq('nte_id',n).range(inicio,inicio+lote-1);if(error)throw error;const rows=data||[];ids.push(...rows.map(x=>x.id));if(rows.length<lote)break;inicio+=lote;}return ids;
}
async function listarProcessosRegulatorios(){
  assertAccess();const c=client(),escopoIds=await idsInstituicoesNoEscopo();if(Array.isArray(escopoIds)&&!escopoIds.length)return[];let q=c.from('legalizacao_processos').select('*').eq('tipo','CREDENCIAMENTO').order('updated_at',{ascending:false}).limit(1000);if(Array.isArray(escopoIds))q=q.in('instituicao_id',escopoIds);const {data,error}=await q;if(error)throw error;const lista=data||[];const ids=[...new Set(lista.map(x=>x.instituicao_id).filter(Boolean))];let inst=[];if(ids.length){let iq=c.from('legalizacao_instituicoes').select('id,nome_instituicao,tipo_cadastro,rede,nte_id').in('id',ids);if(!master())iq=iq.eq('nte_id',nteId());const r=await iq;if(!r.error)inst=r.data||[];}const im=new Map(inst.map(x=>[String(x.id),x]));const filtrada=lista.filter(x=>im.has(String(x.instituicao_id)));const uids=[...new Set(filtrada.map(x=>x.responsavel_id||x.criado_por_id).filter(Boolean))];let usuarios=[];if(uids.length){const r=await c.from('usuarios_sigee').select('id,nome,email').in('id',uids);if(!r.error)usuarios=r.data||[];}const um=new Map(usuarios.map(x=>[String(x.id),x]));return filtrada.map(x=>({...x,nte_id:im.get(String(x.instituicao_id))?.nte_id??x.nte_id,instituicao:im.get(String(x.instituicao_id))||null,responsavel:um.get(String(x.responsavel_id||x.criado_por_id))||null}));
}


async function garantirChecklistDescredenciamento(processo){
  assertAccess();if(!processo?.id)return[];const c=client();
  const {data:exist,error:ee}=await c.from('legalizacao_checklist_processo').select('*').eq('processo_id',processo.id).order('id',{ascending:true});if(ee)throw ee;
  let itens=exist||[];
  if(!itens.length){
    const subtipo=upper(processo.subtipo);
    const {data:catalogo,error:ec}=await c.from('legalizacao_checklist_catalogo').select('*').eq('tipo_processo','DESCREDENCIAMENTO').eq('ativo',true).or(`subtipo_aplicavel.is.null,subtipo_aplicavel.eq.${subtipo}`).order('ordem',{ascending:true});if(ec)throw ec;
    if((catalogo||[]).length){
      const rows=(catalogo||[]).map(x=>({processo_id:processo.id,catalogo_id:x.id,status:'NAO_APRESENTADO'}));
      const {data:criados,error:ei}=await c.from('legalizacao_checklist_processo').insert(rows).select('*');if(ei)throw ei;itens=criados||[];
    }
  }
  const ids=[...new Set(itens.map(x=>x.catalogo_id).filter(Boolean))];let cats=[];
  if(ids.length){const r=await c.from('legalizacao_checklist_catalogo').select('*').in('id',ids).order('ordem',{ascending:true});if(r.error)throw r.error;cats=r.data||[];}
  const cm=new Map(cats.map(x=>[String(x.id),x]));
  return itens.map(x=>({...x,catalogo:cm.get(String(x.catalogo_id))||null})).sort((a,b)=>(a.catalogo?.ordem||0)-(b.catalogo?.ordem||0));
}
async function listarDescredenciamentosRegulatorios(){
  assertAccess();const c=client(),escopoIds=await idsInstituicoesNoEscopo();if(Array.isArray(escopoIds)&&!escopoIds.length)return[];let q=c.from('legalizacao_processos').select('*').eq('tipo','DESCREDENCIAMENTO').order('updated_at',{ascending:false}).limit(1000);if(Array.isArray(escopoIds))q=q.in('instituicao_id',escopoIds);const {data,error}=await q;if(error)throw error;const lista=data||[],ids=[...new Set(lista.map(x=>x.instituicao_id).filter(Boolean))];let inst=[];if(ids.length){let iq=c.from('legalizacao_instituicoes').select('id,nome_instituicao,tipo_cadastro,rede,nte_id').in('id',ids);if(!master())iq=iq.eq('nte_id',nteId());const r=await iq;if(!r.error)inst=r.data||[];}const im=new Map(inst.map(x=>[String(x.id),x]));const base=lista.filter(x=>im.has(String(x.instituicao_id))).map(x=>({...x,nte_id:im.get(String(x.instituicao_id))?.nte_id??x.nte_id,instituicao:im.get(String(x.instituicao_id))||null}));
  return await Promise.all(base.map(async x=>{try{return {...x,checklist:await garantirChecklistDescredenciamento(x)};}catch(err){console.warn('[Legalização] checklist de descredenciamento indisponível',x.id,err);return {...x,checklist:[],checklist_erro:String(err?.message||err||'Falha ao carregar checklist')};}}));
}
async function iniciarDescredenciamento(instituicaoId,payload={}){
  assertAccess();const c=client(),inst=await oneScoped('legalizacao_instituicoes',instituicaoId),subtipo=upper(payload.subtipo),sei=clean(payload.numero_sei),dataProtocolo=clean(payload.data_protocolo);if(!['VOLUNTARIO','COMPULSORIO'].includes(subtipo))throw new Error('Selecione descredenciamento voluntário ou compulsório.');if(!sei)throw new Error('O Processo SEI é obrigatório no início do descredenciamento.');if(!dataProtocolo)throw new Error('Informe a data de protocolo do Processo SEI.');
  const {data:exist,error:ee}=await c.from('legalizacao_processos').select('id,status').eq('instituicao_id',inst.id).eq('tipo','DESCREDENCIAMENTO').limit(20);if(ee)throw ee;if((exist||[]).some(x=>!['CONCLUIDO','ARQUIVADO','CANCELADO'].includes(upper(x.status))))throw new Error('Já existe descredenciamento ativo para esta instituição.');
  const registro={instituicao_id:inst.id,nte_id:inst.nte_id,tipo:'DESCREDENCIAMENTO',subtipo,numero_sei:sei,data_protocolo:dataProtocolo,status:'EM_ANDAMENTO',etapa_atual:'ANALISE_DOCUMENTAL',prazo_etapa:clean(payload.prazo_etapa),observacao:clean(payload.observacao),responsavel_id:currentUserId(),criado_por_id:currentUserId(),atualizado_por_id:currentUserId()};const {data:p,error}=await c.from('legalizacao_processos').insert(registro).select('*').single();if(error)throw error;
  const {data:catalogo,error:ec}=await c.from('legalizacao_checklist_catalogo').select('*').eq('tipo_processo','DESCREDENCIAMENTO').eq('ativo',true).or(`subtipo_aplicavel.is.null,subtipo_aplicavel.eq.${subtipo}`).order('ordem',{ascending:true});if(ec)throw ec;if((catalogo||[]).length){const rows=catalogo.map(x=>({processo_id:p.id,catalogo_id:x.id,status:'NAO_APRESENTADO'}));const {error:er}=await c.from('legalizacao_checklist_processo').insert(rows);if(er)throw er;}
  await c.from('legalizacao_instituicoes').update({situacao_regulatoria:'EM_DESCREDENCIAMENTO',atualizado_por_id:currentUserId(),updated_at:new Date().toISOString()}).eq('id',inst.id);await historicoProcesso(p.id,'ABERTURA_DESCREDENCIAMENTO',`Descredenciamento ${subtipo==='VOLUNTARIO'?'voluntário':'compulsório'} iniciado.`,{numero_sei:sei,data_protocolo:dataProtocolo});resumoCache=null;return p;
}
async function listarCatalogoOfertas(){
  assertAccess();const c=client();const {data,error}=await c.from('legalizacao_oferta_catalogo').select('*').eq('ativo',true).order('ordem',{ascending:true});if(error)throw error;return data||[];
}
async function vincularOfertasAoCredenciamento(processo,inst,payload={}){
  const c=client(),raw=Array.isArray(payload.oferta_catalogo_ids)?payload.oferta_catalogo_ids:[payload.oferta_catalogo_ids],ids=[...new Set(raw.map(Number).filter(Boolean))];if(!ids.length)return{ofertas:[],requisitos_gerados:0};
  const {data:catalogo,error:ec}=await c.from('legalizacao_oferta_catalogo').select('*').in('id',ids).eq('ativo',true);if(ec)throw ec;if((catalogo||[]).length!==ids.length)throw new Error('Uma ou mais ofertas selecionadas não estão disponíveis no catálogo regulatório.');
  const exigeCurso=(catalogo||[]).some(o=>o.exige_curso_especifico===true),cursoNome=clean(payload.curso_nome),eixo=clean(payload.eixo_tecnologico);if(exigeCurso&&!cursoNome)throw new Error('Informe o nome do curso técnico para a oferta de Educação Profissional.');
  const {data:exist,error:ee}=await c.from('legalizacao_processos_ofertas').select('id,oferta_catalogo_id,curso_nome').eq('processo_id',processo.id);if(ee)throw ee;const existentes=exist||[],novos=[];
  for(const id of ids){const oc=(catalogo||[]).find(o=>Number(o.id)===Number(id)),cn=oc?.exige_curso_especifico?cursoNome:null;const dup=existentes.some(x=>Number(x.oferta_catalogo_id)===Number(id)&&String(x.curso_nome||'').trim().toUpperCase()===String(cn||'').trim().toUpperCase());if(!dup)novos.push({processo_id:processo.id,instituicao_id:inst.id,oferta_catalogo_id:id,curso_nome:cn,eixo_tecnologico:oc?.exige_curso_especifico?eixo:null,status:'EM_ANALISE'});}
  if(novos.length){const {error:ev}=await c.from('legalizacao_processos_ofertas').insert(novos);if(ev)throw ev;}
  const {data:reqCat,error:er}=await c.from('legalizacao_oferta_requisitos_catalogo').select('*').eq('ativo',true).or(`oferta_catalogo_id.is.null,oferta_catalogo_id.in.(${ids.join(',')})`).order('ordem',{ascending:true});if(er)throw er;
  const unicos=new Map();for(const r of reqCat||[]){const chave=String(r.id);if(!unicos.has(chave))unicos.set(chave,r);}const reqRows=[...unicos.values()].map(r=>({processo_id:processo.id,instituicao_id:inst.id,requisito_catalogo_id:r.id,status:'NAO_APRESENTADO'}));
  if(reqRows.length){const {error:erp}=await c.from('legalizacao_oferta_requisitos_processo').upsert(reqRows,{onConflict:'processo_id,requisito_catalogo_id',ignoreDuplicates:true});if(erp)throw erp;}
  return{ofertas:catalogo||[],requisitos_gerados:reqRows.length,novas_ofertas:novos.length};
}
async function adicionarOfertasCredenciamento(processoId,payload={}){
  assertAccess();const c=client();let q=c.from('legalizacao_processos').select('*').eq('id',processoId).eq('tipo','CREDENCIAMENTO');q=scoped(q);const {data:p,error}=await q.maybeSingle();if(error)throw error;if(!p)throw new Error('Credenciamento não localizado na sua abrangência.');if(['CONCLUIDO','ARQUIVADO','CANCELADO'].includes(upper(p.status)))throw new Error('O credenciamento já está encerrado.');const inst=await oneScoped('legalizacao_instituicoes',p.instituicao_id);const r=await vincularOfertasAoCredenciamento(p,inst,payload);await historicoProcesso(p.id,'OFERTAS_ADICIONADAS','Oferta(s) adicionada(s) ao ato de credenciamento.',{ofertas:r.ofertas.map(o=>o.codigo),novas:r.novas_ofertas});return r;
}
async function atualizarRequisitoOferta(itemId,payload={}){
  assertAccess();const c=client(),status=upper(payload.status),valid=['NAO_APRESENTADO','APRESENTADO','EM_ANALISE','CONFORME','NAO_CONFORME','NAO_SE_APLICA'];if(!valid.includes(status))throw new Error('Situação de requisito inválida.');const {data:ant,error:ea}=await c.from('legalizacao_oferta_requisitos_processo').select('*').eq('id',itemId).single();if(ea)throw ea;const {data:p,error:ep}=await c.from('legalizacao_processos').select('id,nte_id').eq('id',ant.processo_id).single();if(ep)throw ep;if(!master()&&Number(p.nte_id)!==Number(nteId()))throw new Error('Item fora da sua abrangência.');const {data,error}=await c.from('legalizacao_oferta_requisitos_processo').update({status,observacao:clean(payload.observacao),analisado_por_id:currentUserId(),analisado_em:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',itemId).select('*').single();if(error)throw error;return data;
}
async function listarProcessosOfertaRegulatorios(){
  assertAccess();const c=client();let q=c.from('legalizacao_processos').select('*').eq('tipo','OFERTA').order('updated_at',{ascending:false}).limit(500);q=scoped(q);const {data,error}=await q;if(error)throw error;const lista=data||[],pids=lista.map(x=>x.id),iids=[...new Set(lista.map(x=>x.instituicao_id).filter(Boolean))];let vinc=[],inst=[],cat=[],req=[];
  if(pids.length){let r=await c.from('legalizacao_processos_ofertas').select('*').in('processo_id',pids);if(r.error)throw r.error;vinc=r.data||[];r=await c.from('legalizacao_oferta_requisitos_processo').select('id,processo_id,requisito_catalogo_id,status').in('processo_id',pids);if(!r.error)req=r.data||[];}
  if(iids.length){const r=await c.from('legalizacao_instituicoes').select('id,nome_instituicao,tipo_cadastro,rede').in('id',iids);if(!r.error)inst=r.data||[];}
  const cids=[...new Set(vinc.map(x=>x.oferta_catalogo_id).filter(Boolean))];if(cids.length){const r=await c.from('legalizacao_oferta_catalogo').select('*').in('id',cids);if(!r.error)cat=r.data||[];}
  const im=new Map(inst.map(x=>[String(x.id),x])),cm=new Map(cat.map(x=>[String(x.id),x]));
  return lista.map(x=>{const ofertas=vinc.filter(v=>String(v.processo_id)===String(x.id)).map(v=>({...v,catalogo:cm.get(String(v.oferta_catalogo_id))||null}));const requisitos=req.filter(r=>String(r.processo_id)===String(x.id));return {...x,instituicao:im.get(String(x.instituicao_id))||null,ofertas,requisitos};});
}
async function iniciarProcedimentoOferta(instituicaoId,payload={}){
  assertAccess();const c=client(),inst=await oneScoped('legalizacao_instituicoes',instituicaoId),sei=clean(payload.numero_sei);if(!sei)throw new Error('Processo SEI é obrigatório para autorização de oferta.');
  const subtipo=upper(payload.subtipo||'AUTORIZACAO'),validos=['AUTORIZACAO','RENOVACAO','RECONHECIMENTO','RENOVACAO_RECONHECIMENTO'];if(!validos.includes(subtipo))throw new Error('Tipo de procedimento de oferta inválido.');
  const ids=[...new Set((Array.isArray(payload.oferta_catalogo_ids)?payload.oferta_catalogo_ids:[payload.oferta_catalogo_ids]).map(Number).filter(Boolean))];if(!ids.length)throw new Error('Selecione ao menos uma etapa/modalidade para o procedimento.');
  const {data:catalogo,error:ec}=await c.from('legalizacao_oferta_catalogo').select('*').in('id',ids).eq('ativo',true);if(ec)throw ec;if((catalogo||[]).length!==ids.length)throw new Error('Uma ou mais ofertas selecionadas não estão disponíveis no catálogo regulatório.');const exigeCurso=(catalogo||[]).some(o=>o.exige_curso_especifico===true),cursoNome=clean(payload.curso_nome),eixo=clean(payload.eixo_tecnologico);if(exigeCurso&&!cursoNome)throw new Error('Informe o nome do curso técnico para a oferta de Educação Profissional.');
  const base={instituicao_id:inst.id,nte_id:inst.nte_id,tipo:'OFERTA',subtipo,numero_sei:sei,status:'EM_ANDAMENTO',etapa_atual:'CONFIGURACAO_OFERTA',data_protocolo:payload.data_protocolo||today(),prazo_etapa:clean(payload.prazo_etapa),observacao:clean(payload.observacao),responsavel_id:currentUserId(),criado_por_id:currentUserId(),atualizado_por_id:currentUserId()};
  const {data:p,error:ep}=await c.from('legalizacao_processos').insert(base).select('*').single();if(ep)throw ep;
  const vinculos=ids.map(id=>{const oc=(catalogo||[]).find(o=>Number(o.id)===Number(id));return {processo_id:p.id,instituicao_id:inst.id,oferta_catalogo_id:id,curso_nome:oc?.exige_curso_especifico?cursoNome:null,eixo_tecnologico:oc?.exige_curso_especifico?eixo:null,status:'EM_ANALISE'};});const {error:ev}=await c.from('legalizacao_processos_ofertas').insert(vinculos);if(ev)throw ev;
  const {data:reqCat,error:er}=await c.from('legalizacao_oferta_requisitos_catalogo').select('*').eq('ativo',true).or(`oferta_catalogo_id.is.null,oferta_catalogo_id.in.(${ids.join(',')})`).order('ordem',{ascending:true});if(er)throw er;
  const unicos=new Map();for(const r of reqCat||[]){const chave=String(r.codigo||r.id);if(!unicos.has(chave)||r.oferta_catalogo_id)unicos.set(chave,r);}const reqRows=[...unicos.values()].map(r=>({processo_id:p.id,instituicao_id:inst.id,requisito_catalogo_id:r.id,status:'NAO_APRESENTADO'}));if(reqRows.length){const {error:erp}=await c.from('legalizacao_oferta_requisitos_processo').insert(reqRows);if(erp)throw erp;}
  await historicoProcesso(p.id,'ABERTURA_OFERTA','Procedimento de oferta criado com etapas/modalidades e requisitos parametrizados.',{numero_sei:sei,subtipo,ofertas:(catalogo||[]).map(o=>o.codigo),requisitos:reqRows.length});resumoCache=null;return {...p,ofertas:catalogo||[],requisitos_gerados:reqRows.length};
}

async function listarOfertasRegulatorias(){
  assertAccess();const inst=await listarInstituicoes();const lista=await safeChildren('legalizacao_ofertas','id,instituicao_id,processo_id,etapa_modalidade,curso_tecnico,eixo_tecnologico,ano_inicio_vigencia,ano_fim_vigencia,situacao,updated_at',inst);const im=new Map(inst.map(x=>[String(x.id),x]));return lista.map(x=>({...x,instituicao:im.get(String(x.instituicao_id))||null}));
}
async function listarCarimbosRegulatorios(){
  assertAccess();const inst=await listarInstituicoes();const lista=await safeChildren('legalizacao_autorizacoes_carimbo','id,instituicao_id,responsavel_id,tipo,ano_inicio,ano_fim,situacao,numero_sei,updated_at',inst);const im=new Map(inst.map(x=>[String(x.id),x]));const rids=[...new Set(lista.map(x=>x.responsavel_id).filter(Boolean))];let resp=[];if(rids.length){const c=client(),r=await c.from('legalizacao_responsaveis').select('id,nome,tipo').in('id',rids);if(!r.error)resp=r.data||[];}const rm=new Map(resp.map(x=>[String(x.id),x]));return lista.map(x=>({...x,instituicao:im.get(String(x.instituicao_id))||null,responsavel:rm.get(String(x.responsavel_id))||null}));
}

let atosControleCache=null,atosControleCacheEm=0;const ATOS_CONTROLE_TTL=120000;
async function listarAtosHistoricosControle(force=false,limit=1200){
  assertAccess();if(!force&&atosControleCache&&Date.now()-atosControleCacheEm<ATOS_CONTROLE_TTL)return atosControleCache;
  const c=client();if(!c)throw new Error('Cliente Supabase indisponível.');const lim=Math.min(2500,Math.max(100,intOrNull(limit)||1200));
  const {data,error}=await c.from('legalizacao_atos_legais').select('id,instituicao_id,escola_id,ato,tipo_ato,numero_ato,data_publicacao,numero_processo,vigencia_inicio,vigencia_fim,vigencia_origem,detalhe,fonte,situacao_registro,created_at').order('data_publicacao',{ascending:false,nullsFirst:false}).limit(lim);if(error)throw error;
  const atos=data||[],ids=[...new Set(atos.map(x=>Number(x.instituicao_id)).filter(Boolean))],inst=[];
  for(let i=0;i<ids.length;i+=300){let q=c.from('legalizacao_instituicoes').select('id,escola_id,nte_id,nome_instituicao,tipo_cadastro,rede,municipio,cod_inep').in('id',ids.slice(i,i+300));q=scoped(q);const r=await q;if(r.error)throw r.error;inst.push(...(r.data||[]));}
  const im=new Map(inst.map(x=>[String(x.id),x]));atosControleCache=atos.filter(x=>im.has(String(x.instituicao_id))).map(x=>({...x,instituicao:im.get(String(x.instituicao_id))}));atosControleCacheEm=Date.now();return atosControleCache;
}

async function listarBasePendenciasRegulatorias(){
  assertAccess();const c=client();if(!c)throw new Error('Cliente Supabase indisponível.');
  const instituicoes=[];const lote=1000;let inicio=0;
  while(true){
    let q=c.from('legalizacao_catalogo_v').select('prontuario_id,escola_id,nte_id,nome_instituicao,cod_inep,cod_sec,municipio,tipo_cadastro,rede,situacao_regulatoria,dados_importados_status').order('nome_instituicao',{ascending:true});q=scoped(q);
    const {data,error}=await q.range(inicio,inicio+lote-1);if(error)throw error;const rows=data||[];instituicoes.push(...rows);if(rows.length<lote)break;inicio+=lote;
  }
  const prontuarios=[...new Set(instituicoes.map(x=>Number(x.prontuario_id)).filter(Boolean))];const atos=[];
  for(let i=0;i<prontuarios.length;i+=500){
    const ids=prontuarios.slice(i,i+500);const {data,error}=await c.from('legalizacao_atos_legais').select('id,instituicao_id,ato,tipo_ato,numero_ato,data_publicacao,numero_processo,vigencia_inicio,vigencia_fim,vigencia_origem,detalhe,fonte,situacao_registro,created_at').in('instituicao_id',ids).limit(10000);if(error)throw error;atos.push(...(data||[]));
  }
  return{instituicoes,atos,gerado_em:new Date().toISOString()};
}
async function listarNtes(){const c=client();if(!c)return[];const {data,error}=await c.from('ntes_sigee').select('*').order('id',{ascending:true});if(error)return[];return data||[];}

async function listarInspecoesGerais(){
  assertAccess();const c=client();let q=c.from('legalizacao_inspecoes').select('*').order('created_at',{ascending:false}).limit(500);q=scoped(q);const {data,error}=await q;if(error)throw error;const lista=data||[];if(!lista.length)return[];
  const instIds=[...new Set(lista.map(x=>x.instituicao_id).filter(Boolean))],procIds=[...new Set(lista.map(x=>x.processo_id).filter(Boolean))];
  let inst=[],proc=[];if(instIds.length){const r=await c.from('legalizacao_instituicoes').select('id,nome_instituicao,nte_id').in('id',instIds);if(r.error)throw r.error;inst=r.data||[];}if(procIds.length){const r=await c.from('legalizacao_processos').select('id,numero_sei,tipo,status,etapa_atual').in('id',procIds);if(r.error)throw r.error;proc=r.data||[];}
  const im=new Map(inst.map(x=>[String(x.id),x])),pm=new Map(proc.map(x=>[String(x.id),x]));return lista.map(x=>({...x,instituicao:im.get(String(x.instituicao_id))||null,processo:pm.get(String(x.processo_id))||null}));
}
async function listarHistoricoRegulatorio(){
  assertAccess();const c=client();let q=c.from('legalizacao_processos').select('id,instituicao_id,nte_id,tipo,numero_sei,status,etapa_atual,data_protocolo,created_at,updated_at').order('updated_at',{ascending:false}).limit(700);q=scoped(q);const {data,error}=await q;if(error)throw error;const lista=data||[];if(!lista.length)return[];
  const instIds=[...new Set(lista.map(x=>x.instituicao_id).filter(Boolean))];let inst=[];if(instIds.length){const r=await c.from('legalizacao_instituicoes').select('id,nome_instituicao,nte_id').in('id',instIds);if(r.error)throw r.error;inst=r.data||[];}const im=new Map(inst.map(x=>[String(x.id),x]));return lista.map(x=>({...x,instituicao:im.get(String(x.instituicao_id))||null}));
}
async function criarInstituicao(payload){
  assertAccess();const c=client();if(!c)throw new Error('Cliente Supabase indisponível.');const n=master()?payload.nte_id:nteId();if(n==null||n==='')throw new Error('NTE obrigatório.');
  const tipo=upper(payload.tipo_cadastro||'PUBLICA'),rede=tipo==='PRIVADA'?'PRIVADA':upper(payload.rede||'ESTADUAL');
  const registro={nte_id:Number(n),nome_instituicao:String(payload.nome_instituicao||'').trim(),tipo_cadastro:tipo,rede,
    natureza:tipo==='PRIVADA'?'PRIVADA':(rede==='MUNICIPAL'?'PUBLICA_MUNICIPAL':'PUBLICA_ESTADUAL'),cod_sec:tipo==='PUBLICA'?clean(payload.cod_sec):null,cod_inep:clean(payload.cod_inep),cnpj:tipo==='PRIVADA'?digits(payload.mantenedora_cnpj,14):digits(payload.cnpj,14),municipio:clean(payload.municipio),
    telefone:digits(payload.telefone,11),whatsapp:digits(payload.whatsapp,11),email:clean(payload.email),logradouro:clean(payload.logradouro),numero:clean(payload.numero),complemento:clean(payload.complemento),bairro:clean(payload.bairro),cep:digits(payload.cep,8),situacao_imovel:upper(payload.situacao_imovel),uf:'BA',
    porte:clean(payload.porte),matriculas_referencia:intOrNull(payload.matriculas_referencia),ano_base_matriculas:intOrNull(payload.ano_base_matriculas),sistema_municipal_ensino:rede==='MUNICIPAL'?clean(payload.sistema_municipal_ensino):null,
    situacao_regulatoria:'EM_CADASTRO',origem:'CADASTRO_LEGALIZACAO',legado_sigee:false,criado_por_id:currentUserId(),atualizado_por_id:currentUserId()};
  if(!registro.nome_instituicao)throw new Error('Nome da instituição é obrigatório.');
  if(!['PUBLICA','PRIVADA'].includes(tipo))throw new Error('Tipo da instituição é obrigatório.');
  if(!registro.ano_base_matriculas)throw new Error('Ano-base é obrigatório.');
  if(!registro.logradouro)throw new Error('Logradouro é obrigatório.');
  if(!registro.cep)throw new Error('CEP é obrigatório.');
  if(!registro.municipio)throw new Error('Município é obrigatório.');
  if(!['PROPRIO','ALUGADO'].includes(registro.situacao_imovel))throw new Error('Informe obrigatoriamente se o imóvel é próprio ou alugado.');
  if((registro.cep||'').length!==8)throw new Error('CEP inválido. Informe 8 dígitos.');
  if(!cnpjValido(payload.mantenedora_cnpj))throw new Error('CNPJ da mantenedora inválido.');
  if(!cpfValido(payload.diretor_cpf))throw new Error('CPF do diretor inválido.');
  if(!cpfValido(payload.secretario_cpf))throw new Error('CPF do secretário inválido.');
  if(registro.telefone&&!telefoneValido(registro.telefone))throw new Error('Telefone da escola inválido. Informe DDD + número.');
  if(registro.whatsapp&&!telefoneValido(registro.whatsapp))throw new Error('WhatsApp da escola inválido. Informe DDD + número.');
  const municipiosNte=window.obterMunicipiosNTE?.(registro.nte_id)||[];
  if(municipiosNte.length&&!municipiosNte.some(x=>String(x.municipio||'').localeCompare(String(registro.municipio||''),'pt-BR',{sensitivity:'base'})===0))throw new Error('O município informado não pertence ao território do NTE do usuário.');
  const obrigatorios={
    'Razão social da mantenedora':payload.mantenedora_razao_social,'CNPJ da mantenedora':payload.mantenedora_cnpj,'Representante legal da mantenedora':payload.mantenedora_representante,
    'Telefone da mantenedora':payload.mantenedora_telefone,'WhatsApp da mantenedora':payload.mantenedora_whatsapp,'E-mail da mantenedora':payload.mantenedora_email,'Município da mantenedora':payload.mantenedora_municipio,
    'Nome do diretor':payload.diretor_nome,'CPF do diretor':payload.diretor_cpf,'Telefone do diretor':payload.diretor_telefone,'WhatsApp do diretor':payload.diretor_whatsapp,'E-mail do diretor':payload.diretor_email,
    'Nome do secretário':payload.secretario_nome,'CPF do secretário':payload.secretario_cpf,'Telefone do secretário':payload.secretario_telefone,'WhatsApp do secretário':payload.secretario_whatsapp,'E-mail do secretário':payload.secretario_email
  };
  const faltantes=Object.entries(obrigatorios).filter(([,v])=>!clean(v)).map(([k])=>k);if(faltantes.length)throw new Error('Campos obrigatórios pendentes: '+faltantes.join(', ')+'.');
  for(const [rotulo,campo] of [['Telefone da mantenedora','mantenedora_telefone'],['WhatsApp da mantenedora','mantenedora_whatsapp'],['Telefone do diretor','diretor_telefone'],['WhatsApp do diretor','diretor_whatsapp'],['Telefone do secretário','secretario_telefone'],['WhatsApp do secretário','secretario_whatsapp']])if(!telefoneValido(payload[campo],true))throw new Error(rotulo+' inválido. Informe DDD + número.');
  // RC12.0.10A.2 — proteção contra duplicidade antes de criar uma nova ficha institucional.
  const normalizar=v=>String(v||'').trim().replace(/[,()]/g,' ');
  const chaves=[];if(registro.cod_inep)chaves.push(`cod_inep.eq.${normalizar(registro.cod_inep)}`);if(registro.cnpj)chaves.push(`cnpj.eq.${normalizar(registro.cnpj)}`);
  if(chaves.length){let q=c.from('legalizacao_catalogo_v').select('prontuario_id,escola_id,nome_instituicao,cod_inep,cnpj,municipio').or(chaves.join(',')).limit(5);q=scoped(q);const {data:dup,error:ed}=await q;if(ed)throw ed;if((dup||[]).length)throw new Error(`Já existe instituição com o mesmo INEP/MEC ou CNPJ: ${(dup[0].nome_instituicao||'cadastro existente')}. Use “Localizar escola” e abra o prontuário existente.`);}
  const nomeBusca=normalizar(registro.nome_instituicao);if(nomeBusca&&registro.municipio){let q=c.from('legalizacao_catalogo_v').select('prontuario_id,escola_id,nome_instituicao,cod_inep,municipio').ilike('nome_instituicao',nomeBusca).ilike('municipio',normalizar(registro.municipio)).limit(5);q=scoped(q);const {data:dupNome,error:en}=await q;if(en)throw en;if((dupNome||[]).length)throw new Error(`Já existe uma instituição com esta denominação no município informado: ${dupNome[0].nome_instituicao}. Confirme o cadastro existente antes de criar uma nova ficha.`);}
  const {data,error}=await c.from('legalizacao_instituicoes').insert(registro).select('*').single();if(error)throw error;resumoCache=null;
  if(clean(payload.mantenedora_razao_social)){const {error:em}=await c.from('legalizacao_mantenedoras').insert({instituicao_id:data.id,razao_social:clean(payload.mantenedora_razao_social),cnpj:digits(payload.mantenedora_cnpj,14),representante_legal:clean(payload.mantenedora_representante),telefone:digits(payload.mantenedora_telefone,11),whatsapp:digits(payload.mantenedora_whatsapp,11),email:clean(payload.mantenedora_email),municipio:clean(payload.mantenedora_municipio),uf:'BA'});if(em)throw em;}
  for(const tipoResp of ['DIRETOR','SECRETARIO']){const pfx=tipoResp==='DIRETOR'?'diretor':'secretario';if(clean(payload[pfx+'_nome'])){const {error:er}=await c.from('legalizacao_responsaveis').insert({instituicao_id:data.id,tipo:tipoResp,nome:clean(payload[pfx+'_nome']),cpf:digits(payload[pfx+'_cpf'],11),telefone:digits(payload[pfx+'_telefone'],11),whatsapp:digits(payload[pfx+'_whatsapp'],11),email:clean(payload[pfx+'_email'])});if(er)throw er;}}
  return data;
}
async function atualizarInstituicao(instituicaoId,payload){
  assertAccess();const c=client();if(!c)throw new Error('Cliente Supabase indisponível.');
  let q=c.from('legalizacao_instituicoes').select('*').eq('id',instituicaoId);q=scoped(q);const {data:anterior,error:ea}=await q.maybeSingle();if(ea)throw ea;if(!anterior)throw new Error('Instituição não localizada na sua abrangência.');
  const n=master()?(payload.nte_id||anterior.nte_id):nteId();if(n==null||n==='')throw new Error('NTE obrigatório.');if(!master()&&Number(n)!==Number(anterior.nte_id))throw new Error('O NTE da instituição não pode ser alterado pelo usuário territorial.');
  const tipo=upper(payload.tipo_cadastro||anterior.tipo_cadastro||'PUBLICA'),rede=tipo==='PRIVADA'?'PRIVADA':upper(payload.rede||anterior.rede||'ESTADUAL');
  const registro={nte_id:Number(n),nome_instituicao:clean(payload.nome_instituicao),tipo_cadastro:tipo,rede,natureza:tipo==='PRIVADA'?'PRIVADA':(rede==='MUNICIPAL'?'PUBLICA_MUNICIPAL':'PUBLICA_ESTADUAL'),cod_sec:tipo==='PUBLICA'?clean(payload.cod_sec):null,cod_inep:clean(payload.cod_inep),cnpj:digits(payload.mantenedora_cnpj,14),municipio:clean(payload.municipio),telefone:digits(payload.telefone,11),whatsapp:digits(payload.whatsapp,11),email:clean(payload.email),logradouro:clean(payload.logradouro),numero:clean(payload.numero),complemento:clean(payload.complemento),bairro:clean(payload.bairro),cep:digits(payload.cep,8),situacao_imovel:upper(payload.situacao_imovel),uf:'BA',porte:clean(payload.porte),matriculas_referencia:intOrNull(payload.matriculas_referencia),ano_base_matriculas:intOrNull(payload.ano_base_matriculas),sistema_municipal_ensino:rede==='MUNICIPAL'?clean(payload.sistema_municipal_ensino):null,atualizado_por_id:currentUserId(),updated_at:new Date().toISOString()};
  const importado=anterior.legado_sigee===true||!!anterior.escola_id||upper(anterior.origem||'')!=='CADASTRO_LEGALIZACAO';
  if(!registro.nome_instituicao)throw new Error('Nome da instituição é obrigatório.');if(!['PUBLICA','PRIVADA'].includes(tipo))throw new Error('Tipo da instituição é obrigatório.');
  if(!importado){if(!registro.ano_base_matriculas)throw new Error('Ano-base é obrigatório.');if(!registro.logradouro)throw new Error('Logradouro é obrigatório.');if(registro.cep.length!==8)throw new Error('CEP inválido. Informe 8 dígitos.');if(!registro.municipio)throw new Error('Município é obrigatório.');if(!['PROPRIO','ALUGADO'].includes(registro.situacao_imovel))throw new Error('Informe obrigatoriamente se o imóvel é próprio ou alugado.');if(!cnpjValido(payload.mantenedora_cnpj))throw new Error('CNPJ da mantenedora inválido.');if(!cpfValido(payload.diretor_cpf))throw new Error('CPF do diretor inválido.');if(!cpfValido(payload.secretario_cpf))throw new Error('CPF do secretário inválido.');}
  else {if(registro.cep&&registro.cep.length!==8)throw new Error('CEP inválido. Informe 8 dígitos.');if(registro.situacao_imovel&&!['PROPRIO','ALUGADO'].includes(registro.situacao_imovel))throw new Error('Situação do imóvel inválida.');if(clean(payload.mantenedora_cnpj)&&!cnpjValido(payload.mantenedora_cnpj))throw new Error('CNPJ da mantenedora inválido.');if(clean(payload.diretor_cpf)&&!cpfValido(payload.diretor_cpf))throw new Error('CPF do diretor inválido.');if(clean(payload.secretario_cpf)&&!cpfValido(payload.secretario_cpf))throw new Error('CPF do secretário inválido.');}
  const obrigatorios={'Razão social da mantenedora':payload.mantenedora_razao_social,'CNPJ da mantenedora':payload.mantenedora_cnpj,'Representante legal da mantenedora':payload.mantenedora_representante,'Telefone da mantenedora':payload.mantenedora_telefone,'WhatsApp da mantenedora':payload.mantenedora_whatsapp,'E-mail da mantenedora':payload.mantenedora_email,'Município da mantenedora':payload.mantenedora_municipio,'Nome do diretor':payload.diretor_nome,'CPF do diretor':payload.diretor_cpf,'Telefone do diretor':payload.diretor_telefone,'WhatsApp do diretor':payload.diretor_whatsapp,'E-mail do diretor':payload.diretor_email,'Nome do secretário':payload.secretario_nome,'CPF do secretário':payload.secretario_cpf,'Telefone do secretário':payload.secretario_telefone,'WhatsApp do secretário':payload.secretario_whatsapp,'E-mail do secretário':payload.secretario_email};if(!importado){const faltantes=Object.entries(obrigatorios).filter(([,v])=>!clean(v)).map(([k])=>k);if(faltantes.length)throw new Error('Campos obrigatórios pendentes: '+faltantes.join(', ')+'.');}
  const municipiosNte=window.obterMunicipiosNTE?.(registro.nte_id)||[];if(registro.municipio&&municipiosNte.length&&!municipiosNte.some(x=>String(x.municipio||'').localeCompare(String(registro.municipio||''),'pt-BR',{sensitivity:'base'})===0))throw new Error('O município informado não pertence ao território do NTE do usuário.');
  for(const [rotulo,campo,obrig] of [['Telefone da escola','telefone',false],['WhatsApp da escola','whatsapp',false],['Telefone da mantenedora','mantenedora_telefone',!importado],['WhatsApp da mantenedora','mantenedora_whatsapp',!importado],['Telefone do diretor','diretor_telefone',!importado],['WhatsApp do diretor','diretor_whatsapp',!importado],['Telefone do secretário','secretario_telefone',!importado],['WhatsApp do secretário','secretario_whatsapp',!importado]])if((clean(payload[campo])||obrig)&&!telefoneValido(payload[campo],obrig))throw new Error(rotulo+' inválido. Informe DDD + número.');
  const {data,error}=await c.from('legalizacao_instituicoes').update(registro).eq('id',anterior.id).select('*').single();if(error)throw error;
  const mudouNte=Number(anterior.nte_id)!==Number(registro.nte_id);
  if(mudouNte){
    // Defesa adicional no cliente. A migração RC12.0.10A.11 instala o sincronismo definitivo no banco.
    for(const tabela of ['legalizacao_processos','legalizacao_fiscalizacoes','legalizacao_inspecoes','legalizacao_averiguacoes']){try{const r=await c.from(tabela).update({nte_id:registro.nte_id}).eq('instituicao_id',anterior.id);if(r.error&&!/relation|column|schema cache|does not exist/i.test(String(r.error.message||'')))throw r.error;}catch(e){console.warn('[Legalização] sincronismo territorial complementar falhou em',tabela,e?.message||e);}}
  }
  const mantenedora={razao_social:clean(payload.mantenedora_razao_social),cnpj:digits(payload.mantenedora_cnpj,14),representante_legal:clean(payload.mantenedora_representante),telefone:digits(payload.mantenedora_telefone,11),whatsapp:digits(payload.mantenedora_whatsapp,11),email:clean(payload.mantenedora_email),municipio:clean(payload.mantenedora_municipio),uf:'BA'};
  const temMantenedora=Object.entries(mantenedora).some(([k,v])=>k!=='uf'&&!!clean(v));let rm=await c.from('legalizacao_mantenedoras').select('id').eq('instituicao_id',anterior.id).order('created_at',{ascending:false}).limit(1);if(rm.error)throw rm.error;if(rm.data?.[0]){const r=await c.from('legalizacao_mantenedoras').update(mantenedora).eq('id',rm.data[0].id);if(r.error)throw r.error;}else if(temMantenedora){const r=await c.from('legalizacao_mantenedoras').insert({instituicao_id:anterior.id,...mantenedora});if(r.error)throw r.error;}
  for(const tipoResp of ['DIRETOR','SECRETARIO']){const pfx=tipoResp==='DIRETOR'?'diretor':'secretario',resp={tipo:tipoResp,nome:clean(payload[pfx+'_nome']),cpf:digits(payload[pfx+'_cpf'],11),telefone:digits(payload[pfx+'_telefone'],11),whatsapp:digits(payload[pfx+'_whatsapp'],11),email:clean(payload[pfx+'_email'])},temResp=Object.entries(resp).some(([k,v])=>k!=='tipo'&&!!clean(v));const rr=await c.from('legalizacao_responsaveis').select('id').eq('instituicao_id',anterior.id).eq('tipo',tipoResp).order('created_at',{ascending:false}).limit(1);if(rr.error)throw rr.error;if(rr.data?.[0]){const r=await c.from('legalizacao_responsaveis').update(resp).eq('id',rr.data[0].id);if(r.error)throw r.error;}else if(temResp){const r=await c.from('legalizacao_responsaveis').insert({instituicao_id:anterior.id,...resp});if(r.error)throw r.error;}}
  const campos=Object.keys(registro).filter(k=>!['atualizado_por_id','updated_at'].includes(k)&&String(anterior[k]??'')!==String(registro[k]??''));try{const u=user();await c.from('logs_sigee').insert({usuario_id:currentUserId(),nome:u?.nome||null,email:u?.email||null,acao:'Cadastro institucional atualizado.',created_at:new Date().toISOString(),nte:String(registro.nte_id),perfil:u?.perfil||null,detalhes:`Instituição ${anterior.id} · ${registro.nome_instituicao} · Campos alterados: ${campos.join(', ')||'mantenedora/responsáveis'}${mudouNte?` · Transferência territorial: NTE-${anterior.nte_id} → NTE-${registro.nte_id}`:''}`,modulo:'legalizacao',etapa:'CADASTRO',sessao_id:window.SIGEE_SESSAO_ID||null});}catch(e){console.warn('[Legalização] Cadastro salvo, mas o log complementar falhou:',e);}resumoCache=null;return anterior.escola_id?escolaParaInstituicao(await obterEscolaMestre(anterior.escola_id),data):data;
}
async function confirmarCadastroMigrado(instituicaoId){
  assertAccess();const c=client(),inst=await oneScoped('legalizacao_instituicoes',instituicaoId);if(upper(inst.situacao_regulatoria)!=='A_CONFIRMAR')throw new Error('Este cadastro não está aguardando confirmação.');
  const registro={situacao_regulatoria:'EM_CADASTRO',atualizado_por_id:currentUserId(),updated_at:new Date().toISOString()};
  const {data,error}=await c.from('legalizacao_instituicoes').update(registro).eq('id',inst.id).select('*').single();if(error)throw error;resumoCache=null;return data;
}
async function habilitarProntuario(escolaId){
  assertAccess();const c=client(),escola=await obterEscolaMestre(escolaId);if(!escola)throw new Error('Escola não localizada no cadastro mestre do SIGEE.');if(!master()&&Number(escola.nte_id)!==Number(nteId()))throw new Error('Escola fora da sua abrangência.');
  const {data:exist,error:ee}=await c.from('legalizacao_instituicoes').select('*').eq('escola_id',escola.id).order('id',{ascending:false}).limit(1);if(ee)throw ee;let ext=(exist||[])[0]||null;
  if(ext){if(['A_CONFIRMAR','NAO_HABILITADO'].includes(upper(ext.situacao_regulatoria))){const {data,error}=await c.from('legalizacao_instituicoes').update({situacao_regulatoria:'A_CONFERIR',dados_importados_status:'A_CONFERIR',atualizado_por_id:currentUserId(),updated_at:new Date().toISOString()}).eq('id',ext.id).select('*').single();if(error)throw error;ext=data;}resumoCache=null;return escolaParaInstituicao(escola,ext);}
  const priv=depPrivada(escola.dependencia_adm||escola.dependencia),dep=upper(escola.dependencia_adm||escola.dependencia);
  const registro={escola_id:escola.id,nte_id:escola.nte_id,nome_instituicao:escola.nome_escola||escola.nome,tipo_cadastro:priv?'PRIVADA':'PUBLICA',rede:priv?'PRIVADA':(dep.includes('MUNIC')?'MUNICIPAL':(dep.includes('FEDERAL')?'FEDERAL':'ESTADUAL')),natureza:priv?'PRIVADA':(dep.includes('MUNIC')?'PUBLICA_MUNICIPAL':(dep.includes('FEDERAL')?'PUBLICA_FEDERAL':'PUBLICA_ESTADUAL')),cod_inep:clean(escola.cod_mec),municipio:clean(escola.municipio),situacao_regulatoria:'A_CONFERIR',dados_importados_status:'A_CONFERIR',origem:'CATALOGO_SIGEE',legado_sigee:true,criado_por_id:currentUserId(),atualizado_por_id:currentUserId()};
  const {data,error}=await c.from('legalizacao_instituicoes').insert(registro).select('*').single();if(error)throw error;resumoCache=null;resumoCache=null;return escolaParaInstituicao(escola,data);
}
async function obterProntuario(instituicaoId){
  const c=client(),instituicao=await oneScoped('legalizacao_instituicoes',instituicaoId);
  const iid=instituicao.id;
  const queries=await Promise.all([
    c.from('legalizacao_mantenedoras').select('*').eq('instituicao_id',iid).order('created_at',{ascending:false}),
    c.from('legalizacao_responsaveis').select('*').eq('instituicao_id',iid).order('created_at',{ascending:false}),
    c.from('legalizacao_autorizacoes_carimbo').select('*').eq('instituicao_id',iid).order('ano_fim',{ascending:false}),
    c.from('legalizacao_ofertas').select('*').eq('instituicao_id',iid).order('created_at',{ascending:false}),
    c.from('legalizacao_processos').select('*').eq('instituicao_id',iid).order('created_at',{ascending:false}),
    c.from('legalizacao_fiscalizacoes').select('*').eq('instituicao_id',iid).order('created_at',{ascending:false}),
    c.from('legalizacao_inspecoes').select('*').eq('instituicao_id',iid).order('created_at',{ascending:false}),
    c.from('legalizacao_handoff_acervo').select('*').eq('instituicao_id',iid).order('created_at',{ascending:false}),
    c.from('legalizacao_atos_legais').select('id,ato,tipo_ato,numero_ato,data_publicacao,numero_processo,vigencia_inicio,vigencia_fim,vigencia_origem,detalhe,fonte,situacao_registro,created_at').eq('instituicao_id',iid).order('data_publicacao',{ascending:false}),
    c.from('legalizacao_irregularidade_acompanhamentos').select('*').eq('instituicao_id',iid).order('created_at',{ascending:false})
  ]);
  for(const r of queries){if(r.error)throw r.error;}
  let [mantenedoras,responsaveis,carimbos,ofertas,processos,fiscalizacoes,inspecoes,handoffs,atosLegais,irregularidades]=queries.map(r=>r.data||[]);
  if(inspecoes.length){
    const ids=inspecoes.map(x=>x.id);
    const {data:ii,error:eii}=await c.from('legalizacao_inspecao_itens').select('*').in('inspecao_id',ids).order('ordem',{ascending:true});if(eii)throw eii;
    const by=new Map();for(const x of ii||[]){const k=String(x.inspecao_id);if(!by.has(k))by.set(k,[]);by.get(k).push(x);}
    inspecoes=inspecoes.map(x=>({...x,itens:by.get(String(x.id))||[]}));
  }
  const cred=processos.find(p=>upper(p.tipo)==='CREDENCIAMENTO'&&!['CONCLUIDO','ARQUIVADO','CANCELADO'].includes(upper(p.status)))||processos.find(p=>upper(p.tipo)==='CREDENCIAMENTO')||null;
  const descredenciamento=processos.find(p=>upper(p.tipo)==='DESCREDENCIAMENTO'&&!['CONCLUIDO','ARQUIVADO','CANCELADO'].includes(upper(p.status)))||processos.find(p=>upper(p.tipo)==='DESCREDENCIAMENTO')||null;
  let checklist=[],credOfertas=[],ofertaChecklist=[],checklistDescredenciamento=[];if(cred){
    const {data:it,error:ei}=await c.from('legalizacao_checklist_processo').select('*').eq('processo_id',cred.id).order('id',{ascending:true});if(ei)throw ei;
    const ids=[...new Set((it||[]).map(x=>x.catalogo_id).filter(Boolean))];let cat=[];if(ids.length){const {data,error}=await c.from('legalizacao_checklist_catalogo').select('*').in('id',ids).order('ordem',{ascending:true});if(error)throw error;cat=data||[];}
    const by=new Map(cat.map(x=>[String(x.id),x]));checklist=(it||[]).map(x=>({...x,catalogo:by.get(String(x.catalogo_id))||null})).sort((a,b)=>(a.catalogo?.ordem||0)-(b.catalogo?.ordem||0));
    let r=await c.from('legalizacao_processos_ofertas').select('*').eq('processo_id',cred.id).order('id',{ascending:true});if(r.error)throw r.error;credOfertas=r.data||[];const cids=[...new Set(credOfertas.map(x=>x.oferta_catalogo_id).filter(Boolean))];let oc=[];if(cids.length){r=await c.from('legalizacao_oferta_catalogo').select('*').in('id',cids);if(r.error)throw r.error;oc=r.data||[];}const om=new Map(oc.map(x=>[String(x.id),x]));credOfertas=credOfertas.map(x=>({...x,catalogo:om.get(String(x.oferta_catalogo_id))||null}));
    r=await c.from('legalizacao_oferta_requisitos_processo').select('*').eq('processo_id',cred.id).order('id',{ascending:true});if(r.error)throw r.error;const ori=r.data||[],rids=[...new Set(ori.map(x=>x.requisito_catalogo_id).filter(Boolean))];let rc=[];if(rids.length){r=await c.from('legalizacao_oferta_requisitos_catalogo').select('*').in('id',rids).order('ordem',{ascending:true});if(r.error)throw r.error;rc=r.data||[];}const rm=new Map(rc.map(x=>[String(x.id),x]));ofertaChecklist=ori.map(x=>({...x,catalogo:rm.get(String(x.requisito_catalogo_id))||null})).sort((a,b)=>(a.catalogo?.ordem||0)-(b.catalogo?.ordem||0));
  }
  if(descredenciamento){checklistDescredenciamento=await garantirChecklistDescredenciamento(descredenciamento);}
  return {instituicao,mantenedoras,responsaveis,carimbos,ofertas,processos,fiscalizacoes,inspecoes,handoffs,atosLegais,irregularidades,credenciamento:cred,checklist,credOfertas,ofertaChecklist,descredenciamento,checklistDescredenciamento};
}
async function historicoProcesso(processoId,tipo,descricao,meta=null){const c=client();const {error}=await c.from('legalizacao_processos_historico').insert({processo_id:processoId,tipo,descricao,meta,usuario_id:currentUserId()});if(error)throw error;}
async function iniciarCredenciamento(instituicaoId,payload={}){
  assertAccess();const c=client(),inst=await oneScoped('legalizacao_instituicoes',instituicaoId),sei='';
  const subtipo=upper(payload.subtipo||'CREDENCIAMENTO');if(!['CREDENCIAMENTO','RECREDENCIAMENTO'].includes(subtipo))throw new Error('Tipo de procedimento inválido.');
  const {data:exist,error:ee}=await c.from('legalizacao_processos').select('id,status').eq('instituicao_id',inst.id).eq('tipo','CREDENCIAMENTO').limit(20);if(ee)throw ee;if((exist||[]).some(x=>!['CONCLUIDO','ARQUIVADO','CANCELADO'].includes(upper(x.status))))throw new Error('Já existe credenciamento/recredenciamento ativo para esta instituição.');
  const obsOriginal=clean(payload.observacao),obsLegado=subtipo==='RECREDENCIAMENTO'?`[RECREDENCIAMENTO]${obsOriginal?' '+obsOriginal:''}`:obsOriginal;
  const base={instituicao_id:inst.id,nte_id:inst.nte_id,tipo:'CREDENCIAMENTO',numero_sei:null,status:'EM_ANDAMENTO',etapa_atual:'RECEBIMENTO_DOCUMENTAL',data_protocolo:null,observacao:obsOriginal,criado_por_id:currentUserId(),atualizado_por_id:currentUserId()};
  const enriquecido={...base,subtipo,responsavel_id:currentUserId(),prazo_etapa:clean(payload.prazo_etapa)};
  let p=null;let r=await c.from('legalizacao_processos').insert(enriquecido).select('*').single();
  if(r.error){const msg=String(r.error.message||'');const colunaOpcional=/subtipo|responsavel_id|prazo_etapa|schema cache|column/i.test(msg);if(!colunaOpcional)throw r.error;const legado={...base,observacao:obsLegado};r=await c.from('legalizacao_processos').insert(legado).select('*').single();if(r.error)throw r.error;p={...r.data,subtipo,responsavel_id:currentUserId(),prazo_etapa:clean(payload.prazo_etapa)};}else p=r.data;
  let cq=c.from('legalizacao_checklist_catalogo').select('*').eq('tipo_processo','CREDENCIAMENTO').eq('ativo',true).order('ordem',{ascending:true});
  cq=upper(inst.tipo_cadastro)==='PRIVADA'?cq.eq('aplica_privada',true):cq.eq('aplica_publica',true);
  const {data:catalogo,error:ec}=await cq;if(ec)throw ec;
  if((catalogo||[]).length){const rows=catalogo.map(x=>({processo_id:p.id,catalogo_id:x.id,status:'NAO_APRESENTADO'}));const {error:er}=await c.from('legalizacao_checklist_processo').insert(rows);if(er)throw er;}
  const {error:ui}=await c.from('legalizacao_instituicoes').update({situacao_regulatoria:'EM_CREDENCIAMENTO',atualizado_por_id:currentUserId(),updated_at:new Date().toISOString()}).eq('id',inst.id);if(ui)throw ui;
  await historicoProcesso(p.id,'ABERTURA',`${subtipo==='RECREDENCIAMENTO'?'Recredenciamento':'Credenciamento'} iniciado no SIGEE para recebimento documental.`,{numero_sei:null,tipo_cadastro:inst.tipo_cadastro,subtipo,prazo_etapa:clean(payload.prazo_etapa)});resumoCache=null;return p;
}


async function registrarProcessoSeiCredenciamento(processoId,payload={}){
  assertAccess();const c=client(),p=await processoCredenciamento(processoId);if(clean(p.numero_sei))throw new Error('Este procedimento já possui Processo SEI registrado.');
  const sei=clean(payload.numero_sei);if(!sei)throw new Error('Informe o número do Processo SEI.');
  const {data:it,error:ei}=await c.from('legalizacao_checklist_processo').select('status,catalogo_id').eq('processo_id',p.id);if(ei)throw ei;
  const catIds=[...new Set((it||[]).map(x=>x.catalogo_id).filter(Boolean))];let obrigatorios=new Set();if(catIds.length){const {data:cats,error:ec}=await c.from('legalizacao_checklist_catalogo').select('id,obrigatorio').in('id',catIds);if(ec)throw ec;obrigatorios=new Set((cats||[]).filter(x=>x.obrigatorio).map(x=>String(x.id)));}
  const pend=(it||[]).filter(x=>obrigatorios.has(String(x.catalogo_id))&&!['APRESENTADO','CONFORME','NAO_SE_APLICA'].includes(upper(x.status)));if(pend.length)throw new Error(`Ainda existem ${pend.length} documento(s) obrigatório(s) não encaminhado(s). O Processo SEI só pode ser registrado após o encaminhamento documental.`);
  const dataProtocolo=clean(payload.data_protocolo)||today(),now=new Date().toISOString();
  const {data,error}=await c.from('legalizacao_processos').update({numero_sei:sei,data_protocolo:dataProtocolo,etapa_atual:'ANALISE_DOCUMENTAL',status:'EM_ANDAMENTO',atualizado_por_id:currentUserId(),updated_at:now}).eq('id',p.id).select('*').single();if(error)throw error;
  await historicoProcesso(p.id,'PROCESSO_SEI_REGISTRADO','Documentação encaminhada e Processo SEI registrado.',{numero_sei:sei,data_protocolo:dataProtocolo});return data;
}

async function atualizarChecklist(itemId,payload={}){
  assertAccess();const c=client(),status=upper(payload.status);const valid=['NAO_APRESENTADO','APRESENTADO','EM_ANALISE','CONFORME','NAO_CONFORME','NAO_SE_APLICA'];if(!valid.includes(status))throw new Error('Situação de checklist inválida.');
  const {data:ant,error:ea}=await c.from('legalizacao_checklist_processo').select('*').eq('id',itemId).single();if(ea)throw ea;const {data:proc,error:eproc}=await c.from('legalizacao_processos').select('id,nte_id').eq('id',ant.processo_id).single();if(eproc)throw eproc;if(!master()&&Number(proc.nte_id)!==Number(nteId()))throw new Error('Item fora da sua abrangência.');
  const registro={status,observacao:clean(payload.observacao),analisado_por_id:currentUserId(),analisado_em:new Date().toISOString()};const {data,error}=await c.from('legalizacao_checklist_processo').update(registro).eq('id',itemId).select('*').single();if(error)throw error;
  const {error:eh}=await c.from('legalizacao_checklist_historico').insert({checklist_item_id:itemId,processo_id:ant.processo_id,status_anterior:ant.status,status_novo:status,observacao:clean(payload.observacao),usuario_id:currentUserId()});if(eh)throw eh;return data;
}
async function emitirDiligencia(processoId,observacao){assertAccess();const c=client();const {data:p,error:ep}=await c.from('legalizacao_processos').select('*').eq('id',processoId).single();if(ep)throw ep;if(!master()&&Number(p.nte_id)!==Number(nteId()))throw new Error('Processo fora da sua abrangência.');const {error}=await c.from('legalizacao_processos').update({status:'EM_DILIGENCIA',etapa_atual:'DILIGENCIA',diligencia_em:new Date().toISOString(),observacao:clean(observacao)||p.observacao,atualizado_por_id:currentUserId(),updated_at:new Date().toISOString()}).eq('id',processoId);if(error)throw error;await historicoProcesso(processoId,'DILIGENCIA','Processo colocado em diligência documental.',{observacao:clean(observacao)});}
async function retomarAnalise(processoId){assertAccess();const c=client();const {data:p,error:ep}=await c.from('legalizacao_processos').select('*').eq('id',processoId).single();if(ep)throw ep;if(!master()&&Number(p.nte_id)!==Number(nteId()))throw new Error('Processo fora da sua abrangência.');const {error}=await c.from('legalizacao_processos').update({status:'EM_ANDAMENTO',etapa_atual:'ANALISE_DOCUMENTAL',atualizado_por_id:currentUserId(),updated_at:new Date().toISOString()}).eq('id',processoId);if(error)throw error;await historicoProcesso(processoId,'RETOMADA_ANALISE','Análise documental retomada após diligência.');}
async function prepararInspecao(processoId){
  assertAccess();const c=client();const {data:p,error:ep}=await c.from('legalizacao_processos').select('*').eq('id',processoId).single();if(ep)throw ep;if(!master()&&Number(p.nte_id)!==Number(nteId()))throw new Error('Processo fora da sua abrangência.');if(!clean(p.numero_sei))throw new Error('Registre o Processo SEI após o encaminhamento documental antes de preparar a inspeção.');
  const {data:it,error:ei}=await c.from('legalizacao_checklist_processo').select('status,catalogo_id').eq('processo_id',processoId);if(ei)throw ei;const catIds=[...new Set((it||[]).map(x=>x.catalogo_id).filter(Boolean))];let obrigatorios=new Set();if(catIds.length){const {data:cats,error:ec}=await c.from('legalizacao_checklist_catalogo').select('id,obrigatorio').in('id',catIds);if(ec)throw ec;obrigatorios=new Set((cats||[]).filter(x=>x.obrigatorio).map(x=>String(x.id)));}
  const pend=(it||[]).filter(x=>obrigatorios.has(String(x.catalogo_id))&&!['APRESENTADO','CONFORME','NAO_SE_APLICA'].includes(upper(x.status)));if(pend.length)throw new Error(`Ainda existem ${pend.length} item(ns) obrigatório(s) pendente(s) no checklist institucional.`);
  const {data:ori,error:eori}=await c.from('legalizacao_oferta_requisitos_processo').select('status,requisito_catalogo_id').eq('processo_id',processoId);if(eori)throw eori;const orids=[...new Set((ori||[]).map(x=>x.requisito_catalogo_id).filter(Boolean))];let obrigOferta=new Set();if(orids.length){const {data:orcat,error:eorc}=await c.from('legalizacao_oferta_requisitos_catalogo').select('id,obrigatorio').in('id',orids);if(eorc)throw eorc;obrigOferta=new Set((orcat||[]).filter(x=>x.obrigatorio).map(x=>String(x.id)));}const pendOferta=(ori||[]).filter(x=>obrigOferta.has(String(x.requisito_catalogo_id))&&!['APRESENTADO','CONFORME','NAO_SE_APLICA'].includes(upper(x.status)));if(pendOferta.length)throw new Error(`Ainda existem ${pendOferta.length} requisito(s) obrigatório(s) de oferta pendente(s).`);
  const {data:ins,error:eins}=await c.from('legalizacao_inspecoes').select('*').eq('processo_id',processoId).limit(1);if(eins)throw eins;let insp=(ins||[])[0]||null;
  if(!insp){const motivo=upper(p.tipo)==='OFERTA'?(upper(p.subtipo)||'AUTORIZACAO'):upper(p.tipo)==='ALTERACAO_CADASTRAL'?'MUDANCA_CADASTRAL':(upper(p.subtipo)||'CREDENCIAMENTO');const {data:ni,error}=await c.from('legalizacao_inspecoes').insert({processo_id:processoId,instituicao_id:p.instituicao_id,nte_id:p.nte_id,natureza:'MANUTENCAO_REGULATORIA',motivo,status:'AGENDAMENTO',responsavel_id:currentUserId()}).select('*').single();if(error)throw error;insp=ni;}
  const {data:existItens,error:eex}=await c.from('legalizacao_inspecao_itens').select('id').eq('inspecao_id',insp.id).limit(1);if(eex)throw eex;
  if(!(existItens||[]).length){const {data:cat,error:ecat}=await c.from('legalizacao_inspecao_catalogo').select('*').eq('ativo',true).order('ordem',{ascending:true});if(ecat)throw ecat;if((cat||[]).length){const rows=cat.map(x=>({inspecao_id:insp.id,codigo_item:x.codigo_item,categoria:x.categoria,descricao:x.descricao,referencia_normativa:x.referencia_normativa,resultado:'PENDENTE',ordem:x.ordem}));const {error:eri}=await c.from('legalizacao_inspecao_itens').insert(rows);if(eri)throw eri;}}
  const now=new Date().toISOString();const {error}=await c.from('legalizacao_processos').update({status:'EM_ANDAMENTO',etapa_atual:'AGUARDANDO_INSPECAO',checklist_concluido_em:now,checklist_concluido_por_id:currentUserId(),atualizado_por_id:currentUserId(),updated_at:now}).eq('id',processoId);if(error)throw error;await historicoProcesso(processoId,'CHECKLIST_CONCLUIDO','Checklist documental concluído; processo preparado para inspeção.');return insp;
}
async function agendarInspecao(inspecaoId,dataAgendada){assertAccess();const c=client();const {data:i,error:ei}=await c.from('legalizacao_inspecoes').select('*').eq('id',inspecaoId).single();if(ei)throw ei;if(!master()&&Number(i.nte_id)!==Number(nteId()))throw new Error('Inspeção fora da sua abrangência.');if(!dataAgendada)throw new Error('Informe a data da inspeção.');const now=new Date().toISOString();const {data,error}=await c.from('legalizacao_inspecoes').update({data_agendada:dataAgendada,status:'AGENDADA',responsavel_id:i.responsavel_id||currentUserId(),updated_at:now}).eq('id',inspecaoId).select('*').single();if(error)throw error;await historicoProcesso(i.processo_id,'INSPECAO_AGENDADA','Inspeção agendada.',{data_agendada:dataAgendada});return data;}
async function atualizarItemInspecao(itemId,payload={}){assertAccess();const c=client(),resultado=upper(payload.resultado);if(!['PENDENTE','CONFORME','NAO_CONFORME','NAO_SE_APLICA'].includes(resultado))throw new Error('Resultado de inspeção inválido.');const {data:ant,error:ea}=await c.from('legalizacao_inspecao_itens').select('*').eq('id',itemId).single();if(ea)throw ea;const {data:i,error:ei}=await c.from('legalizacao_inspecoes').select('*').eq('id',ant.inspecao_id).single();if(ei)throw ei;if(!master()&&Number(i.nte_id)!==Number(nteId()))throw new Error('Item fora da sua abrangência.');const {data,error}=await c.from('legalizacao_inspecao_itens').update({resultado,observacao:clean(payload.observacao),orientacao:clean(payload.orientacao),analisado_por_id:currentUserId(),analisado_em:new Date().toISOString()}).eq('id',itemId).select('*').single();if(error)throw error;return data;}
async function registrarRealizacaoInspecao(inspecaoId,dataRealizada){assertAccess();const c=client();const {data:i,error:ei}=await c.from('legalizacao_inspecoes').select('*').eq('id',inspecaoId).single();if(ei)throw ei;if(!master()&&Number(i.nte_id)!==Number(nteId()))throw new Error('Inspeção fora da sua abrangência.');const d=dataRealizada||today(),now=new Date().toISOString();const {data,error}=await c.from('legalizacao_inspecoes').update({data_realizada:d,status:'REALIZADA',responsavel_id:i.responsavel_id||currentUserId(),updated_at:now}).eq('id',inspecaoId).select('*').single();if(error)throw error;await historicoProcesso(i.processo_id,'INSPECAO_REALIZADA','Verificação in loco registrada.',{data_realizada:d});return data;}
async function concluirInspecao(inspecaoId,payload={}){assertAccess();const c=client();const {data:i,error:ei}=await c.from('legalizacao_inspecoes').select('*').eq('id',inspecaoId).single();if(ei)throw ei;if(!master()&&Number(i.nte_id)!==Number(nteId()))throw new Error('Inspeção fora da sua abrangência.');const {data:it,error:eii}=await c.from('legalizacao_inspecao_itens').select('id,resultado').eq('inspecao_id',inspecaoId);if(eii)throw eii;const pend=(it||[]).filter(x=>upper(x.resultado)==='PENDENTE');if(pend.length)throw new Error(`Ainda existem ${pend.length} item(ns) sem conclusão na inspeção.`);const rg=upper(payload.resultado_global);if(!['FAVORAVEL','FAVORAVEL_COM_RESSALVAS','DESFAVORAVEL'].includes(rg))throw new Error('Informe a conclusão técnica da inspeção.');const texto=clean(payload.relatorio_tecnico);if(!texto)throw new Error('Registre a conclusão/relatório técnico.');const now=new Date().toISOString();const {data,error}=await c.from('legalizacao_inspecoes').update({data_realizada:i.data_realizada||today(),status:'CONCLUIDA',resultado_global:rg,relatorio_tecnico:texto,conclusao:texto,relatorio_concluido_em:now,relatorio_concluido_por_id:currentUserId(),updated_at:now}).eq('id',inspecaoId).select('*').single();if(error)throw error;const {error:ep}=await c.from('legalizacao_processos').update({status:'EM_ANDAMENTO',etapa_atual:'ANALISE_FINAL',atualizado_por_id:currentUserId(),updated_at:now}).eq('id',i.processo_id);if(ep)throw ep;await historicoProcesso(i.processo_id,'RELATORIO_TECNICO_CONCLUIDO','Relatório técnico da inspeção concluído.',{resultado_global:rg});return data;}
async function processoCredenciamento(processoId){assertAccess();const c=client();let q=c.from('legalizacao_processos').select('*').eq('id',processoId).eq('tipo','CREDENCIAMENTO');q=scoped(q);const {data,error}=await q.maybeSingle();if(error)throw error;if(!data)throw new Error('Credenciamento não localizado na sua abrangência.');return data;}
async function concluirAnaliseFinal(processoId,payload={}){
  const c=client(),p=await processoCredenciamento(processoId);if(upper(p.etapa_atual)!=='ANALISE_FINAL')throw new Error('O processo não está na etapa de Análise Final.');
  const parecer=clean(payload.parecer_final);if(!parecer)throw new Error('Registre o parecer da análise final.');
  const {data:ins,error:ei}=await c.from('legalizacao_inspecoes').select('id,status,resultado_global').eq('processo_id',p.id).order('created_at',{ascending:false}).limit(1);if(ei)throw ei;const ultima=(ins||[])[0];if(!ultima||upper(ultima.status)!=='CONCLUIDA')throw new Error('A inspeção precisa estar concluída.');if(upper(ultima.resultado_global)==='DESFAVORAVEL')throw new Error('A inspeção desfavorável não pode seguir para publicação. Registre a diligência cabível.');
  const now=new Date().toISOString(),registro={parecer_final:parecer,decisao_final:'DEFERIDO',analise_final_concluida_em:now,analise_final_por_id:currentUserId(),status:'EM_ANDAMENTO',etapa_atual:'AGUARDANDO_PUBLICACAO',atualizado_por_id:currentUserId(),updated_at:now};
  const {data,error}=await c.from('legalizacao_processos').update(registro).eq('id',p.id).select('*').single();if(error)throw error;await historicoProcesso(p.id,'ANALISE_FINAL_CONCLUIDA','Análise final deferida; processo aguardando publicação.',{decisao:'DEFERIDO'});return data;
}
async function registrarPublicacao(processoId,payload={}){
  const c=client(),p=await processoCredenciamento(processoId);if(upper(p.etapa_atual)!=='AGUARDANDO_PUBLICACAO')throw new Error('O processo não está aguardando publicação.');
  const numero=clean(payload.numero_ato),dataAto=clean(payload.data_ato),dataPublicacao=clean(payload.data_publicacao),referencia=clean(payload.referencia_doe);if(!numero||!dataAto||!dataPublicacao||!referencia)throw new Error('Informe número e data do ato, data da publicação e referência do DOE.');
  const inicio=clean(payload.vigencia_inicio),fim=clean(payload.vigencia_fim);if(inicio&&fim&&fim<inicio)throw new Error('O fim da vigência não pode ser anterior ao início.');
  const link=clean(payload.doe_url);if(link&&!/^https?:\/\//i.test(link))throw new Error('O link do DOE deve iniciar com http:// ou https://.');
  const now=new Date().toISOString(),registro={tipo_ato:clean(payload.tipo_ato)||'CREDENCIAMENTO',numero_ato:numero,data_ato:dataAto,data_publicacao:dataPublicacao,referencia_doe:referencia,doe_url:link,vigencia_inicio:inicio,vigencia_fim:fim,publicado_em:now,publicado_por_id:currentUserId(),status:'EM_ANDAMENTO',etapa_atual:'PUBLICADO',atualizado_por_id:currentUserId(),updated_at:now};
  const {data,error}=await c.from('legalizacao_processos').update(registro).eq('id',p.id).select('*').single();if(error)throw error;await historicoProcesso(p.id,'PUBLICACAO_REGISTRADA','Publicação no Diário Oficial registrada no SIGEE.',{numero_ato:numero,data_publicacao:dataPublicacao,referencia_doe:referencia});return data;
}
async function concluirCredenciamento(processoId){
  const c=client(),p=await processoCredenciamento(processoId);if(upper(p.etapa_atual)!=='PUBLICADO'||!p.data_publicacao||!p.numero_ato)throw new Error('Registre a publicação antes de concluir o credenciamento.');
  const now=new Date().toISOString();const {data,error}=await c.from('legalizacao_processos').update({status:'CONCLUIDO',etapa_atual:'CREDENCIAMENTO_CONCLUIDO',credenciamento_concluido_em:now,credenciamento_concluido_por_id:currentUserId(),atualizado_por_id:currentUserId(),updated_at:now}).eq('id',p.id).select('*').single();if(error)throw error;
  const {error:ei}=await c.from('legalizacao_instituicoes').update({situacao_regulatoria:'CREDENCIADA',atualizado_por_id:currentUserId(),updated_at:now}).eq('id',p.instituicao_id);if(ei)throw ei;await historicoProcesso(p.id,'CREDENCIAMENTO_CONCLUIDO','Credenciamento concluído após registro da publicação.',{numero_ato:p.numero_ato,data_publicacao:p.data_publicacao});resumoCache=null;return data;
}

async function listarAlteracoesCadastrais(){assertAccess();const c=client();let q=c.from('legalizacao_processos').select('*,instituicao:legalizacao_instituicoes(id,nome_instituicao,municipio,nte_id)').eq('tipo','ALTERACAO_CADASTRAL').order('created_at',{ascending:false}).limit(300);q=scoped(q);const {data,error}=await q;if(error)throw error;return data||[];}
async function iniciarAlteracaoCadastral(instituicaoId,payload={}){assertAccess();const inst=await oneScoped('legalizacao_instituicoes',instituicaoId),c=client();const subt=String(payload.subtipo||'OUTRA').toUpperCase();if(!['ENDERECO','DENOMINACAO','MANTENEDORA','RESPONSAVEIS','OUTRA'].includes(subt))throw new Error('Tipo de alteração cadastral inválido.');if(!clean(payload.observacao))throw new Error('Descreva a alteração cadastral.');const now=new Date().toISOString(),row={instituicao_id:inst.id,nte_id:inst.nte_id,tipo:'ALTERACAO_CADASTRAL',subtipo:subt,numero_sei:clean(payload.numero_sei),data_protocolo:clean(payload.data_protocolo),prazo_etapa:clean(payload.prazo_etapa),observacao:clean(payload.observacao),status:'EM_ANDAMENTO',etapa_atual:'ANALISE_CADASTRAL',responsavel_id:currentUserId(),criado_por_id:currentUserId(),atualizado_por_id:currentUserId(),created_at:now,updated_at:now};const {data,error}=await c.from('legalizacao_processos').insert(row).select('*').single();if(error)throw error;await historicoProcesso(data.id,'ABERTURA_ALTERACAO_CADASTRAL','Procedimento de alteração cadastral aberto.',{subtipo:subt});return data;}

async function registrarAcaoIrregularidade(acompanhamentoId,payload={}){assertAccess();const c=client();const id=Number(acompanhamentoId),acao=String(payload.acao||'').toUpperCase(),data=clean(payload.data_acao),obs=clean(payload.observacao);if(!id||!data||!obs)throw new Error('Informe a data e o registro da ação.');let q=c.from('legalizacao_irregularidade_acompanhamentos').select('*').eq('id',id);q=scoped(q);const {data:ac,error:e0}=await q.maybeSingle();if(e0)throw e0;if(!ac)throw new Error('Acompanhamento não localizado no território.');const esperado={VISITA_TECNICA_ORIENTACAO:'NOTIFICACAO_01',NOTIFICACAO_01:'NOTIFICACAO_02',NOTIFICACAO_02:'NOTIFICACAO_03'}[String(ac.etapa_atual||'VISITA_TECNICA_ORIENTACAO').toUpperCase()];if(!esperado||acao!==esperado)throw new Error('A ação informada não corresponde à próxima etapa disponível.');let prazo=null,dias=null,sei=null,status='EM_ACOMPANHAMENTO';if(acao==='NOTIFICACAO_03'){sei=clean(payload.numero_sei);if(!sei)throw new Error('Informe o Processo SEI do encaminhamento ao Ministério Público.');status='ENCAMINHADO_MP';}else{dias=Number(payload.prazo_dias);if(![15,20,25,30,35,40,45,50,60].includes(dias))throw new Error('Selecione o prazo concedido para esta ação.');const d=new Date(data+'T12:00:00');d.setDate(d.getDate()+dias);prazo=d.toISOString().slice(0,10);}const upd={etapa_atual:acao,status,prazo_atual:prazo,prazo_dias:dias,updated_at:new Date().toISOString()};if(acao==='NOTIFICACAO_03'){upd.numero_sei_mp=sei;upd.data_encaminhamento_mp=data;}const {error:e1}=await c.from('legalizacao_irregularidade_acompanhamentos').update(upd).eq('id',id);if(e1)throw e1;const label={NOTIFICACAO_01:'Notificação 01',NOTIFICACAO_02:'Notificação 02 (Reiteração)',NOTIFICACAO_03:'Notificação 03 (Encaminhamento ao Ministério Público)'}[acao];const desc=acao==='NOTIFICACAO_03'?`${label}. Processo SEI: ${sei}. ${obs}`:`${label}. Prazo concedido: ${dias} dias. ${obs}`;const {error:e2}=await c.from('legalizacao_irregularidade_eventos').insert({acompanhamento_id:id,tipo_evento:acao,data_evento:data,prazo_limite:prazo,descricao:desc,criado_por_id:currentUserId()});if(e2)throw e2;return true;}

async function garantirChecklistIrregularidade(acompanhamentoId){
  assertAccess();const c=client(),id=Number(acompanhamentoId);if(!id)throw new Error('Acompanhamento inválido.');
  let q=c.from('legalizacao_irregularidade_acompanhamentos').select('*').eq('id',id);q=scoped(q);const {data:ac,error:ea}=await q.maybeSingle();if(ea)throw ea;if(!ac)throw new Error('Acompanhamento não localizado no território.');
  const {data:exist,error:ee}=await c.from('legalizacao_irregularidade_checklist').select('*').eq('acompanhamento_id',id).order('irregularidade_codigo',{ascending:true}).order('ordem',{ascending:true});if(ee)throw ee;if((exist||[]).length)return exist||[];
  const irregs=Array.isArray(ac.irregularidades)?ac.irregularidades:[];if(!irregs.length)return[];
  const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
  const {data:ofertas,error:eo}=await c.from('legalizacao_oferta_catalogo').select('*').eq('ativo',true).order('ordem',{ascending:true});if(eo)throw eo;
  const alvo={
    AUTORIZACAO_VENCIDA_EF1:['FUNDAMENTAL I','ANOS INICIAIS'],OFERTA_SEM_AUTORIZACAO_EF1:['FUNDAMENTAL I','ANOS INICIAIS'],
    AUTORIZACAO_VENCIDA_EF2:['FUNDAMENTAL II','ANOS FINAIS'],OFERTA_SEM_AUTORIZACAO_EF2:['FUNDAMENTAL II','ANOS FINAIS'],
    AUTORIZACAO_VENCIDA_EM:['ENSINO MEDIO'],OFERTA_SEM_AUTORIZACAO_EM:['ENSINO MEDIO']
  };
  const rows=[];
  for(const irr of irregs){
    if(irr==='UNIDADE_FILIAL_SEM_AUTORIZACAO_CREDENCIAMENTO'){
      const {data:cats,error}=await c.from('legalizacao_checklist_catalogo').select('*').eq('tipo_processo','CREDENCIAMENTO').eq('ativo',true).order('ordem',{ascending:true});if(error)throw error;
      for(const r of cats||[])rows.push({acompanhamento_id:id,irregularidade_codigo:irr,fonte_catalogo:'CREDENCIAMENTO',catalogo_origem_id:r.id,codigo_requisito:clean(r.codigo||r.codigo_item),descricao:clean(r.descricao||r.nome||r.titulo)||'Documento de credenciamento',obrigatorio:r.obrigatorio!==false,referencia_normativa:clean(r.referencia_normativa)||'A_VALIDAR',ordem:Number(r.ordem||0),status:'NAO_APRESENTADO',criado_por_id:currentUserId()});
      continue;
    }
    const termos=alvo[irr]||[];const oferta=(ofertas||[]).find(o=>{const s=norm([o.codigo,o.nome,o.titulo,o.descricao,o.etapa,o.modalidade].filter(Boolean).join(' '));return termos.some(t=>s.includes(t));});
    if(!oferta)continue;
    const {data:reqs,error}=await c.from('legalizacao_oferta_requisitos_catalogo').select('*').eq('ativo',true).or(`oferta_catalogo_id.is.null,oferta_catalogo_id.eq.${Number(oferta.id)}`).order('ordem',{ascending:true});if(error)throw error;
    const seen=new Set();for(const r of reqs||[]){const k=String(r.codigo||r.id);if(seen.has(k))continue;seen.add(k);rows.push({acompanhamento_id:id,irregularidade_codigo:irr,fonte_catalogo:'OFERTA',catalogo_origem_id:r.id,codigo_requisito:clean(r.codigo),descricao:clean(r.descricao||r.nome||r.titulo)||'Requisito documental da oferta',obrigatorio:r.obrigatorio!==false,referencia_normativa:clean(r.referencia_normativa)||'A_VALIDAR',ordem:Number(r.ordem||0),status:'NAO_APRESENTADO',criado_por_id:currentUserId()});}
  }
  if(rows.length){const {error}=await c.from('legalizacao_irregularidade_checklist').upsert(rows,{onConflict:'acompanhamento_id,irregularidade_codigo,fonte_catalogo,catalogo_origem_id',ignoreDuplicates:true});if(error)throw error;}
  const {data:lista,error:el}=await c.from('legalizacao_irregularidade_checklist').select('*').eq('acompanhamento_id',id).order('irregularidade_codigo',{ascending:true}).order('ordem',{ascending:true});if(el)throw el;return lista||[];
}
async function atualizarChecklistIrregularidade(itemId,payload={}){
  assertAccess();const c=client(),id=Number(itemId),status=upper(payload.status);if(!['NAO_APRESENTADO','APRESENTADO','EM_ANALISE','CONFORME','NAO_CONFORME','NAO_SE_APLICA'].includes(status))throw new Error('Situação documental inválida.');
  const {data:item,error:ei}=await c.from('legalizacao_irregularidade_checklist').select('*').eq('id',id).single();if(ei)throw ei;let q=c.from('legalizacao_irregularidade_acompanhamentos').select('*').eq('id',item.acompanhamento_id);q=scoped(q);const {data:ac,error:ea}=await q.maybeSingle();if(ea)throw ea;if(!ac)throw new Error('Checklist fora da sua abrangência.');
  const {data,error}=await c.from('legalizacao_irregularidade_checklist').update({status,observacao:clean(payload.observacao),analisado_por_id:currentUserId(),analisado_em:new Date().toISOString(),atualizado_por_id:currentUserId(),updated_at:new Date().toISOString()}).eq('id',id).select('*').single();if(error)throw error;return data;
}
async function registrarSeiRegularizacaoIrregularidade(acompanhamentoId,payload={}){
  assertAccess();const c=client(),id=Number(acompanhamentoId),sei=clean(payload.numero_sei),data=clean(payload.data_sei)||today();if(!sei)throw new Error('Informe o número do Processo SEI.');
  let q=c.from('legalizacao_irregularidade_acompanhamentos').select('*').eq('id',id);q=scoped(q);const {data:ac,error:ea}=await q.maybeSingle();if(ea)throw ea;if(!ac)throw new Error('Acompanhamento não localizado no território.');
  const itens=await garantirChecklistIrregularidade(id);if(!itens.length)throw new Error('O checklist documental ainda não possui requisitos vinculados. Revise a parametrização regulatória.');
  const pend=itens.filter(x=>x.obrigatorio!==false&&!['CONFORME','NAO_SE_APLICA'].includes(upper(x.status)));if(pend.length)throw new Error(`Ainda existem ${pend.length} documento(s) obrigatório(s) sem conformidade. O Processo SEI só pode ser registrado após a documentação completa.`);
  const now=new Date().toISOString();const {error:e1}=await c.from('legalizacao_irregularidade_acompanhamentos').update({numero_sei_regularizacao:sei,data_sei_regularizacao:data,regularizacao_documental_em:now,status:'REGULARIZACAO_EM_ACOMPANHAMENTO',updated_at:now}).eq('id',id);if(e1)throw e1;
  const {error:e2}=await c.from('legalizacao_irregularidade_eventos').insert({acompanhamento_id:id,tipo_evento:'PROCESSO_SEI_REGULARIZACAO',data_evento:data,prazo_limite:ac.prazo_atual,descricao:`Documentação considerada completa. Processo SEI da regularização: ${sei}.`,criado_por_id:currentUserId()});if(e2)throw e2;return true;
}
async function listarAcompanhamentosIrregularidade(){assertAccess();const c=client();let q=c.from('legalizacao_irregularidade_acompanhamentos').select('*,instituicao:legalizacao_instituicoes(id,nome_instituicao,cod_inep,municipio,nte_id)').order('created_at',{ascending:false}).limit(300);q=scoped(q);const {data,error}=await q;if(error)throw error;return data||[];}
async function obterAcompanhamentoIrregularidade(acompanhamentoId){assertAccess();const c=client(),id=Number(acompanhamentoId);let q=c.from('legalizacao_irregularidade_acompanhamentos').select('*,instituicao:legalizacao_instituicoes(id,nome_instituicao,cod_inep,municipio,nte_id)').eq('id',id);q=scoped(q);const {data:ac,error}=await q.maybeSingle();if(error)throw error;if(!ac)throw new Error('Acompanhamento não localizado no território.');const [{data:eventos,error:ee},checklist]=await Promise.all([c.from('legalizacao_irregularidade_eventos').select('*').eq('acompanhamento_id',id).order('data_evento',{ascending:true}).order('created_at',{ascending:true}),garantirChecklistIrregularidade(id)]);if(ee)throw ee;return {...ac,eventos:eventos||[],checklist:checklist||[]};}
async function registrarRegularizacaoIrregularidade(acompanhamentoId,payload={}){assertAccess();const c=client(),id=Number(acompanhamentoId),situacao=upper(payload.situacao),data=clean(payload.data_acao)||today(),obs=clean(payload.observacao);if(!['REGULARIZACAO_INICIADA','REGULARIZADO'].includes(situacao))throw new Error('Situação de regularização inválida.');if(!obs)throw new Error('Registre as providências/evidências da regularização.');let q=c.from('legalizacao_irregularidade_acompanhamentos').select('*').eq('id',id);q=scoped(q);const {data:ac,error:e0}=await q.maybeSingle();if(e0)throw e0;if(!ac)throw new Error('Acompanhamento não localizado no território.');if(['ENCAMINHADO_MP','REGULARIZADO'].includes(upper(ac.status)))throw new Error('Este acompanhamento já está encerrado para novas ações de regularização.');if(!clean(ac.numero_sei_regularizacao))throw new Error('Conclua o checklist documental e registre o Processo SEI da regularização antes de avançar esta situação.');const status=situacao==='REGULARIZADO'?'REGULARIZADO':'REGULARIZACAO_EM_ACOMPANHAMENTO';const upd={status,updated_at:new Date().toISOString()};if(situacao==='REGULARIZADO')upd.prazo_atual=null;const {error:e1}=await c.from('legalizacao_irregularidade_acompanhamentos').update(upd).eq('id',id);if(e1)throw e1;const {error:e2}=await c.from('legalizacao_irregularidade_eventos').insert({acompanhamento_id:id,tipo_evento:situacao,data_evento:data,prazo_limite:situacao==='REGULARIZADO'?null:ac.prazo_atual,descricao:obs,criado_por_id:currentUserId()});if(e2)throw e2;return true;}
async function iniciarAcompanhamentoIrregularidade(instituicaoId,payload={}){assertAccess();const inst=await oneScoped('legalizacao_instituicoes',instituicaoId),c=client();const codInep=String(payload.cod_inep||'').replace(/\D/g,'').trim();if(codInep&&codInep!==String(inst.cod_inep||'').replace(/\D/g,'')){const {error:eCod}=await c.from('legalizacao_instituicoes').update({cod_inep:codInep,updated_at:new Date().toISOString()}).eq('id',inst.id);if(eCod)throw eCod;inst.cod_inep=codInep;try{await c.from('logs_sigee').insert({usuario_id:currentUserId(),acao:'ATUALIZACAO_COD_INEP_INSPECAO',modulo:'LEGALIZACAO',detalhes:`Código INEP/MEC informado/atualizado durante Visita Técnica de Orientação: ${codInep}`});}catch(_){}}const irregs=Array.isArray(payload.irregularidades)?payload.irregularidades.filter(Boolean):[];if(!irregs.length||!clean(payload.ciente_nome)||!clean(payload.ciente_funcao)||!clean(payload.declaracao_ciencia)||!clean(payload.acordo_firmado)||!clean(payload.data_visita)||!clean(payload.prazo_regularizacao)||!Number(payload.prazo_dias))throw new Error('Preencha a visita técnica, irregularidades, ciência do representante, acordo firmado e prazo em dias.');const mapa={AUTORIZACAO_VENCIDA_EF1:'Autorização vencida do Ensino Fundamental I',AUTORIZACAO_VENCIDA_EF2:'Autorização vencida do Ensino Fundamental II',AUTORIZACAO_VENCIDA_EM:'Autorização vencida do Ensino Médio',OFERTA_SEM_AUTORIZACAO_EF1:'Oferta de Ensino Fundamental I sem autorização',OFERTA_SEM_AUTORIZACAO_EF2:'Oferta de Ensino Fundamental II sem autorização',OFERTA_SEM_AUTORIZACAO_EM:'Oferta de Ensino Médio sem autorização',UNIDADE_FILIAL_SEM_AUTORIZACAO_CREDENCIAMENTO:'Unidade de Ensino (filial) sem autorização/credenciamento'};const descricao=irregs.map(x=>mapa[x]||x).join('; ');const row={instituicao_id:inst.id,nte_id:inst.nte_id,etapa_atual:'VISITA_TECNICA_ORIENTACAO',status:'EM_ACOMPANHAMENTO',data_visita:payload.data_visita,prazo_atual:payload.prazo_regularizacao,irregularidade:descricao,irregularidades:irregs,ciente_nome:clean(payload.ciente_nome),ciente_funcao:clean(payload.ciente_funcao),declaracao_ciencia:clean(payload.declaracao_ciencia),acordo_firmado:clean(payload.acordo_firmado),prazo_dias:Number(payload.prazo_dias),responsavel_id:currentUserId()};const {data,error}=await c.from('legalizacao_irregularidade_acompanhamentos').insert(row).select('*').single();if(error)throw error;await c.from('legalizacao_irregularidade_eventos').insert({acompanhamento_id:data.id,tipo_evento:'VISITA_TECNICA_ORIENTACAO',data_evento:payload.data_visita,prazo_limite:payload.prazo_regularizacao,descricao:`${descricao}. Representante: ${clean(payload.ciente_nome)} (${clean(payload.ciente_funcao)}). Acordo: ${clean(payload.acordo_firmado)}`,criado_por_id:currentUserId()});return data;}
async function listarEnquadramentos(){assertAccess();const c=client();let q=c.from('legalizacao_enquadramentos').select('*').order('created_at',{ascending:false}).limit(300);q=scoped(q);const {data,error}=await q;if(error)throw error;return data||[];}
async function iniciarEnquadramento(payload={}){assertAccess();const c=client(),n=nteId();if(!n&&!master())throw new Error('Usuário sem NTE definido.');if(!clean(payload.nome_estabelecimento)||!clean(payload.municipio)||!clean(payload.data_identificacao)||!clean(payload.prazo_adequacao)||!clean(payload.constatacao)||!clean(payload.responsavel_inicial))throw new Error('Preencha os dados mínimos do enquadramento.');const row={nte_id:Number(payload.nte_id||n),nome_estabelecimento:clean(payload.nome_estabelecimento),municipio:clean(payload.municipio),data_identificacao:payload.data_identificacao,prazo_atual:payload.prazo_adequacao,constatacao:clean(payload.constatacao),responsavel_inicial:clean(payload.responsavel_inicial),status:'EM_ENQUADRAMENTO',etapa_atual:'CADASTRO_PRELIMINAR',responsavel_id:currentUserId()};const {data,error}=await c.from('legalizacao_enquadramentos').insert(row).select('*').single();if(error)throw error;await c.from('legalizacao_enquadramento_eventos').insert({enquadramento_id:data.id,tipo_evento:'IDENTIFICACAO',data_evento:payload.data_identificacao,prazo_limite:payload.prazo_adequacao,descricao:clean(payload.constatacao),criado_por_id:currentUserId()});return data;}
async function obterProntuarioPorEscola(escolaId){const inst=await habilitarProntuario(escolaId);return obterProntuario(inst.id);}
async function importarAtosLote(rows=[]){assertAccess();if(!master())throw new Error('A importação de atos é exclusiva do perfil Master.');if(!Array.isArray(rows)||!rows.length)return[];if(rows.length>200)throw new Error('Cada lote pode conter no máximo 200 registros.');const c=client();const {data,error}=await c.from('legalizacao_atos_importacao').insert(rows).select('id,status_match,escola_id');if(error)throw error;return data||[];}
async function listarAtosImportados(status=''){assertAccess();if(!master())throw new Error('A conferência de importações é exclusiva do perfil Master.');const c=client();let q=c.from('legalizacao_atos_importacao').select('id,lote_id,arquivo_origem,linha_origem,nte_numero,municipio,escola_nome,ato,tipo_ato,numero_publicacao,data_publicacao,numero_processo,vigencia_inicio,vigencia_fim,vigencia_origem,status_match,escola_id,created_at').order('id',{ascending:false}).limit(200);if(status)q=q.eq('status_match',upper(status));const {data,error}=await q;if(error)throw error;return data||[];}
async function resumoImportacaoAtos(){assertAccess();if(!master())return null;const c=client(),contar=async status=>{let q=c.from('legalizacao_atos_importacao').select('id',{count:'exact',head:true});if(status)q=q.eq('status_match',status);const {count,error}=await q;if(error)throw error;return Number(count||0);};const [total,identificados,pendentes,ambiguos,confirmados,duplicados]=await Promise.all([contar(),contar('IDENTIFICADO'),contar('PENDENTE_CONFERENCIA'),contar('AMBIGUO'),contar('CONFIRMADO'),contar('DUPLICADO')]);return{total,identificados,pendentes,ambiguos,confirmados,duplicados};}
async function confirmarAtoImportado(importacaoId,escolaId=null){assertAccess();if(!master())throw new Error('A confirmação de atos é exclusiva do perfil Master.');const c=client();const {data:r,error:er}=await c.from('legalizacao_atos_importacao').select('*').eq('id',importacaoId).single();if(er)throw er;if(upper(r.status_match)==='CONFIRMADO')throw new Error('Este ato já foi confirmado.');const eid=Number(escolaId||r.escola_id);if(!eid)throw new Error('Vincule uma escola antes de confirmar o ato.');const inst=await habilitarProntuario(eid);const registro={instituicao_id:inst.id,escola_id:eid,importacao_id:r.id,ato:r.ato,tipo_ato:r.tipo_ato,numero_ato:r.numero_publicacao,data_publicacao:r.data_publicacao,numero_processo:r.numero_processo,vigencia_inicio:r.vigencia_inicio,vigencia_fim:r.vigencia_fim,vigencia_origem:r.vigencia_origem,detalhe:r.detalhe,fonte:`IMPORTACAO:${r.arquivo_origem}`,situacao_registro:'CONFIRMADO',criado_por_id:currentUserId()};const {data,error}=await c.from('legalizacao_atos_legais').upsert(registro,{onConflict:'importacao_id'}).select('*').single();if(error)throw error;const now=new Date().toISOString();const {error:eu}=await c.from('legalizacao_atos_importacao').update({escola_id:eid,status_match:'CONFIRMADO',confirmado_em:now,confirmado_por_id:currentUserId()}).eq('id',r.id);if(eu)throw eu;if(r.endereco_extraido&&!inst.endereco_importado){await c.from('legalizacao_instituicoes').update({endereco_importado:r.endereco_extraido,endereco_importado_fonte:r.arquivo_origem,dados_importados_status:'A_CONFERIR',updated_at:now}).eq('id',inst.id);}return data;}
async function integrarAtosIdentificados(importacaoIds=[]){
  assertAccess();if(!master())throw new Error('A integração automática de atos é exclusiva do perfil Master.');
  const c=client();let registros=[];
  if(Array.isArray(importacaoIds)&&importacaoIds.length){
    const ids=[...new Set(importacaoIds.map(Number).filter(Boolean))];if(!ids.length)return{integrados:0,falhas:0,erros:[]};
    const {data,error}=await c.from('legalizacao_atos_importacao').select('id,status_match,escola_id').in('id',ids);if(error)throw error;registros=(data||[]).filter(x=>upper(x.status_match)==='IDENTIFICADO'&&Number(x.escola_id));
  }else{
    const {data,error}=await c.from('legalizacao_atos_importacao').select('id,status_match,escola_id').eq('status_match','IDENTIFICADO').not('escola_id','is',null).order('id',{ascending:true}).limit(1000);if(error)throw error;registros=data||[];
  }
  let cursor=0,integrados=0;const erros=[];const worker=async()=>{while(cursor<registros.length){const r=registros[cursor++];try{await confirmarAtoImportado(r.id,r.escola_id);integrados++;}catch(e){erros.push({id:r.id,mensagem:e?.message||String(e)});}}};
  await Promise.all(Array.from({length:Math.min(8,registros.length)},worker));
  return{integrados,falhas:erros.length,erros};
}
async function listarAtosInstituicao(instituicaoId){assertAccess();const inst=await oneScoped('legalizacao_instituicoes',instituicaoId),c=client();const {data,error}=await c.from('legalizacao_atos_legais').select('id,ato,tipo_ato,numero_ato,data_publicacao,numero_processo,vigencia_inicio,vigencia_fim,vigencia_origem,detalhe,fonte,situacao_registro,created_at').eq('instituicao_id',inst.id).order('data_publicacao',{ascending:false}).limit(300);if(error)throw error;return data||[];}
window.SIGEE_LEGALIZACAO_SERVICE=Object.freeze({listarInstituicoes,consultarInstituicoes,contarInstituicoes,resumo,listarBasePendenciasRegulatorias,listarNtes,listarInspecoesGerais,listarAcompanhamentosIrregularidade,obterAcompanhamentoIrregularidade,garantirChecklistIrregularidade,atualizarChecklistIrregularidade,registrarSeiRegularizacaoIrregularidade,iniciarAcompanhamentoIrregularidade,registrarAcaoIrregularidade,registrarRegularizacaoIrregularidade,listarEnquadramentos,iniciarEnquadramento,listarHistoricoRegulatorio,listarProcessosRegulatorios,listarAlteracoesCadastrais,iniciarAlteracaoCadastral,listarDescredenciamentosRegulatorios,garantirChecklistDescredenciamento,listarOfertasRegulatorias,listarProcessosOfertaRegulatorios,listarCatalogoOfertas,iniciarProcedimentoOferta,adicionarOfertasCredenciamento,atualizarRequisitoOferta,listarCarimbosRegulatorios,listarAtosHistoricosControle,criarInstituicao,atualizarInstituicao,confirmarCadastroMigrado,habilitarProntuario,obterProntuario,obterProntuarioPorEscola,iniciarCredenciamento,iniciarDescredenciamento,registrarProcessoSeiCredenciamento,atualizarChecklist,emitirDiligencia,retomarAnalise,prepararInspecao,agendarInspecao,atualizarItemInspecao,registrarRealizacaoInspecao,concluirInspecao,concluirAnaliseFinal,registrarPublicacao,concluirCredenciamento,importarAtosLote,listarAtosImportados,resumoImportacaoAtos,confirmarAtoImportado,integrarAtosIdentificados,listarAtosInstituicao,ehMaster:master,nteId});
})(window);
