/* SIGEE Enterprise RC6.5.0 — Central de Relatórios */
(function(){
'use strict';
if(window.__SIGEE_REPORTS_650__) return; window.__SIGEE_REPORTS_650__=true;
const txt=v=>v==null?'':String(v).trim(), norm=v=>txt(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase(), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const R=()=>window.SIGEE_REGRAS_OPERACIONAIS;
const tipos=[
 ['operacional','📊','Relatório Operacional'],['sla','⏱️','Relatório de SLA'],['territorial','🗺️','Relatório Territorial'],['pendencias','⏸️','Relatório de Pendências'],['produtividade','👥','Relatório de Produtividade'],['executivo','📈','Relatório Executivo']
];
let state={payload:null,tipo:null};
function finalizado(p){const e=norm(R().etapa(p));return e.includes('RETIR')||e.includes('INDEFER')||e.includes('DEFERIDO');}
function data(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d;}
function dias(v){const d=data(v);return d?Math.max(0,Math.floor((Date.now()-d)/86400000)):0;}
function limite(e){const n=norm(e);if(n.includes('DESARQ'))return 30;if(n.includes('ANAL'))return 7;if(n.includes('DIGIT'))return 15;if(n.includes('CONFER'))return 10;if(n.includes('ASSIN'))return 7;if(n.includes('PENDEN'))return null;return null;}
function atraso(p){if(finalizado(p)||R().pendenciaAluno(p))return false;const l=limite(R().etapa(p));return l!=null&&dias(p.data_etapa_atual||p.data_etapa||p.created_at)>l;}
function responsavel(p){return txt(p.tecnico_atribuido||p.tecnico_responsavel||p.responsavel_etapa||p.analista||p.digitador||p.conferente||p.responsavel||p.usuario_lancamento||p.criado_por_nome);}
function dados(){const ps=state.payload.processos,ativos=ps.filter(p=>!finalizado(p)),externas=ativos.filter(R().pendenciaAluno),operacionais=ativos.filter(p=>!R().pendenciaAluno(p)),atrasados=operacionais.filter(atraso);return {ps,ativos,externas,operacionais,atrasados};}
function main(){return document.querySelector('#sistema-dashboard main');}
function esconder(){main()?.querySelectorAll(':scope > section').forEach(s=>s.classList.add('hidden'));}
function host(tipo){let s=document.getElementById('aba-relatorio-'+tipo);if(!s){s=document.createElement('section');s.id='aba-relatorio-'+tipo;s.className='hidden sig-rel-page';main()?.appendChild(s);}return s;}
function abrir(tipo,forcar=false){state.tipo=tipo;esconder();const h=host(tipo);h.classList.remove('hidden');h.innerHTML='<div class="sig-rel-loading">Consolidando dados do relatório...</div>';window.SIGEE_REPORTS_DATA.carregar(forcar).then(p=>{state.payload=p;render(h,tipo);}).catch(e=>h.innerHTML='<div class="sig-rel-error"><h2>Não foi possível carregar o relatório</h2><p>'+esc(e.message)+'</p><button data-retry>Tentar novamente</button></div>');marcarMenu(tipo);}
function marcarMenu(tipo){document.querySelectorAll('[data-report-menu]').forEach(b=>b.classList.toggle('active',b.dataset.reportMenu===tipo));}
function card(t,v,s){return '<article><span>'+esc(t)+'</span><strong>'+esc(v)+'</strong><small>'+esc(s)+'</small></article>';}
function tabela(arr){return '<div class="sig-rel-table"><table><thead><tr><th>Processo</th><th>Aluno / Escola</th><th>NTE</th><th>Etapa</th><th>Responsável</th></tr></thead><tbody>'+arr.map(p=>'<tr><td>'+esc(p.codigo_sigee||p.id)+'</td><td><b>'+esc(p.aluno_nome||'')+'</b><small>'+esc(p.escola_nome||'')+'</small></td><td>'+esc(window.SIGEE_REPORTS_DATA.nte(p.nte||p.nte_id))+'</td><td>'+esc(R().etapa(p))+'</td><td>'+esc(responsavel(p)||'Aguardando atribuição')+'</td></tr>').join('')+'</tbody></table></div>';}
function header(tipo,titulo,desc){return '<header class="sig-rel-hero"><div><small>CENTRAL DE RELATÓRIOS</small><h1>'+esc(titulo)+'</h1><p>'+esc(desc)+'</p></div><div><span>'+esc(state.payload.contexto.global?'Estado da Bahia':state.payload.contexto.nte)+'</span><button data-refresh>↻ Atualizar</button></div></header>';}
function render(h,tipo){const d=dados();let body='';
 if(tipo==='operacional'){const etapas={};d.operacionais.forEach(p=>{const e=R().etapa(p);etapas[e]=(etapas[e]||0)+1;});body='<section class="sig-rel-cards">'+card('Ativos operacionais',d.operacionais.length,'Exclui espera externa')+card('Em atraso',d.atrasados.length,'Com prazo controlado')+card('Pendências externas',d.externas.length,'Sem prazo estimado')+card('Sem responsável',d.operacionais.filter(p=>!responsavel(p)).length,'Aguardando atribuição')+'</section><section class="sig-rel-panel"><h2>Distribuição operacional por etapa</h2><div class="sig-rel-bars">'+Object.entries(etapas).sort((a,b)=>b[1]-a[1]).map(([e,n])=>'<div><span>'+esc(e)+'</span><b>'+n+'</b></div>').join('')+'</div></section>'+tabela(d.atrasados.slice(0,300));}
 if(tipo==='sla'){const sla=d.operacionais.length?Math.round((d.operacionais.length-d.atrasados.length)*100/d.operacionais.length):0;body='<section class="sig-rel-cards">'+card('SLA operacional',sla+'%','Somente etapas com prazo')+card('Base com SLA',d.operacionais.filter(p=>limite(R().etapa(p))!=null).length,'Processos elegíveis')+card('Vencidos',d.atrasados.length,'Fora do prazo')+card('Espera externa',d.externas.length,'Fora do SLA')+'</section><section class="sig-rel-note"><b>Regra aplicada:</b> Pendência do Aluno não possui prazo estimado e não entra no cálculo do SLA.</section>'+tabela(d.atrasados);}
 if(tipo==='territorial'){const map=new Map();d.operacionais.forEach(p=>{const n=window.SIGEE_REPORTS_DATA.nte(p.nte||p.nte_id);if(!map.has(n))map.set(n,[]);map.get(n).push(p);});body='<section class="sig-rel-territory">'+[...map].map(([n,arr])=>'<article><h3>'+esc(n)+'</h3><strong>'+arr.length+'</strong><span>ativos operacionais</span><small>'+arr.filter(atraso).length+' atrasados · '+arr.filter(p=>!responsavel(p)).length+' sem responsável</small></article>').join('')+'</section>';}
 if(tipo==='pendencias'){const inst=d.ativos.filter(R().pendenciaInstitucional);body='<section class="sig-rel-cards">'+card('Pendências externas',d.externas.length,'Aluno/interessado')+card('Pendências institucionais',inst.length,'Responsabilidade interna')+card('Externas no SLA',0,'Não contabilizadas')+card('Institucionais monitoradas',inst.length,'Acompanhamento operacional')+'</section><section class="sig-rel-tabs"><h2>Pendência do Aluno — espera externa</h2><p>Sem prazo estimado, sem alerta de atraso e fora do ranking de criticidade.</p></section>'+tabela(d.externas);}
 if(tipo==='produtividade'){const map=new Map();d.operacionais.forEach(p=>{const r=responsavel(p)||'Aguardando atribuição';if(!map.has(r))map.set(r,[]);map.get(r).push(p);});body='<section class="sig-rel-team">'+[...map].sort((a,b)=>b[1].length-a[1].length).map(([r,arr])=>'<article><h3>'+esc(r)+'</h3><strong>'+arr.length+'</strong><span>processos ativos</span><small>'+arr.filter(atraso).length+' em atraso</small></article>').join('')+'</section><section class="sig-rel-note">Indicadores destinados ao equilíbrio de carga, apoio e treinamento, sem finalidade punitiva.</section>';}
 if(tipo==='executivo'){body='<section class="sig-rel-cards">'+card('Processos ativos',d.ativos.length,'Total em tramitação')+card('Operação controlável',d.operacionais.length,'Depende da equipe')+card('Espera externa',d.externas.length,'Depende do interessado')+card('Em atraso',d.atrasados.length,'Somente operação controlável')+'</section><section class="sig-rel-exec"><h2>Leitura executiva</h2><p>Existem <b>'+d.operacionais.length+'</b> processos sob gestão direta da operação e <b>'+d.externas.length+'</b> aguardando resposta externa. O total em atraso é <b>'+d.atrasados.length+'</b>, sem contabilizar Pendência do Aluno.</p></section>';}
 const meta=tipos.find(x=>x[0]===tipo);h.innerHTML=header(tipo,meta[2],descricao(tipo))+body;h.querySelector('[data-refresh]').onclick=()=>abrir(tipo,true);h.querySelector('[data-retry]')?.addEventListener('click',()=>abrir(tipo,true));}
function descricao(t){return {operacional:'Visão do fluxo, atrasos e capacidade operacional.',sla:'Acompanhamento de prazos das etapas controladas pela equipe.',territorial:'Distribuição da operação e dos atrasos por NTE.',pendencias:'Separação entre pendência externa e institucional.',produtividade:'Carga e acompanhamento das equipes sem finalidade punitiva.',executivo:'Síntese estratégica para apoio à decisão.'}[t];}
function instalarMenu(){const nav=document.getElementById('sigee-menu-dinamico');if(!nav||document.getElementById('menu-relatorios-rc650'))return;const wrap=document.createElement('div');wrap.id='menu-relatorios-rc650';wrap.className='sig-rel-menu';wrap.innerHTML='<button class="sig-rel-menu-title" type="button">📑 Relatórios <span>▾</span></button><div>'+tipos.map(x=>'<button type="button" data-report-menu="'+x[0]+'">'+x[1]+' '+x[2]+'</button>').join('')+'</div>';nav.appendChild(wrap);wrap.querySelector('.sig-rel-menu-title').onclick=()=>wrap.classList.toggle('open');wrap.querySelectorAll('[data-report-menu]').forEach(b=>b.onclick=()=>abrir(b.dataset.reportMenu));}
function init(){instalarMenu();tipos.forEach(x=>host(x[0]));}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
window.SIGEE_RELATORIOS={abrir,atualizar:()=>state.tipo&&abrir(state.tipo,true),versao:'RC6.5.0'};
console.info('[SIGEE RC6.5.0] Central de Relatórios pronta.');
})();
