/** SIGEE Enterprise — GT-06 Mapa Vetorial / Sala de Situação Territorial. */
(function(window,document){
'use strict';
if(window.SIGEE_TERRITORIAL_MAPA) return;
const POS={1:{x:42.207,y:32.185},2:{x:31.032,y:29.948},3:{x:54.842,y:51.612},4:{x:74.959,y:27.990},5:{x:81.878,y:82.786},6:{x:80.283,y:57.560},7:{x:73.939,y:98.502},8:{x:65.930,y:77.029},9:{x:65.119,y:55.013},10:{x:54.377,y:8.797},11:{x:13.918,y:34.915},12:{x:41.397,y:51.612},13:{x:48.750,y:60.999},14:{x:64.335,y:41.989},15:{x:74.465,y:42.534},16:{x:59.360,y:25.549},17:{x:89.855,y:16.650},18:{x:91.811,y:29.403},19:{x:85.069,y:41.989},20:{x:61.609,y:69.447},21:{x:86.665,y:54.468},22:{x:65.930,y:63.750},23:{x:10.066,y:57.015},24:{x:84.675,y:6.296},25:{x:63.205,y:17.467},26:{x:91.106,y:53.923},27:{x:80.926,y:89.293}};
const LABEL={CONCLUIDA:'Concluída',EM_REALIZACAO:'Em realização',AGENDADA:'Agendada',PENDENTE:'Pendente',EXCELENTE:'Excelente',BOM:'Bom',ATENCAO:'Atenção',ALERTA:'Alerta',CRITICO:'Crítico',SEM_AMOSTRA:'Sem amostra',PRIORITARIA:'Prioritária',ALTA:'Alta',MODERADA:'Moderada',BAIXA:'Baixa',SEM_EVIDENCIA:'Sem evidência'};
let dados=[];
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function nota(v){return v==null?'—':`${String(Math.round(Number(v)*10)/10).replace('.',',')}%`;}
function classe(layer,x){if(layer==='FORMACAO')return `form-${x.statusFormacao.toLowerCase()}`;if(layer==='PRIORIDADE')return `pri-${String(x.prioridadeClasse||'sem_evidencia').toLowerCase()}`;if(layer==='DESEMPENHO')return `des-${String(x.classeDesempenho||'sem_amostra').toLowerCase()}`;if(layer==='SATISFACAO'){if(x.satisfacao==null)return'neutral';return x.satisfacao>=90?'des-excelente':x.satisfacao>=80?'des-bom':x.satisfacao>=70?'des-atencao':x.satisfacao>=50?'des-alerta':'des-critico';}if(layer==='MONITORIA'){if(x.notaTecnica==null)return'neutral';return x.notaTecnica>=90?'des-excelente':x.notaTecnica>=80?'des-bom':x.notaTecnica>=70?'des-atencao':x.notaTecnica>=50?'des-alerta':'des-critico';}return'neutral';}
function valor(layer,x){if(layer==='FORMACAO')return LABEL[x.statusFormacao]||x.statusFormacao;if(layer==='PRIORIDADE')return x.fase==='POS_FORMACAO'?'Já formada':`${LABEL[x.prioridadeClasse]||'—'}${x.prioridadeNota!=null?` • ${nota(x.prioridadeNota)}`:''}`;if(layer==='DESEMPENHO')return x.fase==='PRE_FORMACAO'?'Pré-formação':`${LABEL[x.classeDesempenho]||'—'} • ${nota(x.indiceConsolidado)}`;if(layer==='SATISFACAO')return `${nota(x.satisfacao)} • ${x.amostraSatisfacao} resposta(s)`;if(layer==='MONITORIA')return `${nota(x.notaTecnica)} • ${x.amostraTecnica} avaliação(ões)`;if(layer==='PRODUCAO')return `${new Intl.NumberFormat('pt-BR').format(x.producao)} processo(s)`;if(layer==='VISITAS')return `${x.visitas} visita(s) • ${x.reunioes} reunião(ões)`;return'—';}
function legenda(layer){const l={FORMACAO:[['form-concluida','Concluída','Formação realizada'],['form-em_realizacao','Em realização','Atividade em andamento'],['form-agendada','Agendada','Formação programada'],['form-pendente','Pendente','Sem formação concluída']],PRIORIDADE:[['pri-prioritaria','Prioritária','Prioridade máxima'],['pri-alta','Alta','Intervenção recomendada'],['pri-moderada','Moderada','Acompanhamento'],['pri-baixa','Baixa','Baixa prioridade'],['neutral','Sem evidência','Sem base suficiente']],DESEMPENHO:[['des-excelente','Excelente','90% ou mais'],['des-bom','Bom','80% a 89%'],['des-atencao','Atenção','70% a 79%'],['des-alerta','Alerta','50% a 69%'],['des-critico','Crítico','Abaixo de 50%'],['neutral','Não avaliado','Sem amostra']],SATISFACAO:[['des-excelente','Excelente','90% ou mais'],['des-bom','Bom','80% a 89%'],['des-atencao','Atenção','70% a 79%'],['des-alerta','Alerta','50% a 69%'],['des-critico','Crítico','Abaixo de 50%'],['neutral','Não avaliado','Sem respostas']],MONITORIA:[['des-excelente','Excelente','90% ou mais'],['des-bom','Bom','80% a 89%'],['des-atencao','Atenção','70% a 79%'],['des-alerta','Alerta','50% a 69%'],['des-critico','Crítico','Abaixo de 50%'],['neutral','Não avaliado','Sem amostra']],PRODUCAO:[['neutral','Produção','Valor no painel territorial']],VISITAS:[['neutral','Atuação institucional','Visitas e reuniões realizadas']]};return `<div class="gt-map-legend">${(l[layer]||[]).map(([c,t,d])=>`<span><i class="${c}"></i><b>${t}</b><small>${d||''}</small></span>`).join('')}</div>`;}
function detalhe(x,layer){
  const classeAtual=layer==='DESEMPENHO'?(LABEL[x.classeDesempenho]||'Sem dados'):(layer==='FORMACAO'?(LABEL[x.statusFormacao]||'Sem dados'):valor(layer,x));
  const badgeClass=classe(layer,x);
  return `<div class="gt-map-detail gt-map-detail-pro">
    <div class="gt-map-detail-head"><div><span>${esc(x.codigo)}</span><h3>${esc(x.sede)}</h3><small>${x.municipios} município(s) • ${x.fase==='POS_FORMACAO'?'Pós-formação':'Pré-formação'}</small></div><b class="gt-map-status-badge ${badgeClass}">${esc(classeAtual)}</b></div>
    <div class="gt-map-detail-kpis gt-map-detail-grid">
      <span class="gt-map-kpi-destaque"><small>Índice territorial</small><b>${nota(x.indiceConsolidado)}</b><em>${x.fase==='POS_FORMACAO'?(LABEL[x.classeDesempenho]||'Sem amostra'):'Pré-formação'}</em></span>
      <span><small>Monitoria técnica</small><b>${nota(x.notaTecnica)}</b><em>${x.amostraTecnica} avaliação(ões)</em></span>
      <span><small>Formação</small><b>${LABEL[x.statusFormacao]||x.statusFormacao}</b><em>${x.fase==='POS_FORMACAO'?'Marco pós-formação':'Acompanhamento territorial'}</em></span>
      <span><small>Satisfação</small><b>${nota(x.satisfacao)}</b><em>${x.amostraSatisfacao} resposta(s)</em></span>
      <span><small>Ocorrências</small><b>${x.negativas}</b><em>Negativas</em></span>
      <span><small>Constatações positivas</small><b>${x.positivas}</b><em>Registros</em></span>
      <span><small>Visitas / Reuniões</small><b>${x.visitas} / ${x.reunioes}</b><em>Realizadas</em></span>
      <span><small>Produção</small><b>${new Intl.NumberFormat('pt-BR').format(x.producao)}</b><em>Processos</em></span>
    </div>
    <button type="button" data-dossie="${x.numero}" class="gt-map-dossie-btn">▣&nbsp; Abrir dossiê territorial <span>›</span></button>
    <button type="button" data-dossie="${x.numero}" class="gt-map-secondary-btn">Ver todas as informações ↗</button>
  </div>`;
}
function legendaNtes(){return `<div class="gt-map-nte-key"><strong>Núcleos Territoriais de Educação <small>(Nº de municípios)</small></strong><div>${dados.map(x=>`<span>${String(x.numero).padStart(2,'0')}. ${esc(x.sede)} (${String(x.municipios).padStart(2,'0')})</span>`).join('')}</div></div>`;}
function layerTabs(layer){const itens=[['FORMACAO','⌂','Cobertura de Formação'],['PRIORIDADE','☆','Prioridade p/ Formação'],['DESEMPENHO','◉','Desempenho Pós-formação'],['MONITORIA','☷','Monitoria Técnica'],['SATISFACAO','☺','Pesquisa de Satisfação'],['PRODUCAO','▥','Produção'],['VISITAS','♙','Visitas / Reuniões']];return `<div class="gt-map-layer-tabs">${itens.map(([v,i,t])=>`<button type="button" data-layer-tab="${v}" class="${v===layer?'ativo':''}"><i>${i}</i>${t}</button>`).join('')}</div>`;}
function renderMapa(root,layer,selecionado){const maxProd=Math.max(1,...dados.map(x=>x.producao));const markers=dados.map(x=>{const p=POS[x.numero]||{x:50,y:50},size=layer==='PRODUCAO'?Math.max(40,Math.min(54,40+(x.producao/maxProd)*14)):42;return `<button type="button" class="gt-map-marker ${classe(layer,x)} ${selecionado===x.numero?'selecionado':''}" data-nte="${x.numero}" style="left:${p.x}%;top:${p.y}%;--gt-marker-size:${size}px" title="${esc(x.codigo+' — '+x.sede+': '+valor(layer,x))}"><span>${x.numero}</span></button>`;}).join('');root.querySelector('#gt-map-canvas').innerHTML=`<div class="gt-map-stage"><img src="assets/gt-mapa-nte.svg?v=GT-06.1.5" alt="Mapa vetorial institucional dos Núcleos Territoriais de Educação da Bahia"><div class="gt-map-markers">${markers}</div>${legendaNtes()}</div>`;root.querySelector('#gt-map-legenda').innerHTML=legenda(layer);const tabs=root.querySelector('#gt-map-layer-tabs');if(tabs){tabs.innerHTML=layerTabs(layer);tabs.querySelectorAll('[data-layer-tab]').forEach(b=>b.addEventListener('click',()=>{root.querySelector('#gt-map-layer').value=b.dataset.layerTab;root.querySelector('#gt-map-layer').dispatchEvent(new Event('change'));}));}root.querySelectorAll('[data-nte]').forEach(b=>b.addEventListener('click',()=>selecionar(root,Number(b.dataset.nte))));}
function selecionar(root,n){const x=dados.find(d=>d.numero===n);if(!x)return;root.dataset.selecionado=n;const layer=root.querySelector('#gt-map-layer').value;renderMapa(root,layer,n);root.querySelector('#gt-map-detalhe').innerHTML=detalhe(x,layer);root.querySelectorAll('#gt-map-detalhe [data-dossie]').forEach(b=>b.addEventListener('click',()=>window.SIGEE_TERRITORIAL_FORMACOES?.abrirDossie?.(n)));root.querySelector('#gt-map-nte').value=String(n);}
function resumo(){const concl=dados.filter(x=>x.statusFormacao==='CONCLUIDA').length,ag=dados.filter(x=>['AGENDADA','EM_REALIZACAO'].includes(x.statusFormacao)).length,pend=dados.filter(x=>x.statusFormacao==='PENDENTE').length,crit=dados.filter(x=>x.classeDesempenho==='CRITICO').length,prio=dados.filter(x=>x.prioridadeClasse==='PRIORITARIA').length;return `<div class="gt-kpis gt-map-kpis"><article><span>Formação concluída</span><strong>${concl}</strong><small>pós-formação</small></article><article><span>Agendada / em realização</span><strong>${ag}</strong><small>próximas intervenções</small></article><article><span>Pendentes</span><strong>${pend}</strong><small>sem formação concluída</small></article><article><span>Prioridade máxima</span><strong>${prio}</strong><small>pré-formação</small></article><article><span>Críticos</span><strong>${crit}</strong><small>pós-formação</small></article></div>`;}
async function carregar(root){root=root||document.querySelector('#gt-conteudo');if(!root)return;root.innerHTML='<div class="gt-empty">Carregando Sala de Situação Territorial...</div>';try{dados=await window.SIGEE_TERRITORIAL_INDICADORES_SERVICE.carregar();root.innerHTML=`<article class="gt-panel gt-panel-full gt-map-shell"><header><div><span>SALA DE SITUAÇÃO • GT-06</span><h2>Mapa vetorial dos 27 NTEs</h2><p>Visualização territorial integrada a formação, prioridade, desempenho, monitoria, satisfação, produção e atuação institucional.</p></div><span class="gt-status">Base cartográfica institucional</span></header><div class="gt-map-toolbar"><label>Camada<select id="gt-map-layer"><option value="FORMACAO">Cobertura de formação</option><option value="PRIORIDADE">Prioridade para formação</option><option value="DESEMPENHO">Desempenho pós-formação</option><option value="MONITORIA">Monitoria técnica</option><option value="SATISFACAO">Pesquisa de satisfação</option><option value="PRODUCAO">Produção</option><option value="VISITAS">Visitas e reuniões</option></select></label><label>NTE<select id="gt-map-nte"><option value="">Selecione</option>${dados.map(x=>`<option value="${x.numero}">${x.codigo} — ${esc(x.sede)}</option>`).join('')}</select></label><small>Selecione um marcador para abrir o resumo e o dossiê territorial.</small></div><div id="gt-map-legenda"></div><div class="gt-map-layout"><div id="gt-map-canvas" class="gt-map-canvas"></div><aside id="gt-map-detalhe"><div class="gt-empty">Selecione um NTE no mapa.</div></aside></div><div id="gt-map-layer-tabs"></div><div class="gt-map-source">Fonte cartográfica: mapa institucional dos Núcleos Territoriais de Educação da Bahia (SEI/DIGEO/CARTGEO). Indicadores: dados internos do SIGEE.</div></article>`;renderMapa(root,'FORMACAO',null);root.querySelector('#gt-map-layer').addEventListener('change',()=>{const n=Number(root.dataset.selecionado)||null;renderMapa(root,root.querySelector('#gt-map-layer').value,n);if(n)selecionar(root,n);});root.querySelector('#gt-map-nte').addEventListener('change',e=>{if(e.target.value)selecionar(root,Number(e.target.value));});}catch(e){root.innerHTML=`<div class="gt-agenda-alert"><strong>Não foi possível carregar o mapa territorial</strong><span>${esc(e.message||e)}</span></div>`;}}
window.SIGEE_TERRITORIAL_MAPA=Object.freeze({carregar,versao:'GT-06.1.5'});
})(window,document);
