/** SIGEE RC12.0.3 — Serviço de Solicitação de Apoio Territorial. */
(function(window){
'use strict';
if(window.SIGEE_TERRITORIAL_APOIO_SERVICE?.versao==='RC12.0.3')return;
const T='gt_solicitacoes_apoio', H='gt_solicitacoes_apoio_historico';
function cliente(){try{return window.SIGEE_SUPABASE?.criarCliente?.()||window.SIGEE_SUPABASE_CLIENT||window.supabaseClient||null;}catch(_){return null;}}
function usuario(){return window.SIGEE_SESSION?.getUser?.()||window.usuarioLogado||window.usuarioAtual||null;}
function perfil(){return window.SIGEE_PERFIS?.normalizar?.(usuario()?.perfil)||String(usuario()?.perfil||'');}
function master(){return perfil()==='Master';}
function territorial(){return master()||window.SIGEE_ESCOPO?.ehTerritorial?.(usuario())===true;}
function nteUsuario(){return window.SIGEE_ESCOPO?.nteUsuario?.(usuario())||usuario()?.nte||null;}
function numeroNte(v){return window.SIGEE_TERRITORIAL_DATA?.numeroNte?.(v)||window.SIGEE_ESCOPO?.numeroNte?.(v)||Number(String(v||'').match(/\d+/)?.[0])||null;}
function exigir(){if(!territorial())throw new Error('Solicitação de Apoio disponível somente para Gestão Master e usuários territoriais.');const c=cliente();if(!c)throw new Error('Cliente Supabase indisponível.');return c;}
function txt(v){return String(v??'').trim();}
function autor(){const u=usuario()||{};return{usuario_id:u.id||null,usuario_nome:u.nome||u.name||'',usuario_email:String(u.email||'').toLowerCase()||null,usuario_perfil:perfil()};}
function fechada(s){return ['CONCLUIDA','CANCELADA'].includes(String(s||'').toUpperCase());}
async function historico(id,status,observacao){const c=exigir(),a=autor();const {error}=await c.from(H).insert({solicitacao_id:Number(id),status:String(status||'').toUpperCase(),observacao:txt(observacao)||null,...a});if(error)console.warn('[Apoio Territorial] histórico:',error);}
async function registrarHistoricoProcesso(reg,acao,observacao){const c=exigir(),a=autor();const payload={processo_id:Number(reg.processo_id),codigo_sigee:reg.codigo_sigee||'',etapa:reg.etapa_processo||'Processo em andamento',acao,observacao:txt(observacao)||null,usuario_nome:a.usuario_nome,usuario_email:a.usuario_email,usuario_perfil:a.usuario_perfil,nte:`NTE-${String(reg.nte_numero).padStart(2,'0')}`,dados:{solicitacao_apoio_id:reg.id,tipo_solicitacao:reg.tipo_solicitacao,prioridade:reg.prioridade},created_at:new Date().toISOString()};const {error}=await c.from('historico_processos').insert(payload);if(error)console.warn('[Apoio Territorial] histórico do processo:',error);}
async function listar(filtros={}){const c=exigir();let q=c.from(T).select('*').order('created_at',{ascending:false});const n=master()?numeroNte(filtros.nte_numero):numeroNte(nteUsuario());if(n)q=q.eq('nte_numero',n);if(filtros.status)q=q.eq('status',String(filtros.status).toUpperCase());if(filtros.processo_id)q=q.eq('processo_id',Number(filtros.processo_id));const {data,error}=await q;if(error)throw error;return data||[];}
async function listarProcessosAtivos(){if(master())return[];const c=exigir(),n=numeroNte(nteUsuario());if(!n)throw new Error('Seu usuário não possui NTE válido vinculado.');let q=c.from('processos').select('*').order('updated_at',{ascending:false}).limit(700);if(window.SIGEE_ESCOPO?.aplicarQueryProcessos)q=window.SIGEE_ESCOPO.aplicarQueryProcessos(q,usuario());const {data,error}=await q;if(error)throw error;return (data||[]).filter(p=>!p.finalizado_em&&!['DEFERIDO','RETIRADO','INDEFERIDO','FINALIZADO','CONCLUIDO'].some(x=>String(p.etapa_atual||p.etapa||'').toUpperCase().includes(x))).filter(p=>{const pn=numeroNte(p.nte||p.nte_nome);return !n||!pn||pn===n;});}
async function criar(payload={}){if(master())throw new Error('A solicitação de apoio deve ser aberta pelo território.');const c=exigir(),a=autor(),n=numeroNte(nteUsuario()),processoId=Number(payload.processo_id);if(!n)throw new Error('Seu usuário não possui NTE válido vinculado.');if(!processoId)throw new Error('Selecione o processo que necessita de apoio.');if(!txt(payload.assunto))throw new Error('Informe o assunto da solicitação.');if(!txt(payload.descricao))throw new Error('Descreva a dificuldade ou necessidade de apoio.');const proc=(await listarProcessosAtivos()).find(x=>Number(x.id)===processoId);if(!proc)throw new Error('O processo selecionado não está disponível entre os processos em andamento do seu NTE.');const reg={processo_id:processoId,codigo_sigee:txt(proc.codigo_sigee)||null,nte_numero:n,etapa_processo:txt(proc.etapa_atual||proc.etapa)||null,tipo_solicitacao:String(payload.tipo_solicitacao||'ORIENTACAO_TECNICA').toUpperCase(),prioridade:String(payload.prioridade||'NORMAL').toUpperCase(),assunto:txt(payload.assunto),descricao:txt(payload.descricao),status:'SOLICITADA',solicitante_id:a.usuario_id,solicitante_nome:a.usuario_nome,solicitante_email:a.usuario_email,solicitante_perfil:a.usuario_perfil};const {data,error}=await c.from(T).insert(reg).select('*').single();if(error)throw error;await historico(data.id,'SOLICITADA',data.descricao);await registrarHistoricoProcesso(data,'Apoio solicitado pelo território',`${data.assunto}. ${data.descricao}`);document.dispatchEvent(new CustomEvent('sigee:gt-apoio-atualizado'));return data;}
async function assumir(id){if(!master())throw new Error('Somente a Gestão Master pode assumir uma solicitação de apoio.');const c=exigir(),agora=new Date().toISOString();const {data,error}=await c.from(T).update({status:'EM_ANALISE',updated_at:agora}).eq('id',Number(id)).select('*').single();if(error)throw error;await historico(id,'EM_ANALISE','Solicitação em análise pela Gestão Master.');document.dispatchEvent(new CustomEvent('sigee:gt-apoio-atualizado'));return data;}
async function responder(id,resposta){if(!master())throw new Error('Somente a Gestão Master registra orientação/resposta.');if(!txt(resposta))throw new Error('Registre a orientação ou apoio fornecido.');const c=exigir(),a=autor(),agora=new Date().toISOString();const {data,error}=await c.from(T).update({status:'ORIENTADA',resposta:txt(resposta),respondido_por_id:a.usuario_id,respondido_por_nome:a.usuario_nome,respondido_em:agora,updated_at:agora}).eq('id',Number(id)).select('*').single();if(error)throw error;await historico(id,'ORIENTADA',resposta);await registrarHistoricoProcesso(data,'Orientação da Gestão ao território',resposta);document.dispatchEvent(new CustomEvent('sigee:gt-apoio-atualizado'));return data;}
async function concluir(id){if(master())throw new Error('A ciência e conclusão devem ser registradas pelo território.');const c=exigir(),a=autor(),agora=new Date().toISOString(),n=numeroNte(nteUsuario());const {data:atual,error:ea}=await c.from(T).select('id,nte_numero,status').eq('id',Number(id)).single();if(ea)throw ea;if(Number(atual.nte_numero)!==Number(n))throw new Error('Solicitação fora do seu NTE.');const {data,error}=await c.from(T).update({status:'CONCLUIDA',ciencia_em:agora,concluido_em:agora,concluido_por_id:a.usuario_id,concluido_por_nome:a.usuario_nome,concluido_por_email:a.usuario_email,updated_at:agora}).eq('id',Number(id)).eq('status','ORIENTADA').select('*').single();if(error)throw error;await historico(id,'CONCLUIDA',`Ciência registrada e solicitação concluída por ${a.usuario_nome||a.usuario_email||'técnico do NTE'}.`);await registrarHistoricoProcesso(data,'Ciência da orientação registrada pelo território',`Solicitação de apoio concluída por ${a.usuario_nome||a.usuario_email||'técnico do NTE'}.`);document.dispatchEvent(new CustomEvent('sigee:gt-apoio-atualizado'));return data;}
async function cancelar(id,motivo=''){if(master())throw new Error('O cancelamento deve ser realizado pelo técnico solicitante.');const c=exigir(),a=autor(),agora=new Date().toISOString(),n=numeroNte(nteUsuario());const {data:atual,error:ea}=await c.from(T).select('id,solicitante_id,solicitante_email,nte_numero,status').eq('id',Number(id)).single();if(ea)throw ea;if(Number(atual.nte_numero)!==Number(n))throw new Error('Solicitação fora do seu NTE.');const mesmoId=a.usuario_id&&atual.solicitante_id&&String(a.usuario_id)===String(atual.solicitante_id),mesmoEmail=a.usuario_email&&atual.solicitante_email&&String(a.usuario_email).toLowerCase()===String(atual.solicitante_email).toLowerCase();if(!mesmoId&&!mesmoEmail)throw new Error('Somente o técnico que abriu a solicitação pode cancelá-la.');const {data,error}=await c.from(T).update({status:'CANCELADA',updated_at:agora}).eq('id',Number(id)).in('status',['SOLICITADA','EM_ANALISE']).select('*').single();if(error)throw error;await historico(id,'CANCELADA',txt(motivo)||'Solicitação cancelada pelo técnico solicitante.');document.dispatchEvent(new CustomEvent('sigee:gt-apoio-atualizado'));return data;}
async function contarPendentes(){const c=exigir();let q=c.from(T).select('id',{count:'exact',head:true});if(master())q=q.in('status',['SOLICITADA','EM_ANALISE']);else{const n=numeroNte(nteUsuario());q=q.eq('status','ORIENTADA');if(n)q=q.eq('nte_numero',n);}const {count,error}=await q;if(error)throw error;return Number(count||0);}
window.SIGEE_TERRITORIAL_APOIO_SERVICE=Object.freeze({listar,listarProcessosAtivos,criar,assumir,responder,concluir,cancelar,contarPendentes,master,territorial,fechada,versao:'RC12.0.3'});
})(window);
