/** SIGEE Enterprise — GT-05.2 Pesquisa de Satisfação. */
(function(window,document){
'use strict';
if(window.SIGEE_TERRITORIAL_PESQUISA_SERVICE) return;
const T='gt_pesquisa_satisfacao';
function cliente(){try{return window.SIGEE_SUPABASE?.criarCliente?.()||window.SIGEE_SUPABASE_CLIENT||window.supabaseClient||null;}catch(_){return null;}}
function usuario(){return window.SIGEE_SESSION?.getUser?.()||window.usuarioLogado||null;}
function perfil(){return window.SIGEE_PERFIS?.normalizar?.(usuario()?.perfil)||window.SIGEE_SESSION?.normalizarPerfil?.(usuario()?.perfil)||String(usuario()?.perfil||'');}
function master(){return perfil()==='Master';}
function exigir(){if(!master())throw new Error('Acesso restrito ao perfil Master.');const c=cliente();if(!c)throw new Error('Cliente Supabase indisponível.');return c;}
function txt(v){return String(v??'').trim();}
function ator(){const u=usuario()||{};return{id:u.id||null,nome:u.nome||u.name||'',email:String(u.email||'').toLowerCase()||null};}
async function listar(f={}){const c=exigir();let q=c.from(T).select('*').order('data_resposta',{ascending:false});if(f.nte)q=q.eq('nte_numero',Number(f.nte));if(f.leitura)q=q.eq('status_leitura',f.leitura);if(f.triagem)q=q.eq('status_triagem',f.triagem);const {data,error}=await q;if(error)throw error;return data||[];}
async function resumo(){const rows=await listar();const A=window.SIGEE_TERRITORIAL_INDICADORES_AUTHORITY;const validas=rows.filter(x=>x.nte_numero&&x.score_satisfacao!=null),sat=A?.mediaSatisfacao?A.mediaSatisfacao(validas):{nota:null,nota5:null,amostra:0};return{total:rows.length,naoLidas:rows.filter(x=>x.status_leitura==='NAO_LIDA').length,emApuracao:rows.filter(x=>x.status_triagem==='EM_APURACAO').length,triagem:rows.filter(x=>x.requer_triagem&&!['CONVERTIDA_EM_OCORRENCIA','ENCERRADA_SEM_OCORRENCIA','ARQUIVO_HISTORICO'].includes(x.status_triagem)).length,convertidas:rows.filter(x=>x.status_triagem==='CONVERTIDA_EM_OCORRENCIA').length,media:sat.nota,media5:sat.nota5,amostra:sat.amostra};}
async function resumoPorNte(){const rows=await listar();const out={};const A=window.SIGEE_TERRITORIAL_INDICADORES_AUTHORITY;for(const r of rows){const n=Number(r.nte_numero);if(!n||r.score_satisfacao==null)continue;if(!out[n])out[n]={rows:[],total:0,naoLidas:0};out[n].rows.push(r);out[n].total++;if(r.status_leitura==='NAO_LIDA')out[n].naoLidas++;}Object.keys(out).forEach(k=>{const sat=A?.mediaSatisfacao?A.mediaSatisfacao(out[k].rows):{nota:null,nota5:null};out[k].media=sat.nota;out[k].media5=sat.nota5;delete out[k].rows;});return out;}
async function atualizar(id,patch){const c=exigir();const {data,error}=await c.from(T).update({...patch,updated_at:new Date().toISOString()}).eq('id',id).select('*').single();if(error)throw error;document.dispatchEvent(new CustomEvent('sigee:gt-pesquisa-atualizada'));return data;}
async function marcarLida(id){const a=ator();return atualizar(id,{status_leitura:'LIDA',lida_em:new Date().toISOString(),lida_por_id:a.id,lida_por_nome:a.nome,lida_por_email:a.email});}
async function emApuracao(id,obs){const a=ator();return atualizar(id,{status_triagem:'EM_APURACAO',observacao_triagem:txt(obs)||null,tratada_por_id:a.id,tratada_por_nome:a.nome,tratada_por_email:a.email});}
async function encerrar(id,medida,desfecho){const a=ator();return atualizar(id,{status_leitura:'LIDA',status_triagem:'ENCERRADA_SEM_OCORRENCIA',medida_adotada:txt(medida)||null,desfecho:txt(desfecho)||null,tratada_em:new Date().toISOString(),tratada_por_id:a.id,tratada_por_nome:a.nome,tratada_por_email:a.email});}
async function converter(id,p){const rows=await listar();const r=rows.find(x=>Number(x.id)===Number(id));if(!r)throw new Error('Avaliação não localizada.');if(!r.nte_numero)throw new Error('Esta resposta não possui NTE identificado. Vincule o território antes de converter em ocorrência.');const ms=window.SIGEE_TERRITORIAL_MONITORAMENTO_SERVICE;if(!ms?.salvarOcorrencia)throw new Error('Serviço de Monitoramento indisponível.');const texto=[r.comentario_email&&`Comentário sobre atendimento por e-mail: ${r.comentario_email}`,r.comentario_presencial&&`Comentário sobre atendimento presencial: ${r.comentario_presencial}`,r.reclamacao_sugestao&&`Reclamação / sugestão geral: ${r.reclamacao_sugestao}`].filter(Boolean).join('\n\n');const oc=await ms.salvarOcorrencia({nte_numero:r.nte_numero,item_monitoria:p.item_monitoria,avaliacao:p.avaliacao,relevancia:p.relevancia,titulo:`Pesquisa de satisfação — ${r.avaliador_nome||r.nome_historico||'manifestação do usuário'}`,descricao:texto||`Avaliação recebida pela Pesquisa de Satisfação em ${new Date(r.data_resposta).toLocaleString('pt-BR')}.`,resultado:'EM_ACOMPANHAMENTO',observacoes:`Origem: Pesquisa de Satisfação #${r.id}. Avaliador: ${r.avaliador_nome||'não informado'}${r.avaliador_email?` <${r.avaliador_email}>`:''}.${p.apuracao?` Apuração inicial: ${p.apuracao}`:''}`});const a=ator();await atualizar(id,{status_leitura:'LIDA',status_triagem:'CONVERTIDA_EM_OCORRENCIA',monitoramento_id:oc.id,item_monitoria_confirmado:p.item_monitoria,avaliacao_confirmada:p.avaliacao,relevancia_confirmada:p.relevancia,observacao_triagem:txt(p.apuracao)||null,medida_adotada:txt(p.medida)||null,tratada_em:new Date().toISOString(),tratada_por_id:a.id,tratada_por_nome:a.nome,tratada_por_email:a.email});return oc;}
let canal=null;
function assinarNovas(cb){const c=cliente();if(!c?.channel||!master()||canal)return;canal=c.channel('gt-pesquisa-satisfacao-novas').on('postgres_changes',{event:'INSERT',schema:'public',table:T},payload=>{document.dispatchEvent(new CustomEvent('sigee:gt-pesquisa-nova',{detail:payload.new}));cb?.(payload.new);}).subscribe();}
window.SIGEE_TERRITORIAL_PESQUISA_SERVICE=Object.freeze({listar,resumo,resumoPorNte,marcarLida,emApuracao,encerrar,converter,assinarNovas,master,versao:'GT-09.0'});
})(window,document);
