/** SIGEE RC11.3.19C — Plano de Ação Territorial com contador leve para o menu. */
(function(window){
'use strict';
if(window.SIGEE_TERRITORIAL_PLANO_ACAO_SERVICE?.versao==='RC11.3.19C') return;
const T='gt_tarefas_corretivas', TP='gt_tarefa_processos', H='gt_tarefas_corretivas_historico';
function cliente(){try{return window.SIGEE_SUPABASE?.criarCliente?.()||window.SIGEE_SUPABASE_CLIENT||window.supabaseClient||null;}catch(_){return null;}}
function usuario(){return window.SIGEE_SESSION?.getUser?.()||window.usuarioLogado||null;}
function perfil(){return window.SIGEE_PERFIS?.normalizar?.(usuario()?.perfil)||String(usuario()?.perfil||'');}
function master(){return perfil()==='Master';}
function nteUsuario(){return window.SIGEE_ESCOPO?.nteUsuario?.(usuario())||usuario()?.nte||null;}
function numeroNte(v){return window.SIGEE_TERRITORIAL_DATA?.numeroNte?.(v)||window.SIGEE_ESCOPO?.numeroNte?.(v)||Number(String(v||'').match(/\d+/)?.[0])||null;}
function territorial(){return master()||window.SIGEE_ESCOPO?.ehTerritorial?.(usuario())===true;}
function exigir(){if(!territorial())throw new Error('Plano de Ação disponível somente para Gestão Master e usuários territoriais.');const c=cliente();if(!c)throw new Error('Cliente Supabase indisponível.');return c;}
function autor(){const u=usuario()||{};return{usuario_id:u.id||null,usuario_nome:u.nome||u.name||'',usuario_email:String(u.email||'').toLowerCase()||null,usuario_perfil:perfil()};}
function txt(v){return String(v??'').trim();}
function statusFechado(s){return ['VALIDADA','CONCLUIDA','CONCLUIDO','REGULARIZADA','REGULARIZADO'].includes(String(s||'').toUpperCase());}
function statusCancelado(s){return String(s||'').toUpperCase()==='CANCELADA';}
function prazoPadrao(rel){return({BAIXA:15,MODERADA:10,ALTA:7,CRITICA:3})[String(rel||'').toUpperCase()]||10;}
function somarDias(data,dias){const d=new Date(data||Date.now());d.setDate(d.getDate()+Number(dias||0));return d.toISOString().slice(0,10);}
function tratamento(oc){const t=String(oc?.tratamento_tipo||'').toUpperCase();if(['MONITORAMENTO','ACAO_CORRETIVA'].includes(t))return t;return oc?.requer_acao_corretiva===true?'ACAO_CORRETIVA':'MONITORAMENTO';}
async function historico(tarefaId,status,observacao){const c=exigir(),a=autor();const {error}=await c.from(H).insert({tarefa_id:Number(tarefaId),status:String(status||'').toUpperCase(),observacao:txt(observacao)||null,...a});if(error)console.warn('[Plano Ação] histórico:',error);}
async function listar(filtros={}){const c=exigir();let q=c.from(T).select('*,gt_tarefa_processos(*)').neq('status','CANCELADA').order('created_at',{ascending:false});const n=master()?numeroNte(filtros.nte_numero):numeroNte(nteUsuario());if(n)q=q.eq('nte_numero',n);if(filtros.status)q=q.eq('status',String(filtros.status).toUpperCase());const {data,error}=await q;if(error)throw error;return data||[];}
async function obter(id){const c=exigir();let q=c.from(T).select('*,gt_tarefa_processos(*),gt_tarefas_corretivas_historico(*)').eq('id',Number(id));if(!master()){const n=numeroNte(nteUsuario());if(n)q=q.eq('nte_numero',n);}const {data,error}=await q.single();if(error)throw error;return data;}
async function tarefaDaOcorrencia(id){const c=exigir();const {data,error}=await c.from(T).select('*').eq('monitoramento_id',Number(id)).limit(1);if(error)throw error;return data?.[0]||null;}
async function validarAlteracaoTratamento(monitoramentoId,novoTratamento){if(!master())return true;if(String(novoTratamento||'').toUpperCase()!=='MONITORAMENTO')return true;const t=await tarefaDaOcorrencia(monitoramentoId);if(!t||statusCancelado(t.status)||String(t.status).toUpperCase()==='PENDENTE')return true;throw new Error('Este Plano de Ação já possui execução ou validação registrada. Para preservar a auditoria, ele não pode ser convertido em Monitoramento.');}
async function criarDaOcorrencia(oc){if(!master())throw new Error('Somente a Gestão Master cria planos de ação a partir do monitoramento.');if(String(oc?.avaliacao||'').toUpperCase()!=='NEGATIVA'||tratamento(oc)!=='ACAO_CORRETIVA')return null;const c=exigir(),existente=await tarefaDaOcorrencia(oc.id),dias=prazoPadrao(oc.relevancia);const campos={nte_numero:numeroNte(oc.nte_numero),criterio:oc.item_monitoria,titulo:txt(oc.titulo)||'Ação corretiva do Monitoramento Territorial',descricao:txt(oc.descricao),acao_necessaria:txt(oc.observacoes)||'Corrigir a não conformidade identificada e registrar a providência adotada.',relevancia:String(oc.relevancia||'MODERADA').toUpperCase(),prazo:oc.prazo||somarDias(oc.data_registro,dias),updated_at:new Date().toISOString()};if(existente){if(statusCancelado(existente.status)){const {data,error}=await c.from(T).update({...campos,status:'PENDENTE',iniciado_em:null,enviado_validacao_em:null,validado_em:null,concluido_em:null,validado_por:null,validado_por_nome:null,observacao_validacao:null}).eq('id',existente.id).select('*').single();if(error)throw error;await historico(data.id,'PENDENTE','Plano de Ação reativado após alteração do tratamento para Ação Corretiva.');if(oc.processo_id)await c.from(TP).upsert({tarefa_id:data.id,processo_id:Number(oc.processo_id),codigo_sigee:txt(oc.codigo_sigee)||null,status_correcao:'PENDENTE'},{onConflict:'tarefa_id,processo_id'});document.dispatchEvent(new CustomEvent('sigee:gt-plano-acao-atualizado'));return data;}const {data,error}=await c.from(T).update(campos).eq('id',existente.id).select('*').single();if(error)throw error;if(oc.processo_id)await c.from(TP).upsert({tarefa_id:data.id,processo_id:Number(oc.processo_id),codigo_sigee:txt(oc.codigo_sigee)||null,status_correcao:statusFechado(data.status)?'VALIDADA':'PENDENTE'},{onConflict:'tarefa_id,processo_id'});return data;}const reg={monitoramento_id:Number(oc.id),...campos,status:'PENDENTE',criado_por_id:autor().usuario_id,criado_por_nome:autor().usuario_nome,criado_por_email:autor().usuario_email};const {data,error}=await c.from(T).insert(reg).select('*').single();if(error)throw error;if(oc.processo_id)await c.from(TP).insert({tarefa_id:data.id,processo_id:Number(oc.processo_id),codigo_sigee:txt(oc.codigo_sigee)||null,status_correcao:'PENDENTE'});await historico(data.id,'PENDENTE','Plano de Ação criado a partir de constatação classificada como Ação Corretiva.');document.dispatchEvent(new CustomEvent('sigee:gt-plano-acao-atualizado'));return data;}
async function cancelarPorMonitoramento(oc){if(!master())throw new Error('Somente a Gestão Master altera o tratamento da ocorrência.');const t=await tarefaDaOcorrencia(oc.id);if(!t||statusCancelado(t.status))return t;if(String(t.status||'').toUpperCase()!=='PENDENTE')throw new Error('Este Plano de Ação já possui execução. Para preservar a auditoria, não pode ser convertido em Monitoramento.');const c=exigir(),agora=new Date().toISOString();const {data,error}=await c.from(T).update({status:'CANCELADA',observacao_validacao:'Tratamento alterado para Monitoramento.',updated_at:agora}).eq('id',t.id).select('*').single();if(error)throw error;await historico(t.id,'CANCELADA','Plano de Ação cancelado porque a ocorrência foi classificada como Monitoramento.');document.dispatchEvent(new CustomEvent('sigee:gt-plano-acao-atualizado'));return data;}
async function sincronizarDaOcorrencia(oc){if(String(oc?.avaliacao||'').toUpperCase()!=='NEGATIVA'||tratamento(oc)==='MONITORAMENTO')return cancelarPorMonitoramento(oc);return criarDaOcorrencia(oc);}
async function iniciar(id){if(master())throw new Error('A execução da correção deve ser registrada pelo território.');const c=exigir(),a=autor();const {data,error}=await c.from(T).update({status:'EM_EXECUCAO',iniciado_em:new Date().toISOString(),responsavel_usuario_id:a.usuario_id,responsavel_nome:a.usuario_nome,updated_at:new Date().toISOString()}).eq('id',Number(id)).select('*').single();if(error)throw error;await historico(id,'EM_EXECUCAO','Execução iniciada pelo território.');document.dispatchEvent(new CustomEvent('sigee:gt-plano-acao-atualizado'));return data;}
async function informarCorrecao(id,providencia,evidencia){if(master())throw new Error('A providência deve ser informada pelo território.');if(!txt(providencia))throw new Error('Descreva a providência adotada.');const c=exigir();const agora=new Date().toISOString();const {data,error}=await c.from(T).update({status:'AGUARDANDO_VALIDACAO',providencia_adotada:txt(providencia),evidencia_descricao:txt(evidencia)||null,enviado_validacao_em:agora,updated_at:agora}).eq('id',Number(id)).select('*').single();if(error)throw error;await historico(id,'AGUARDANDO_VALIDACAO',`Providência informada: ${txt(providencia)}`);await registrarHistoricoProcessos(id,'Correção informada pelo território',txt(providencia));document.dispatchEvent(new CustomEvent('sigee:gt-plano-acao-atualizado'));return data;}
async function validar(id,observacao=''){if(!master())throw new Error('Somente a Gestão Master valida a correção.');const c=exigir(),a=autor(),agora=new Date().toISOString();const {data,error}=await c.from(T).update({status:'CONCLUIDA',validado_em:agora,concluido_em:agora,validado_por:a.usuario_id,validado_por_nome:a.usuario_nome,observacao_validacao:txt(observacao)||null,updated_at:agora}).eq('id',Number(id)).select('*').single();if(error)throw error;await c.from(TP).update({status_correcao:'VALIDADA',validado_em:agora}).eq('tarefa_id',Number(id));await historico(id,'CONCLUIDA',txt(observacao)||'Correção validada pela Gestão Master.');await registrarHistoricoProcessos(id,'Correção validada pelo Monitoramento Territorial',txt(observacao)||'Ação corretiva validada.');document.dispatchEvent(new CustomEvent('sigee:gt-plano-acao-atualizado'));return data;}
async function devolver(id,motivo){if(!master())throw new Error('Somente a Gestão Master pode devolver a correção.');if(!txt(motivo))throw new Error('Informe o motivo da devolução.');const c=exigir(),agora=new Date().toISOString();const {data,error}=await c.from(T).update({status:'DEVOLVIDA',observacao_validacao:txt(motivo),updated_at:agora}).eq('id',Number(id)).select('*').single();if(error)throw error;await historico(id,'DEVOLVIDA',motivo);document.dispatchEvent(new CustomEvent('sigee:gt-plano-acao-atualizado'));return data;}
async function registrarHistoricoProcessos(id,acao,observacao){const c=exigir();const t=await obter(id);const links=t.gt_tarefa_processos||[];for(const p of links){const reg={processo_id:p.processo_id,codigo_sigee:p.codigo_sigee||'',etapa:'Monitoramento Territorial',acao,observacao:`Plano de Ação Territorial #${id}. ${observacao||''}`.trim(),usuario_nome:autor().usuario_nome,usuario_email:autor().usuario_email,usuario_perfil:autor().usuario_perfil,nte:`NTE-${String(t.nte_numero).padStart(2,'0')}`,dados:{tarefa_id:id,monitoramento_id:t.monitoramento_id},created_at:new Date().toISOString()};const {error}=await c.from('historico_processos').insert(reg);if(error)console.warn('[Plano Ação] histórico do processo:',error);}}
async function resumo(nte){const rows=await listar({nte_numero:nte});const total=rows.length,concluidas=rows.filter(x=>statusFechado(x.status)).length,naoFechadas=rows.filter(x=>!statusFechado(x.status)),aguardando=naoFechadas.filter(x=>String(x.status).toUpperCase()==='AGUARDANDO_VALIDACAO').length,ativas=naoFechadas.filter(x=>String(x.status).toUpperCase()!=='AGUARDANDO_VALIDACAO'),criticas=naoFechadas.filter(x=>String(x.relevancia).toUpperCase()==='CRITICA').length;return{total,concluidas,pendentes:ativas.length,aguardando,criticas,taxaRegularizacao:total?Math.round(concluidas/total*100):null};}
async function contarAbertas(){const c=exigir();let q=c.from(T).select('id',{count:'exact',head:true}).not('status','in','(CANCELADA,VALIDADA,CONCLUIDA,CONCLUIDO,REGULARIZADA,REGULARIZADO)');const n=master()?null:numeroNte(nteUsuario());if(n)q=q.eq('nte_numero',n);const {count,error}=await q;if(error)throw error;return Number(count||0);}
window.SIGEE_TERRITORIAL_PLANO_ACAO_SERVICE=Object.freeze({listar,obter,criarDaOcorrencia,sincronizarDaOcorrencia,validarAlteracaoTratamento,iniciar,informarCorrecao,validar,devolver,resumo,contarAbertas,master,territorial,statusFechado,versao:'RC11.3.19C'});
})(window);
