/** SIGEE Enterprise — GT-06 Mapa Vetorial / Sala de Situação Territorial. */
(function(window,document){
'use strict';
if(window.SIGEE_TERRITORIAL_MAPA) return;
const POS={
1:{x:42.207,y:32.185},       // Irecê
2:{x:41.397,y:51.612},       // Bom Jesus da Lapa
3:{x:54.842,y:51.612},       // Seabra
4:{x:80.400,y:35.600},       // Serrinha
5:{x:82.300,y:72.500},       // Itabuna
6:{x:83.200,y:57.900},       // Valença
7:{x:75.800,y:94.000},       // Teixeira de Freitas
8:{x:65.930,y:77.029},       // Itapetinga
9:{x:75.300,y:55.000},       // Amargosa
10:{x:54.377,y:8.797},       // Juazeiro
11:{x:13.918,y:34.915},      // Barreiras
12:{x:45.500,y:55.300},      // Macaúbas
13:{x:50.500,y:65.500},      // Caetité
14:{x:64.335,y:41.989},      // Itaberaba
15:{x:73.600,y:42.000},      // Ipirá
16:{x:59.360,y:25.549},      // Jacobina
17:{x:86.800,y:29.700},      // Ribeira do Pombal
18:{x:90.800,y:39.000},      // Alagoinhas
19:{x:81.500,y:42.500},      // Feira de Santana
20:{x:61.600,y:71.500},      // Vitória da Conquista
21:{x:81.800,y:51.800},      // Santo Antônio de Jesus
22:{x:67.800,y:62.500},      // Jequié
23:{x:11.800,y:60.000},      // Santa Maria da Vitória
24:{x:84.675,y:6.296},       // Paulo Afonso
25:{x:63.205,y:17.467},      // Senhor do Bonfim
26:{x:91.106,y:53.923},      // Salvador
27:{x:80.200,y:84.500}       // Eunápolis
};
const LABEL={CONCLUIDA:'Concluída',EM_REALIZACAO:'Em realização',AGENDADA:'Agendada',PENDENTE:'Pendente',EXCELENTE:'Excelente',BOM:'Bom',ATENCAO:'Atenção',ALERTA:'Alerta',CRITICO:'Crítico',SEM_AMOSTRA:'Sem amostra',PRIORITARIA:'Prioritária',ALTA:'Alta',MODERADA:'Moderada',BAIXA:'Baixa',SEM_EVIDENCIA:'Sem evidência'};
let dados=[];
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function nota(v){return v==null?'—':`${String(Math.round(Number(v)*10)/10).replace('.',',')}%`;}
function classe(layer,x){if(layer==='FORMACAO')return `form-${x.statusFormacao.toLowerCase()}`;if(layer==='PRIORIDADE')return `pri-${String(x.prioridadeClasse||'sem_evidencia').toLowerCase()}`;if(layer==='DESEMPENHO')return `des-${String(x.classeDesempenho||'sem_amostra').toLowerCase()}`;if(layer==='SATISFACAO'){if(x.satisfacao==null)return'neutral';return x.satisfacao>=90?'des-excelente':x.satisfacao>=80?'des-bom':x.satisfacao>=70?'des-atencao':x.satisfacao>=50?'des-alerta':'des-critico';}if(layer==='MONITORIA'){if(x.notaTecnica==null)return'neutral';return x.notaTecnica>=90?'des-excelente':x.notaTecnica>=80?'des-bom':x.notaTecnica>=70?'des-atencao':x.notaTecnica>=50?'des-alerta':'des-critico';}return'neutral';}
function valor(layer,x){if(layer==='FORMACAO')return LABEL[x.statusFormacao]||x.statusFormacao;if(layer==='PRIORIDADE')return x.fase==='POS_FORMACAO'?'Já formada':`${LABEL[x.prioridadeClasse]||'—'}${x.prioridadeNota!=null?` • ${nota(x.prioridadeNota)}`:''}`;if(layer==='DESEMPENHO')return x.fase==='PRE_FORMACAO'?'Pré-formação':`${LABEL[x.classeDesempenho]||'—'} • ${nota(x.indiceConsolidado)}`;if(layer==='SATISFACAO')return `${nota(x.satisfacao)} • ${x.amostraSatisfacao} resposta(s)`;if(layer==='MONITORIA')return `${nota(x.notaTecnica)} • ${x.amostraTecnica} avaliação(ões)`;if(layer==='PRODUCAO')return `${new Intl.NumberFormat('pt-BR').format(x.producao)} processo(s)`;if(layer==='VISITAS')return `${x.visitas} visita(s) • ${x.reunioes} reunião(ões)`;return'—';}
function legenda(layer){const l={FORMACAO:[['form-concluida','Concluída'],['form-em_realizacao','Em realização'],['form-agendada','Agendada'],['form-pendente','Pendente']],PRIORIDADE:[['pri-prioritaria','Prioritária'],['pri-alta','Alta'],['pri-moderada','Moderada'],['pri-baixa','Baixa'],['neutral','Sem evidência / já formada']],DESEMPENHO:[['des-excelente','Excelente'],['des-bom','Bom'],['des-atencao','Atenção'],['des-alerta','Alerta'],['des-critico','Crítico'],['neutral','Sem amostra / pré-formação']],SATISFACAO:[['des-excelente','≥ 90%'],['des-bom','80–89%'],['des-atencao','70–79%'],['des-alerta','50–69%'],['des-critico','< 50%'],['neutral','Sem amostra']],MONITORIA:[['des-excelente','≥ 90%'],['des-bom','80–89%'],['des-atencao','70–79%'],['des-alerta','50–69%'],['des-critico','< 50%'],['neutral','Sem amostra']],PRODUCAO:[['neutral','Valor exibido no marcador']],VISITAS:[['neutral','Visitas e reuniões realizadas']]};return `<div class="gt-map-legend">${(l[layer]||[]).map(([c,t])=>`<span><i class="${c}"></i>${t}</span>`).join('')}</div>`;}
function detalhe(x,layer){return `<div class="gt-map-detail"><div><span>${esc(x.codigo)}</span><h3>${esc(x.sede)}</h3><small>${x.municipios} município(s) • ${x.fase==='POS_FORMACAO'?'Pós-formação':'Pré-formação'}</small></div><div class="gt-map-detail-kpis"><span><b>${esc(valor(layer,x))}</b>Camada atual</span><span><b>${nota(x.notaTecnica)}</b>Monitoria técnica</span><span><b>${nota(x.satisfacao)}</b>Satisfação</span><span><b>${x.positivas}/${x.negativas}</b>Positivas / negativas</span><span><b>${x.visitas}/${x.reunioes}</b>Visitas / reuniões</span><span><b>${new Intl.NumberFormat('pt-BR').format(x.producao)}</b>Produção</span></div><button type="button" data-dossie="${x.numero}">Abrir dossiê territorial</button></div>`;}
function renderMapa(root,layer,selecionado){const maxProd=Math.max(1,...dados.map(x=>x.producao));const markers=dados.map(x=>{const p=POS[x.numero]||{x:50,y:50},size=layer==='PRODUCAO'?Math.max(42,Math.min(60,42+(x.producao/maxProd)*18)):44;return `<button type="button" class="gt-map-marker ${classe(layer,x)} ${selecionado===x.numero?'selecionado':''}" data-nte="${x.numero}" style="left:${p.x}%;top:${p.y}%;--gt-marker-size:${size}px" title="${esc(x.codigo+' — '+x.sede+': '+valor(layer,x))}"><span>${x.numero}</span></button>`;}).join('');root.querySelector('#gt-map-canvas').innerHTML=`<img src="assets/gt-mapa-nte.svg?v=GT-06.1.3" alt="Mapa vetorial institucional dos Núcleos Territoriais de Educação da Bahia"><div class="gt-map-markers">${markers}</div>`;root.querySelector('#gt-map-legenda').innerHTML=legenda(layer);root.querySelectorAll('[data-nte]').forEach(b=>b.addEventListener('click',()=>selecionar(root,Number(b.dataset.nte))));}
function selecionar(root,n){const x=dados.find(d=>d.numero===n);if(!x)return;root.dataset.selecionado=n;const layer=root.querySelector('#gt-map-layer').value;renderMapa(root,layer,n);root.querySelector('#gt-map-detalhe').innerHTML=detalhe(x,layer);root.querySelector('#gt-map-detalhe [data-dossie]')?.addEventListener('click',()=>window.SIGEE_TERRITORIAL_FORMACOES?.abrirDossie?.(n));root.querySelector('#gt-map-nte').value=String(n);}
function resumo(){const concl=dados.filter(x=>x.statusFormacao==='CONCLUIDA').length,ag=dados.filter(x=>['AGENDADA','EM_REALIZACAO'].includes(x.statusFormacao)).length,pend=dados.filter(x=>x.statusFormacao==='PENDENTE').length,crit=dados.filter(x=>x.classeDesempenho==='CRITICO').length,prio=dados.filter(x=>x.prioridadeClasse==='PRIORITARIA').length;return `<div class="gt-kpis gt-map-kpis"><article><span>Formação concluída</span><strong>${concl}</strong><small>pós-formação</small></article><article><span>Agendada / em realização</span><strong>${ag}</strong><small>próximas intervenções</small></article><article><span>Pendentes</span><strong>${pend}</strong><small>sem formação concluída</small></article><article><span>Prioridade máxima</span><strong>${prio}</strong><small>pré-formação</small></article><article><span>Críticos</span><strong>${crit}</strong><small>pós-formação</small></article></div>`;}
async function carregar(root){root=root||document.querySelector('#gt-conteudo');if(!root)return;root.innerHTML='<div class="gt-empty">Carregando Sala de Situação Territorial...</div>';try{dados=await window.SIGEE_TERRITORIAL_INDICADORES_SERVICE.carregar();root.innerHTML=`<article class="gt-panel gt-panel-full gt-map-shell"><header><div><span>SALA DE SITUAÇÃO • GT-06</span><h2>Mapa vetorial dos 27 NTEs</h2><p>Visualização territorial integrada a formação, prioridade, desempenho, monitoria, satisfação, produção e atuação institucional.</p></div><span class="gt-status">Base cartográfica institucional</span></header>${resumo()}<div class="gt-map-toolbar"><label>Camada<select id="gt-map-layer"><option value="FORMACAO">Cobertura de formação</option><option value="PRIORIDADE">Prioridade para formação</option><option value="DESEMPENHO">Desempenho pós-formação</option><option value="MONITORIA">Monitoria técnica</option><option value="SATISFACAO">Pesquisa de satisfação</option><option value="PRODUCAO">Produção</option><option value="VISITAS">Visitas e reuniões</option></select></label><label>NTE<select id="gt-map-nte"><option value="">Selecione</option>${dados.map(x=>`<option value="${x.numero}">${x.codigo} — ${esc(x.sede)}</option>`).join('')}</select></label><small>Selecione um marcador para abrir o resumo e o dossiê territorial.</small></div><div id="gt-map-legenda"></div><div class="gt-map-layout"><div id="gt-map-canvas" class="gt-map-canvas"></div><aside id="gt-map-detalhe"><div class="gt-empty">Selecione um NTE no mapa.</div></aside></div><div class="gt-map-source">Fonte cartográfica: mapa institucional dos Núcleos Territoriais de Educação da Bahia (SEI/DIGEO/CARTGEO). Indicadores: dados internos do SIGEE.</div></article>`;renderMapa(root,'FORMACAO',null);root.querySelector('#gt-map-layer').addEventListener('change',()=>{const n=Number(root.dataset.selecionado)||null;renderMapa(root,root.querySelector('#gt-map-layer').value,n);if(n)selecionar(root,n);});root.querySelector('#gt-map-nte').addEventListener('change',e=>{if(e.target.value)selecionar(root,Number(e.target.value));});}catch(e){root.innerHTML=`<div class="gt-agenda-alert"><strong>Não foi possível carregar o mapa territorial</strong><span>${esc(e.message||e)}</span></div>`;}}
window.SIGEE_TERRITORIAL_MAPA=Object.freeze({carregar,versao:'GT-06.1.3'});
})(window,document);
