/** SIGEE — Escolas Extintas / Descredenciamento e Acervo — 2026.09.15 */
(function(w){'use strict';if(w.SIGEE_EXTINTAS_DESC_SERVICE)return;
const C=()=>w.SIGEE_SUPABASE?.criarCliente?.()||w.SIGEE_SUPABASE_CLIENT||w.supabaseClient;const PAGE_SIZE=25;function paginar(q,pagina=1,tamanho=PAGE_SIZE){pagina=Math.max(1,Number(pagina)||1);tamanho=Math.min(50,Math.max(1,Number(tamanho)||PAGE_SIZE));const de=(pagina-1)*tamanho;return q.range(de,de+tamanho-1);}
const U=()=>w.SIGEE_SESSION?.getUser?.()||w.usuarioLogado||{};
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim();
const perfilBase=()=>norm(U().perfil);
const perfil=()=>norm(w.SIGEE_MODULOS?.perfilNoModulo?.('ESCOLAS_EXTINTAS',U())||U().perfil);
const global=()=>perfilBase()==='MASTER'||(perfilBase()==='SEC'&&w.SIGEE_MODULOS?.podeAcessar?.('ESCOLAS_EXTINTAS',U())===true);
const podeEditarCatalogo=()=>['MASTER','SEC'].includes(perfilBase());
const podeAnalisarAcervo=()=>['MASTER','SEC'].includes(perfilBase());
const podeSolicitarAlteracaoAcervo=()=>!podeAnalisarAcervo();
const nte=()=>{const modular=w.SIGEE_MODULOS?.nteNoModulo?.('ESCOLAS_EXTINTAS',U());return Number(modular||U().nte_id||String(U().nte||'').match(/\d{1,2}/)?.[0]||0)||null;};
function qscope(q){return global()?q:(nte()?q.eq('nte_id',nte()):q.eq('nte_id',-1));}



async function contarTabela(table,scopeFn){let q=C().from(table).select('id',{count:'exact',head:true});if(scopeFn)q=scopeFn(q);const r=await q;if(r.error)throw r.error;return Number(r.count||0);}
async function contarProcedimentos(){return contarTabela('extintas_descredenciamentos',qscope);}
async function contarProcedimentosOrigem(origem){let q=C().from('extintas_descredenciamentos').select('id',{count:'exact',head:true}).eq('origem',String(origem||''));q=qscope(q);const r=await q;if(r.error)throw r.error;return Number(r.count||0);}
async function contarParalisadas(){let q=C().from('escolas_sigee').select('id',{count:'exact',head:true}).or('situacao.eq.PARALISADA,situacao_funcional.eq.PARALISADA');q=qscopeEscola(q);const r=await q;if(r.error)throw r.error;return Number(r.count||0);}
async function contarDescredenciamento(){let q=C().from('extintas_descredenciamentos').select('id',{count:'exact',head:true}).not('status','in','("CONCLUIDO","PUBLICADO","EXTINTO","AGUARDANDO_PUBLICACAO")').neq('origem','PARALISACAO_ESTADUAL').neq('tipo','ESTADUAL');q=qscope(q);const r=await q;if(r.error)throw r.error;return Number(r.count||0);}
async function contarAguardandoPublicacao(){let q=C().from('extintas_descredenciamentos').select('id',{count:'exact',head:true}).eq('status','AGUARDANDO_PUBLICACAO');q=qscope(q);const r=await q;if(r.error)throw r.error;return Number(r.count||0);}
async function contarEscolasExtintas(){let q=C().from('escolas_sigee').select('id',{count:'exact',head:true}).or('situacao.eq.EXTINTA,situacao.eq.DESCREDENCIADA,situacao_funcional.eq.EXTINTA,situacao_funcional.eq.DESCREDENCIADA');q=qscopeEscola(q);const r=await q;if(r.error)throw r.error;return Number(r.count||0);}
async function contarCustodia(){const alvo=Number(!global()?nte():0)||null;const r=await C().rpc('sigee_panorama_custodia_paginado',{p_nte_id:alvo,p_dependencia:null,p_busca:null,p_espera:0,p_pagina:1,p_tamanho:1});if(r.error)throw r.error;return Number(r.data?.total||0);}
async function contadoresControle(){const vals=await Promise.allSettled([contarProcedimentos(),contarParalisadas(),contarDescredenciamento(),contarAguardandoPublicacao(),contarEscolasExtintas(),contarCustodia()]);const v=i=>vals[i].status==='fulfilled'?vals[i].value:0;return{procedimentos:v(0),paralisadas:v(1),descredenciamento:v(2),aguardandoPublicacao:v(3),extintas:v(4),custodia:v(5)};}
async function listar({pagina=1,tamanho=PAGE_SIZE}={}){let q=C().from('extintas_descredenciamentos').select('*').order('updated_at',{ascending:false});q=qscope(q);q=paginar(q,pagina,tamanho);const r=await q;if(r.error)throw r.error;return r.data||[];}
async function listarParalisadas(){let q=C().from('extintas_estaduais_fluxo').select('*').is('concluido_em',null).order('created_at',{ascending:true});if(!global()&&nte())q=q.eq('nte_id',nte());const r=await q;if(r.error)throw r.error;const fluxos=r.data||[],ids=[...new Set(fluxos.map(x=>Number(x.escola_id)).filter(Boolean))];if(!ids.length)return fluxos;const er=await C().from('escolas_sigee').select('id,cod_mec,nome_escola,nome,municipio,nte_id,dependencia_adm,situacao_funcional,situacao,status_acervo,acervo,local_acervo,tipo_unidade,escola_sede_id').in('id',ids);if(er.error)throw er.error;const mapa=new Map((er.data||[]).map(e=>[Number(e.id),e])),sedeIds=[...new Set((er.data||[]).map(e=>Number(e.escola_sede_id)).filter(Boolean))];let sedes=new Map();if(sedeIds.length){const sr=await C().from('escolas_sigee').select('id,cod_mec,nome_escola,nome,municipio,nte_id,situacao_funcional,situacao,tipo_unidade').in('id',sedeIds);if(sr.error)throw sr.error;sedes=new Map((sr.data||[]).map(e=>[Number(e.id),e]));}return fluxos.map(f=>{const e=mapa.get(Number(f.escola_id))||null,sede=e?.escola_sede_id?sedes.get(Number(e.escola_sede_id))||null:null,matrizAtiva=norm(e?.tipo_unidade)==='ANEXO'&&!!sede&&norm(sede.situacao_funcional||sede.situacao)==='ATIVA';return{...f,escola:e,matriz_responsavel:sede,acervo_nao_aplicavel:matrizAtiva?true:!!f.acervo_nao_aplicavel};});}
async function salvarSeiFluxoEstadual(fluxoId,numeroSei){const sei=String(numeroSei||'').trim();if(!sei)throw new Error('Informe o Processo SEI.');let q=C().from('extintas_estaduais_fluxo').select('id,nte_id,chamado_id,numero_sei').eq('id',Number(fluxoId));if(!global()&&nte())q=q.eq('nte_id',nte());const x=await q.maybeSingle();if(x.error)throw x.error;if(!x.data)throw new Error('Fluxo estadual não localizado no território.');if(String(x.data.numero_sei||'').trim()&&perfilBase()!=='MASTER')throw new Error('O Processo SEI já foi informado. Somente o perfil Master pode alterá-lo.');const r=await C().from('extintas_estaduais_fluxo').update({numero_sei:sei,updated_at:new Date().toISOString()}).eq('id',x.data.id);if(r.error)throw r.error;if(x.data.chamado_id){const c=await C().from('extintas_descredenciamentos').update({numero_sei:sei,updated_at:new Date().toISOString()}).eq('id',x.data.chamado_id);if(c.error)throw c.error;}return true;}
async function listarDescredenciamento(){const xs=await listar();return xs.filter(x=>String(x.origem||'').toUpperCase()!=='PARALISACAO_ESTADUAL'&&String(x.tipo||'').toUpperCase()!=='ESTADUAL');}

async function responsabilidadeAcervo(escola){const tipo=norm(escola?.tipo_unidade||'SEDE');if(tipo!=='ANEXO'||!Number(escola?.escola_sede_id))return{naoAplicavel:false,responsavel:escola||null};const sr=await C().from('escolas_sigee').select('id,cod_mec,nome_escola,nome,municipio,nte_id,situacao_funcional,situacao,status_acervo,acervo,tipo_unidade').eq('id',Number(escola.escola_sede_id)).maybeSingle();if(sr.error)throw sr.error;const sede=sr.data||null,ativa=sede&&norm(sede.situacao_funcional||sede.situacao)==='ATIVA';return{naoAplicavel:!!ativa,responsavel:sede,matrizAtiva:!!ativa};}
async function processoLegalizacaoDaEscola(escolaId){const ir=await C().from('legalizacao_instituicoes').select('id').eq('escola_id',Number(escolaId)).order('id',{ascending:false}).limit(1);if(ir.error)throw ir.error;const iid=ir.data?.[0]?.id;if(!iid)return null;const pr=await C().from('legalizacao_processos').select('*').eq('instituicao_id',iid).eq('tipo','DESCREDENCIAMENTO').not('status','in','(CONCLUIDO,ARQUIVADO,CANCELADO)').order('updated_at',{ascending:false}).limit(1);if(pr.error)throw pr.error;return pr.data?.[0]||null;}
async function fluxoEstadual(chamadoId){const r=await C().from('extintas_estaduais_fluxo').select('*').eq('chamado_id',Number(chamadoId)).maybeSingle();if(r.error)throw r.error;return r.data||null;}
async function iniciarFluxoEstadual(escolaId,p={}){const u=U(),er=await C().from('escolas_sigee').select('*').eq('id',Number(escolaId)).single();if(er.error)throw er.error;const e=er.data,dep=norm(e.dependencia_adm||'');if(!dep.includes('ESTAD'))throw new Error('O fluxo de paralisação estadual é exclusivo para unidades da rede estadual.');if(norm(e.situacao_funcional||e.situacao)!=='PARALISADA')throw new Error('A unidade deve estar PARALISADA antes da abertura do fluxo estadual.');if(!global()&&nte()&&Number(e.nte_id)!==nte())throw new Error('A escola não pertence ao território deste usuário.');const resp=await responsabilidadeAcervo(e),procLeg=await processoLegalizacaoDaEscola(e.id);const ex=await C().from('extintas_estaduais_fluxo').select('id,chamado_id,concluido_em').eq('escola_id',Number(escolaId)).is('concluido_em',null).limit(1);if(ex.error)throw ex.error;if(ex.data?.length)return ex.data[0];const row={origem:'LEGALIZACAO',tipo:'ESTADUAL',legalizacao_processo_id:procLeg?.id||null,escola_id:e.id,nte_id:e.nte_id,escola_nome:e.nome_escola||e.nome,municipio:e.municipio,status:'EM_ANDAMENTO',etapa_atual:'REMANEJAMENTO_PESSOAL',motivo_suspeita:String(p.motivo||'Paralisação de unidade estadual sinalizada para providências administrativas.'),fonte_suspeita:String(p.fonte||'LEGALIZACAO'),criado_por_id:String(u.id||''),atualizado_por_id:String(u.id||'')};const cr=await C().from('extintas_descredenciamentos').insert(row).select('*').single();if(cr.error)throw cr.error;if(!resp.naoAplicavel)await C().from('extintas_acervo_recolhimentos').insert({chamado_id:cr.data.id});const fr=await C().from('extintas_estaduais_fluxo').insert({chamado_id:cr.data.id,escola_id:e.id,nte_id:e.nte_id,legalizacao_processo_id:procLeg?.id||null,acervo_nao_aplicavel:resp.naoAplicavel,acervo_responsavel_escola_id:resp.naoAplicavel?resp.responsavel?.id:null,origem_sinalizacao:String(p.fonte||'LEGALIZACAO'),registrado_por_id:String(u.id||''),registrado_por_nome:u.nome||u.name||u.email||''}).select('*').single();if(fr.error)throw fr.error;return fr.data;}
async function concluirEtapaEstadual(chamadoId,etapa,p={}){const f=await fluxoEstadual(chamadoId);if(!f)throw new Error('Fluxo estadual não localizado.');const e=norm(etapa),agora=new Date().toISOString(),obs=String(p.observacao||'').trim()||null;let upd={},prox='';if(e==='PESSOAL'){upd={pessoal_concluido_em:agora,pessoal_observacao:obs};prox='REMANEJAMENTO_PATRIMONIO';}else if(e==='PATRIMONIO'){if(!f.pessoal_concluido_em)throw new Error('Conclua primeiro o remanejamento de pessoal.');upd={patrimonio_concluido_em:agora,patrimonio_observacao:obs};prox='PRESTACAO_CONTAS';}else if(e==='PRESTACAO_CONTAS'){if(!f.patrimonio_concluido_em)throw new Error('Conclua primeiro o remanejamento de patrimônio.');upd={prestacao_contas_concluida_em:agora,prestacao_contas_observacao:obs};prox='DESTINACAO_ACERVO';}else if(e==='ACERVO'){if(!f.prestacao_contas_concluida_em)throw new Error('Conclua primeiro a prestação de contas.');if(f.acervo_nao_aplicavel)throw new Error('Este anexo possui matriz ativa responsável universal pelo acervo. Não existe recolhimento independente para o anexo.');const ca=await custodiaAtual(f.escola_id);if(!ca)throw new Error('Registre a destinação do acervo antes de concluir esta etapa.');const ct=norm(ca.custodia_tipo);let dest='';if(ct==='NTE')dest='RECOLHIDO_NTE';else if(ct==='EGBA')dest='RECOLHIDO_EGBA';else if(ct==='INSTITUICAO')dest='REMANEJADO_INSTITUICAO';else throw new Error('A destinação deve ser recolhimento pelo NTE, recolhimento direto pela EGBA ou remanejamento para outra Unidade de Ensino.');upd={acervo_concluido_em:agora,acervo_destinacao:dest,acervo_observacao:obs};prox='PUBLICACAO_DESCREDENCIAMENTO';}else throw new Error('Etapa estadual inválida.');upd.updated_at=agora;const r=await C().from('extintas_estaduais_fluxo').update(upd).eq('chamado_id',Number(chamadoId));if(r.error)throw r.error;const x=await C().from('extintas_descredenciamentos').update({etapa_atual:prox,status:'EM_ANDAMENTO',updated_at:agora}).eq('id',Number(chamadoId));if(x.error)throw x.error;return true;}
async function concluirPublicacaoEstadual(chamadoId,p={}){const f=await fluxoEstadual(chamadoId);if(!f?.acervo_concluido_em&&!f?.acervo_nao_aplicavel)throw new Error('Conclua a destinação do acervo antes da publicação.');const ato=String(p.ato_numero||'').trim(),data=String(p.ato_data_publicacao||'').trim();if(!ato||!data)throw new Error('Informe o ato de descredenciamento e a data de publicação.');const agora=new Date().toISOString();const r=await C().from('extintas_estaduais_fluxo').update({ato_numero:ato,ato_data_publicacao:data,ato_referencia:String(p.ato_referencia||'').trim()||null,concluido_em:agora,updated_at:agora}).eq('chamado_id',Number(chamadoId));if(r.error)throw r.error;const c=await C().from('extintas_descredenciamentos').update({status:'CONCLUIDO',etapa_atual:'ENCERRADO',updated_at:agora}).eq('id',Number(chamadoId));if(c.error)throw c.error;const e=await C().from('escolas_sigee').update({situacao_funcional:'EXTINTA',situacao:'EXTINTA'}).eq('id',Number(f.escola_id));if(e.error)throw e.error;return true;}

async function listarAguardandoPublicacao(){const xs=await listar();return xs.filter(x=>['PUBLICACAO_DESCREDENCIAMENTO','AGUARDANDO_PUBLICACAO'].includes(norm(x.etapa_atual))&&!['CONCLUIDO','ENCERRADO','CANCELADO'].includes(norm(x.status)));}
async function listarEscolasExtintas(filtros={}){if(typeof filtros==='string')filtros={busca:filtros};const busca=String(filtros.busca||'').trim(),municipio=String(filtros.municipio||'').trim(),acervo=String(filtros.acervo||'').trim(),nteFiltro=Number(filtros.nte_id||0),pagina=Math.max(1,Number(filtros.pagina||1)),porPagina=Math.min(50,Math.max(10,Number(filtros.porPagina||25))),limpo=v=>String(v||'').replace(/[%(),]/g,'');let q=C().from('escolas_sigee').select('id,cod_mec,nome_escola,nome,municipio,nte_id,nte,dependencia_adm,situacao_funcional,situacao,status_acervo,acervo,local_acervo,ativo',{count:'exact'}).or('situacao_funcional.eq.EXTINTA,situacao.eq.EXTINTA,situacao_funcional.eq.DESCREDENCIADA,situacao.eq.DESCREDENCIADA').order('nome_escola');if(!global()&&nte())q=q.eq('nte_id',nte());else if(nteFiltro)q=q.eq('nte_id',nteFiltro);if(busca.length>=2)q=q.or(`nome_escola.ilike.%${limpo(busca)}%,nome.ilike.%${limpo(busca)}%,cod_mec.ilike.%${limpo(busca)}%`);if(municipio.length>=2)q=q.ilike('municipio',`%${limpo(municipio)}%`);if(acervo)q=q.or(`status_acervo.eq.${limpo(acervo)},acervo.eq.${limpo(acervo)}`);const inicio=(pagina-1)*porPagina;q=q.range(inicio,inicio+porPagina-1);const r=await q;if(r.error)throw r.error;return{items:r.data||[],total:Number(r.count||0),pagina,porPagina,consultaExecutada:true};}
async function escolasTerritorio(filtros={}){if(typeof filtros==='string')filtros={busca:filtros};const busca=String(filtros.busca||'').trim(),municipio=String(filtros.municipio||'').trim(),situacao=String(filtros.situacao||'').trim(),acervo=String(filtros.acervo||'').trim(),nteFiltro=Number(filtros.nte_id||0),pagina=Math.max(1,Number(filtros.pagina||1)),porPagina=Math.min(50,Math.max(10,Number(filtros.porPagina||25)));const temCriterio=busca.length>=2||municipio.length>=2||!!situacao||!!acervo||!!nteFiltro||(!global()&&!!nte());if(!temCriterio)return{items:[],total:0,pagina,porPagina,consultaExecutada:false,noNte:null};const limpo=v=>String(v||'').replace(/[%(),]/g,'');let q=C().from('escolas_sigee').select('id,cod_mec,nome_escola,nome,municipio,nte_id,nte,dependencia_adm,situacao_funcional,situacao,status_acervo,acervo,local_acervo,ativo',{count:'exact'}).order('nome_escola');if(!global()&&nte())q=q.eq('nte_id',nte());else if(nteFiltro)q=q.eq('nte_id',nteFiltro);if(busca.length>=2)q=q.or(`nome_escola.ilike.%${limpo(busca)}%,nome.ilike.%${limpo(busca)}%,cod_mec.ilike.%${limpo(busca)}%`);if(municipio.length>=2)q=q.ilike('municipio',`%${limpo(municipio)}%`);if(situacao)q=q.or(`situacao_funcional.eq.${limpo(situacao)},situacao.eq.${limpo(situacao)}`);if(acervo)q=q.or(`status_acervo.eq.${limpo(acervo)},acervo.eq.${limpo(acervo)}`);const inicio=(pagina-1)*porPagina;q=q.range(inicio,inicio+porPagina-1);const r=await q;if(r.error)throw r.error;const escolas=r.data||[];const ids=escolas.map(x=>x.id);let procedimentos=[];if(ids.length){const pr=await C().from('extintas_descredenciamentos').select('id,escola_id,status,etapa_atual,updated_at').in('escola_id',ids).order('updated_at',{ascending:false});if(pr.error)throw pr.error;procedimentos=pr.data||[];}const mapa=new Map();procedimentos.forEach(x=>{const a=mapa.get(String(x.escola_id))||[];a.push(x);mapa.set(String(x.escola_id),a)});let cq=C().from('vw_acervos_sob_custodia_nte').select('escola_id',{count:'exact',head:true});if(!global()&&nte())cq=cq.eq('nte_id',nte());else if(nteFiltro)cq=cq.eq('nte_id',nteFiltro);const cr=await cq;return{items:escolas.map(e=>({...e,procedimentos:mapa.get(String(e.id))||[]})),total:Number(r.count||0),pagina,porPagina,consultaExecutada:true,noNte:cr.error?null:Number(cr.count||0)};}
async function pesquisarDestinoAcervo(termo,escolaOrigemId){if(!podeEditarCatalogo())throw new Error('Somente o perfil Master pode vincular o destino do acervo.');const busca=String(termo||'').trim();if(busca.length<2)return[];const limpo=busca.replace(/[%(),]/g,'');let q=C().from('escolas_sigee').select('id,cod_mec,nome_escola,nome,municipio,nte_id,situacao_funcional,situacao').neq('id',Number(escolaOrigemId)).or(`nome_escola.ilike.%${limpo}%,nome.ilike.%${limpo}%,cod_mec.ilike.%${limpo}%`).order('nome_escola').limit(20);const r=await q;if(r.error)throw r.error;return r.data||[];}
async function historicoCustodia(escolaId){const r=await C().from('escolas_acervo_movimentacoes').select('id,origem_tipo,origem_escola_id,origem_nte_id,origem_descricao,destino_tipo,destino_escola_id,destino_nte_id,destino_descricao,tipo_movimentacao,status_movimentacao,data_movimentacao,quantidade_caixas,observacao,numero_sei,registrado_por_nome,created_at').eq('escola_origem_id',Number(escolaId)).order('data_movimentacao',{ascending:false}).order('id',{ascending:false});if(r.error)throw r.error;return r.data||[];}

async function custodiaAtual(escolaId){const r=await C().from('vw_escolas_acervo_custodia_atual').select('*').eq('escola_origem_id',Number(escolaId)).maybeSingle();if(r.error)throw r.error;return r.data||null;}
async function enviarAcervoEgba(escolaId,p={}){const atual=await custodiaAtual(escolaId);if(!atual||String(atual.custodia_tipo||'').toUpperCase()!=='NTE')throw new Error('O acervo não está atualmente sob custódia de um NTE.');if(!global()&&nte()&&Number(atual.custodia_nte_id)!==nte())throw new Error('O acervo está sob custódia de outro NTE.');const u=U();const r=await C().rpc('sigee_registrar_envio_acervo_egba',{p_escola_origem_id:Number(escolaId),p_observacao:String(p.observacao||'').trim()||null,p_numero_sei:String(p.numero_sei||'').trim()||null,p_documento_referencia:String(p.documento_referencia||'').trim()||null,p_usuario_id:String(u.id||''),p_usuario_nome:u.nome||u.name||u.email||'',p_usuario_email:String(u.email||'').toLowerCase()||null});if(r.error)throw r.error;return r.data;}
async function resumoCustodiaNte(nteId){let q=C().from('vw_acervos_pendentes_egba_por_nte').select('*');const alvo=Number(nteId||(!global()?nte():0));if(alvo)q=q.eq('nte_id',alvo);const r=await q;if(r.error)throw r.error;return r.data||[];}
async function listarCustodiaNte(nteId){let q=C().from('vw_acervos_sob_custodia_nte').select('*').order('dias_sob_custodia',{ascending:false}).order('escola_nome');const alvo=Number(nteId||(!global()?nte():0));if(alvo)q=q.eq('nte_id',alvo);const r=await q;if(r.error)throw r.error;return r.data||[];}
async function panoramaCustodiaTerritorial(nteId,f={}){const pagina=Math.max(1,Number(f.pagina)||1),tamanho=Math.min(50,Math.max(1,Number(f.tamanho)||25)),alvo=Number(nteId||(!global()?nte():0))||null,dep=String(f.dependencia||'').trim()||null,busca=String(f.busca||'').trim()||null,espera=Math.max(0,Number(f.espera)||0);const r=await C().rpc('sigee_panorama_custodia_paginado',{p_nte_id:alvo,p_dependencia:dep,p_busca:busca,p_espera:espera,p_pagina:pagina,p_tamanho:tamanho});if(r.error)throw r.error;const x=r.data||{};return{itens:Array.isArray(x.itens)?x.itens:[],pagina:Number(x.pagina||pagina),tamanho:Number(x.tamanho||tamanho),total:Number(x.total||0),totalPaginas:Math.max(1,Number(x.total_paginas||x.totalPaginas||1)),totais:x.totais||{nte:0,egba:0,remanejados:0,estaduais:0,privadas:0,caixas:0}};}
async function solicitarAlteracaoAcervo(escolaId,p={}){const u=U(),id=Number(escolaId);const [atual,er]=await Promise.all([C().from('vw_escolas_acervo_custodia_atual').select('*').eq('escola_origem_id',id).maybeSingle(),C().from('escolas_sigee').select('id,status_acervo,acervo,local_acervo').eq('id',id).single()]);if(atual.error)throw atual.error;if(er.error)throw er.error;const justificativa=String(p.justificativa||'').trim();if(!justificativa)throw new Error('Informe a justificativa da solicitação.');const solicitado={status_acervo:p.status_acervo||null,local_acervo:p.local_acervo||null,destino_escola_id:Number(p.destino_escola_id||0)||null};const statusAtual=norm(er.data?.status_acervo||er.data?.acervo||''),localAtual=norm(atual.data?.custodia_tipo||atual.data?.local_atual_acervo||er.data?.local_acervo||''),statusNovo=norm(solicitado.status_acervo),localNovo=statusNovo==='RECOLHIDO'?norm(solicitado.local_acervo):statusNovo==='REMANEJADO'?'INSTITUICAO':'';if(statusAtual===statusNovo&&((statusNovo==='RECOLHIDO'&&localAtual===localNovo)||(statusNovo==='REMANEJADO'&&localAtual==='INSTITUICAO')||(!['RECOLHIDO','REMANEJADO'].includes(statusNovo))))throw new Error('A alteração solicitada é igual à situação atual do acervo.');const r=await C().from('extintas_acervo_solicitacoes_alteracao').insert({escola_id:id,nte_id:nte(),solicitante_id:String(u.id||''),solicitante_nome:u.nome||u.name||u.email||'',solicitante_email:String(u.email||'').toLowerCase()||null,perfil_solicitante:perfilBase()||perfil(),dados_atuais:{...(er.data||{}),custodia:atual.data||null},dados_solicitados:solicitado,justificativa,status:'PENDENTE'}).select('*').single();if(r.error)throw r.error;return r.data;}
async function listarSolicitacoesAlteracaoAcervo(status='PENDENTE'){if(!podeAnalisarAcervo())return[];let q=C().from('extintas_acervo_solicitacoes_alteracao').select('*').order('created_at',{ascending:false});if(status)q=q.eq('status',status);const r=await q;if(r.error)throw r.error;return r.data||[];}
async function decidirSolicitacaoAlteracaoAcervo(id,deferir,observacao=''){if(!podeAnalisarAcervo())throw new Error('Somente SEC/Master podem analisar solicitações de alteração do acervo.');const u=U();const r=await C().rpc('sigee_decidir_solicitacao_alteracao_acervo',{p_solicitacao_id:Number(id),p_deferir:!!deferir,p_observacao:String(observacao||'').trim()||null,p_decisor_id:String(u.id||''),p_decisor_nome:u.nome||u.name||u.email||'',p_decisor_perfil:perfilBase()});if(r.error)throw r.error;return r.data;}

async function atualizarAcervoEscola(escolaId,p){if(!podeEditarCatalogo())throw new Error('Somente os perfis MASTER/SEC podem editar diretamente os dados do acervo. Usuários NTE devem solicitar alteração.');const justificativa=String(p.observacao||'').trim();if(!justificativa)throw new Error('Informe a justificativa da alteração administrativa do acervo.');const atual=await C().from('escolas_sigee').select('id,nte_id,situacao_funcional,situacao,status_acervo,acervo,local_acervo').eq('id',escolaId).maybeSingle();if(atual.error)throw atual.error;if(!atual.data)throw new Error('Escola não localizada.');const situacoes=['ATIVA','MUNICIPALIZADA','PARALISADA','EXTINTA','EM PROCESSO'];const situacao=String(p.situacao_funcional||p.situacao||'').trim();if(!situacoes.includes(norm(situacao)))throw new Error('Selecione uma situação funcional permitida.');const permitidos=['NAO RECOLHIDO','REMANEJADO','A RECOLHER','AGUARDANDO ENTREGA','PARCIALMENTE RECOLHIDO','RECOLHIDO','SEM REGISTRO'];const status=String(p.status_acervo||'').trim();if(!permitidos.includes(norm(status)))throw new Error('Selecione uma situação de acervo permitida.');if(norm(status)==='REMANEJADO'){const destinoId=Number(p.destino_escola_id||0);if(!destinoId)throw new Error('Para ACERVO REMANEJADO, selecione obrigatoriamente a Unidade de Ensino responsável pelo acervo.');if(destinoId===Number(escolaId))throw new Error('A Unidade de Ensino de destino deve ser diferente da unidade de origem.');const u=U();const rpc=await C().rpc('sigee_registrar_remanejamento_acervo',{p_escola_origem_id:Number(escolaId),p_destino_escola_id:destinoId,p_situacao_funcional:situacao,p_observacao:String(p.observacao||'').trim()||null,p_usuario_id:String(u.id||''),p_usuario_nome:u.nome||u.name||u.email||'',p_usuario_email:String(u.email||'').toLowerCase()||null});if(rpc.error)throw rpc.error;return rpc.data;}const local=norm(p.local_acervo||'');if(norm(status)==='RECOLHIDO'&&['NTE','EGBA'].includes(local)){const u=U();const rr=await C().rpc('sigee_regularizar_custodia_historica',{p_escola_origem_id:Number(escolaId),p_destino_tipo:local,p_usuario_id:String(u.id||''),p_usuario_nome:u.nome||u.name||u.email||'',p_usuario_email:String(u.email||'').toLowerCase()||null,p_observacao:justificativa});if(rr.error)throw rr.error;}const payload={situacao_funcional:situacao,situacao:situacao,status_acervo:status,acervo:status,local_acervo:local||null};const r=await C().from('escolas_sigee').update(payload).eq('id',escolaId);if(r.error)throw r.error;return payload;}
async function abrirSuspeita(p){const u=U(),e=(await C().from('escolas_sigee').select('*').eq('id',p.escola_id).single());if(e.error)throw e.error;if(!global()&&nte()&&Number(e.data.nte_id)!==nte())throw new Error('A escola não pertence ao território deste usuário.');const dup=await C().from('extintas_descredenciamentos').select('id,status,etapa_atual').eq('escola_id',p.escola_id).in('status',['AGUARDANDO_INSPECAO','AGUARDANDO_TRATATIVAS','EM_RECOLHIMENTO','AGUARDANDO_SEI_COMPULSORIO','AGUARDANDO_MP','ENCAMINHADO_MP']).limit(1);if(dup.error)throw dup.error;if(dup.data?.length)throw new Error('Já existe um chamado ativo para esta escola. Abra o chamado existente para continuar o acompanhamento.');const row={origem:'SUSPEITA_EXTINCAO',tipo:'SUSPEITA',escola_id:e.data.id,nte_id:e.data.nte_id,escola_nome:e.data.nome_escola||e.data.nome,municipio:e.data.municipio,status:'AGUARDANDO_INSPECAO',etapa_atual:'INSPECAO',motivo_suspeita:p.motivo,fonte_suspeita:p.fonte||null,criado_por_id:String(u.id||''),atualizado_por_id:String(u.id||'')};const r=await C().from('extintas_descredenciamentos').insert(row).select('*').single();if(r.error)throw r.error;await C().from('extintas_acervo_recolhimentos').insert({chamado_id:r.data.id});return r.data;}
async function detalhe(id){let q=C().from('extintas_descredenciamentos').select('*').eq('id',id);q=qscope(q);const c=await q.single();if(c.error)throw c.error;const [a,i,h]=await Promise.all([C().from('extintas_acervo_recolhimentos').select('*').eq('chamado_id',id).maybeSingle(),C().from('extintas_inspecoes').select('*').eq('chamado_id',id).order('created_at',{ascending:false}),C().from('extintas_descredenciamento_historico').select('*').eq('chamado_id',id).order('created_at',{ascending:false})]);let itens=[];if(a.data?.id){const x=await C().from('extintas_acervo_itens').select('*').eq('recolhimento_id',a.data.id).order('ordem');if(x.error)throw x.error;itens=x.data||[];}let origem=null;if(c.data.origem==='LEGALIZACAO'&&c.data.legalizacao_processo_id){const pr=await C().from('legalizacao_processos').select('*').eq('id',c.data.legalizacao_processo_id).maybeSingle();let inst=null;if(pr.data?.instituicao_id){const ir=await C().from('legalizacao_instituicoes').select('*').eq('id',pr.data.instituicao_id).maybeSingle();inst=ir.data||null;}origem={processo:pr.data||null,instituicao:inst};}return{chamado:c.data,acervo:a.data,inspecoes:i.data||[],historico:h.data||[],itens,origem};}
async function garantirItens(acervoId){const ex=await C().from('extintas_acervo_itens').select('id').eq('recolhimento_id',acervoId).limit(1);if(ex.error)throw ex.error;if(ex.data?.length)return;const defs=[['PRONTUARIOS','Prontuários de alunos'],['DIARIOS','Diários de Classe'],['ATAS_FINAIS','Atas de Resultados Finais'],['ATAS_COMPLEMENTARES','Atas de Dependência / Adaptação / Classificação / Reclassificação']];const r=await C().from('extintas_acervo_itens').insert(defs.map((x,i)=>({recolhimento_id:acervoId,codigo:x[0],descricao:x[1],obrigatorio:true,condicao:'NAO_ENTREGUE',em_caixa:true,quantidade_caixas:0,ordem:(i+1)*10})));if(r.error)throw r.error;}
async function salvarItem(id,p){if(!['COMPLETO','INCOMPLETO','NAO_ENTREGUE','COM_AVARIA'].includes(String(p.condicao||'')))throw new Error('Condição documental inválida.');const r=await C().from('extintas_acervo_itens').update({condicao:p.condicao||null,em_caixa:p.em_caixa!==false,quantidade_caixas:p.em_caixa===false?null:Number(p.quantidade_caixas||0),observacao:p.observacao||null,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;}
async function adicionarItem(recolhimento_id,p){const r=await C().from('extintas_acervo_itens').insert({recolhimento_id,descricao:p.descricao,obrigatorio:false,condicao:p.condicao||'COMPLETO',em_caixa:p.em_caixa===true,quantidade_caixas:p.em_caixa?Number(p.quantidade_caixas||0):null,observacao:p.observacao||null,ordem:1000}).select('*').single();if(r.error)throw r.error;return r.data;}
async function salvarAcervo(id,p){const payload={situacao:p.situacao||'EM_RECOLHIMENTO',data_recolhimento:p.data_recolhimento||null,local_guarda:p.local_guarda||null,termo_referencia:p.termo_referencia||null,observacoes:p.observacoes||null,updated_at:new Date().toISOString()};['responsavel_entrega','documento_responsavel','contato_responsavel','unidade_recebedora','organizacao_alfabetica','estado_conservacao','inconformidades','fase_atual','interlocutor_nome','interlocutor_whatsapp','interlocutor_vinculo','interlocutor_observacoes'].forEach(k=>{if(Object.prototype.hasOwnProperty.call(p,k))payload[k]=p[k]||null});const r=await C().from('extintas_acervo_recolhimentos').update(payload).eq('id',id);if(r.error)throw r.error;}
async function concluirAcervo(chamadoId,destino='NTE'){const ch=await chamadoNoEscopo(chamadoId);const er=await C().from('escolas_sigee').select('*').eq('id',Number(ch.escola_id)).single();if(er.error)throw er.error;const resp=await responsabilidadeAcervo(er.data);if(resp.naoAplicavel)throw new Error('Este anexo possui matriz ativa responsável universal pelo acervo. Não existe recolhimento independente para concluir.');const u=U(),dest=norm(destino||'NTE');if(!['NTE','EGBA'].includes(dest))throw new Error('Selecione NTE ou EGBA como destino do recolhimento.');if(dest==='EGBA'){const r=await C().rpc('sigee_extintas_concluir_recolhimento_egba',{p_chamado_id:Number(chamadoId),p_usuario_id:String(u.id||''),p_usuario_nome:u.nome||u.name||u.email||'',p_usuario_email:String(u.email||'').toLowerCase()||null});if(r.error)throw r.error;return r.data;}const r=await C().rpc('sigee_extintas_concluir_recolhimento',{p_chamado_id:chamadoId,p_usuario_id:String(u.id||''),p_usuario_nome:u.nome||u.name||u.email||''});if(r.error)throw r.error;return r.data;}
async function salvarInspecao(chamadoId,p){await chamadoNoEscopo(chamadoId);if(!p.data_inspecao)throw new Error('Informe a data da inspeção.');if(!String(p.relatorio||'').trim())throw new Error('O relatório técnico da inspeção é obrigatório.');const u=U(),row={chamado_id:chamadoId,tipo:'SUSPEITA_EXTINCAO',data_inspecao:p.data_inspecao,tecnico_id:String(u.id||''),tecnico_nome:u.nome||u.name||'',desativacao_constatada:p.desativacao_constatada,escola_localizada:p.escola_localizada,responsavel_localizado:p.responsavel_localizado,acervo_localizado:p.acervo_localizado,acervo_recuperado:p.acervo_recuperado,relatorio:p.relatorio,evidencias:p.evidencias||null};const r=await C().from('extintas_inspecoes').insert(row);if(r.error)throw r.error;const upd=p.desativacao_constatada?{status:p.acervo_recuperado?'EM_RECOLHIMENTO':'AGUARDANDO_SEI_COMPULSORIO',etapa_atual:p.acervo_recuperado?'RECOLHIMENTO':'DESCREDENCIAMENTO_COMPULSORIO',desativacao_constatada:true,responsavel_localizado:p.responsavel_localizado,acervo_localizado:p.acervo_localizado}:{status:'SUSPEITA_NAO_CONFIRMADA',etapa_atual:'ENCERRADO',desativacao_constatada:false};const x=await C().from('extintas_descredenciamentos').update({...upd,updated_at:new Date().toISOString()}).eq('id',chamadoId);if(x.error)throw x.error;}

async function chamadoNoEscopo(id){let q=C().from('extintas_descredenciamentos').select('id,nte_id,status,etapa_atual').eq('id',id);q=qscope(q);const r=await q.maybeSingle();if(r.error)throw r.error;if(!r.data)throw new Error('Chamado não localizado ou fora do seu escopo de atuação.');return r.data;}
async function listarInterlocutores(id){await chamadoNoEscopo(id);const r=await C().from('extintas_interlocutores').select('*').eq('chamado_id',Number(id)).eq('ativo',true).order('nome',{ascending:true});if(r.error)throw r.error;return r.data||[];}
async function cadastrarInterlocutor(id,p){await chamadoNoEscopo(id);const u=U(),nome=String(p.nome||'').trim(),whatsapp=String(p.whatsapp||'').trim(),vinculo=String(p.vinculo_funcao||'').trim();if(!nome)throw new Error('Informe o nome do interlocutor.');if(!whatsapp)throw new Error('Informe o WhatsApp/telefone do interlocutor.');if(!vinculo)throw new Error('Informe o vínculo/função do interlocutor.');const r=await C().from('extintas_interlocutores').insert({chamado_id:Number(id),nome,whatsapp,vinculo_funcao:vinculo,criado_por_id:String(u.id||'')||null,criado_por_nome:u.nome||u.name||u.email||null}).select('*').single();if(r.error)throw r.error;return r.data;}
async function listarTratativas(id){await chamadoNoEscopo(id);const r=await C().from('extintas_tratativas').select('*').eq('chamado_id',Number(id)).order('created_at',{ascending:false});if(r.error)throw r.error;return r.data||[];}
async function registrarTratativa(id,p){await chamadoNoEscopo(id);const u=U(),tipo=norm(p.tipo);if(!['CONTATO','ORIENTACAO'].includes(tipo))throw new Error('Selecione Registro de contato ou Orientação.');const texto=String(p.texto||'').trim();if(!texto)throw new Error('Informe o conteúdo do registro.');const interlocutorId=Number(p.interlocutor_id||0);if(!interlocutorId)throw new Error('Selecione o interlocutor antes de salvar o registro.');const ci=await C().from('extintas_interlocutores').select('*').eq('id',interlocutorId).eq('chamado_id',Number(id)).eq('ativo',true).maybeSingle();if(ci.error)throw ci.error;if(!ci.data)throw new Error('Interlocutor inválido para este procedimento.');const row={chamado_id:Number(id),tipo,interlocutor_id:interlocutorId,interlocutor:ci.data.nome,vinculo_funcao:ci.data.vinculo_funcao,contato:ci.data.whatsapp,texto,usuario_id:String(u.id||'')||null,usuario_nome:u.nome||u.name||u.email||null};const r=await C().from('extintas_tratativas').insert(row).select('*').single();if(r.error)throw r.error;await C().from('extintas_descredenciamento_historico').insert({chamado_id:Number(id),evento:tipo==='CONTATO'?'REGISTRO_CONTATO':'ORIENTACAO_REGISTRADA',descricao:texto,usuario_id:String(u.id||''),usuario_nome:u.nome||u.name||u.email||''});return r.data;}
async function salvarTratativas(id,p){return registrarTratativa(id,{tipo:p.instrucao_registro?'ORIENTACAO':'CONTATO',texto:p.instrucao_registro||p.contato_registro||''});}
async function agendarAtividade(chamadoId,p){
  const z=await detalhe(chamadoId),c=z.chamado,a=z.acervo||{},u=U();
  const tipo=String(p.tipo||'').toUpperCase(),fase=String(p.fase_recolhimento||'').toUpperCase();
  if(!['INSPECAO_SUSPEITA_EXTINCAO','RECOLHIMENTO_ACERVO'].includes(tipo))throw new Error('Tipo de agenda inválido para Escolas Extintas.');
  if(tipo==='RECOLHIMENTO_ACERVO'&&!['ORIENTACAO','VISITA_PREVENTIVA','RECOLHIMENTO'].includes(fase))throw new Error('Informe a fase da ação de recolhimento.');
  if(!p.inicio)throw new Error('Informe a data e hora da atividade.');
  if(tipo==='RECOLHIMENTO_ACERVO'&&(!String(a.interlocutor_nome||'').trim()||!String(a.interlocutor_whatsapp||'').trim()))throw new Error('Cadastre o nome e o WhatsApp do interlocutor da tratativa antes de agendar a ação de recolhimento.');
  const faseLabel={ORIENTACAO:'Orientação',VISITA_PREVENTIVA:'Visita preventiva',RECOLHIMENTO:'Recolhimento'}[fase];
  const row={tipo,titulo:(tipo==='RECOLHIMENTO_ACERVO'?`${faseLabel} de acervo — `:'Inspeção de suspeita de extinção — ')+c.escola_nome,inicio:p.inicio,fim:p.fim||p.inicio,modalidade:'PRESENCIAL',local:p.local||null,motivo:p.motivo||null,objetivo:tipo==='RECOLHIMENTO_ACERVO'?`${faseLabel} vinculada ao mesmo registro de recolhimento de acervo.`:'Constatar a desativação da instituição e tentar localizar/recuperar o acervo escolar.',situacao:'AGENDADO',prioridade:p.prioridade||'NORMAL',observacoes:p.observacoes||null,comunicar_ntes:true,ntes:[Number(c.nte_id)].filter(Boolean),dominio:'ESCOLAS_EXTINTAS',escola_id:c.escola_id||null,chamado_extintas_id:c.id,recolhimento_id:a.id||null,fase_recolhimento:fase||null,legalizacao_processo_id:c.legalizacao_processo_id||null,numero_sei:c.numero_sei||c.numero_sei_compulsorio||null,criado_por_id:u.id||null,criado_por_nome:u.nome||u.name||'',criado_por_email:String(u.email||'').toLowerCase()||null,tecnico_id:String(u.id||'')||null,tecnico_nome:u.nome||u.name||u.email||null,updated_at:new Date().toISOString()};
  const r=await C().from('gt_agenda').insert(row).select('*').single();if(r.error)throw r.error;
  if(tipo==='RECOLHIMENTO_ACERVO'&&a.id){const upd={fase_atual:fase,updated_at:new Date().toISOString()};if(fase==='ORIENTACAO')upd.orientacao_em=p.inicio;if(fase==='VISITA_PREVENTIVA')upd.visita_preventiva_em=p.inicio;if(fase==='RECOLHIMENTO')upd.recolhimento_agendado_em=p.inicio;const ar=await C().from('extintas_acervo_recolhimentos').update(upd).eq('id',a.id);if(ar.error)throw ar.error;}
  await C().from('extintas_descredenciamento_historico').insert({chamado_id:c.id,evento:tipo==='RECOLHIMENTO_ACERVO'?`ACERVO_${fase}_AGENDADA`:'AGENDA_CRIADA',descricao:`${tipo==='RECOLHIMENTO_ACERVO'?faseLabel:tipo}: ${p.inicio}${p.local?' · '+p.local:''}`,usuario_id:String(u.id||''),usuario_nome:u.nome||u.name||u.email||''});
  return r.data;
}
async function registrarCompulsorio(id,p){await chamadoNoEscopo(id);if(!String(p.sei||'').trim())throw new Error('Informe o número do Processo SEI.');const r=await C().from('extintas_descredenciamentos').update({tipo:'COMPULSORIO',numero_sei_compulsorio:p.sei,status:'AGUARDANDO_MP',etapa_atual:'ENCAMINHAMENTO_MP',updated_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;}
async function registrarMP(id,p){await chamadoNoEscopo(id);if(!p.data)throw new Error('Informe a data do encaminhamento.');if(!String(p.referencia||'').trim())throw new Error('Informe a referência do encaminhamento ao Ministério Público.');const r=await C().from('extintas_descredenciamentos').update({encaminhado_mp:true,data_encaminhamento_mp:p.data,referencia_mp:p.referencia,status:'ENCAMINHADO_MP',etapa_atual:'ACOMPANHAMENTO',updated_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;}
async function historico(id){await chamadoNoEscopo(id);const r=await C().from('extintas_descredenciamento_historico').select('*').eq('chamado_id',id).order('created_at',{ascending:false});if(r.error)throw r.error;return r.data||[];}

async function pesquisarInstituicaoDestinoRecolhimento(termo,escolaOrigemId){const busca=String(termo||'').trim();if(busca.length<2)return[];const limpo=busca.replace(/[%(),]/g,'');let q=C().from('escolas_sigee').select('id,cod_mec,nome_escola,nome,municipio,nte_id,situacao_funcional,situacao').neq('id',Number(escolaOrigemId)).or(`nome_escola.ilike.%${limpo}%,nome.ilike.%${limpo}%,cod_mec.ilike.%${limpo}%,municipio.ilike.%${limpo}%`).order('nome_escola').limit(20);const r=await q;if(r.error)throw r.error;return r.data||[];}
async function registrarRemanejamentoAcervoProcesso(chamadoId,destinoEscolaId,p={}){const c=await chamadoNoEscopo(chamadoId);const er=await C().from('escolas_sigee').select('*').eq('id',Number(c.escola_id)).single();if(er.error)throw er.error;const resp=await responsabilidadeAcervo(er.data);if(resp.naoAplicavel)throw new Error('Anexo de matriz ativa não possui remanejamento de acervo: a matriz é a responsável universal.');const u=U();const r=await C().rpc('sigee_registrar_remanejamento_acervo',{p_escola_origem_id:Number(c.escola_id),p_destino_escola_id:Number(destinoEscolaId),p_situacao_funcional:String(er.data.situacao_funcional||er.data.situacao||'PARALISADA'),p_observacao:String(p.observacao||'').trim()||null,p_usuario_id:String(u.id||''),p_usuario_nome:u.nome||u.name||u.email||'',p_usuario_email:String(u.email||'').toLowerCase()||null});if(r.error)throw r.error;return r.data;}
w.SIGEE_EXTINTAS_DESC_SERVICE=Object.freeze({contadoresControle,contarProcedimentos,contarProcedimentosOrigem,contarParalisadas,contarDescredenciamento,contarAguardandoPublicacao,contarEscolasExtintas,contarCustodia,listar,escolasTerritorio,abrirSuspeita,detalhe,garantirItens,salvarItem,adicionarItem,salvarAcervo,concluirAcervo,salvarInspecao,salvarTratativas,listarInterlocutores,cadastrarInterlocutor,listarTratativas,registrarTratativa,agendarAtividade,registrarCompulsorio,registrarMP,historico,global,nte,podeEditarCatalogo,atualizarAcervoEscola,pesquisarDestinoAcervo,historicoCustodia,custodiaAtual,enviarAcervoEgba,resumoCustodiaNte,listarCustodiaNte,panoramaCustodiaTerritorial,solicitarAlteracaoAcervo,listarSolicitacoesAlteracaoAcervo,decidirSolicitacaoAlteracaoAcervo,podeAnalisarAcervo,podeSolicitarAlteracaoAcervo,listarParalisadas,salvarSeiFluxoEstadual,listarDescredenciamento,listarAguardandoPublicacao,listarEscolasExtintas,fluxoEstadual,iniciarFluxoEstadual,concluirEtapaEstadual,concluirPublicacaoEstadual,pesquisarInstituicaoDestinoRecolhimento,registrarRemanejamentoAcervoProcesso});})(window);
