/** SIGEE — Escolas Extintas / Descredenciamento e Acervo — 2026.09.15 */
(function(w){'use strict';if(w.SIGEE_EXTINTAS_DESC_SERVICE)return;
const C=()=>w.SIGEE_SUPABASE?.criarCliente?.()||w.SIGEE_SUPABASE_CLIENT||w.supabaseClient;
const U=()=>w.SIGEE_SESSION?.getUser?.()||w.usuarioLogado||{};
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim();
const perfilBase=()=>norm(U().perfil);
const perfil=()=>norm(w.SIGEE_MODULOS?.perfilNoModulo?.('ESCOLAS_EXTINTAS',U())||U().perfil);
const global=()=>['MASTER','SEC'].includes(perfilBase())&&w.SIGEE_MODULOS?.podeAcessar?.('ESCOLAS_EXTINTAS',U())===true;
const nte=()=>{const modular=w.SIGEE_MODULOS?.nteNoModulo?.('ESCOLAS_EXTINTAS',U());return Number(modular||U().nte_id||String(U().nte||'').match(/\d{1,2}/)?.[0]||0)||null;};
function qscope(q){return global()?q:(nte()?q.eq('nte_id',nte()):q.eq('nte_id',-1));}
async function listar(){let q=C().from('extintas_descredenciamentos').select('*').order('updated_at',{ascending:false}).limit(1000);q=qscope(q);const r=await q;if(r.error)throw r.error;return r.data||[];}
async function escolasTerritorio(busca=''){let q=C().from('escolas_sigee').select('id,cod_mec,nome_escola,nome,municipio,nte_id,situacao_funcional,status_acervo,acervo').order('nome_escola').limit(80);if(!global()&&nte())q=q.eq('nte_id',nte());if(busca)q=q.or(`nome_escola.ilike.%${busca.replace(/[%(),]/g,'')}%,cod_mec.ilike.%${busca.replace(/[%(),]/g,'')}%`);const r=await q;if(r.error)throw r.error;return r.data||[];}
async function abrirSuspeita(p){const u=U(),e=(await C().from('escolas_sigee').select('*').eq('id',p.escola_id).single());if(e.error)throw e.error;if(!global()&&nte()&&Number(e.data.nte_id)!==nte())throw new Error('A escola não pertence ao território deste usuário.');const dup=await C().from('extintas_descredenciamentos').select('id,status,etapa_atual').eq('escola_id',p.escola_id).in('status',['AGUARDANDO_INSPECAO','AGUARDANDO_TRATATIVAS','EM_RECOLHIMENTO','AGUARDANDO_SEI_COMPULSORIO','AGUARDANDO_MP','ENCAMINHADO_MP']).limit(1);if(dup.error)throw dup.error;if(dup.data?.length)throw new Error('Já existe um chamado ativo para esta escola. Abra o chamado existente para continuar o acompanhamento.');const row={origem:'SUSPEITA_EXTINCAO',tipo:'SUSPEITA',escola_id:e.data.id,nte_id:e.data.nte_id,escola_nome:e.data.nome_escola||e.data.nome,municipio:e.data.municipio,status:'AGUARDANDO_INSPECAO',etapa_atual:'INSPECAO',motivo_suspeita:p.motivo,fonte_suspeita:p.fonte||null,criado_por_id:String(u.id||''),atualizado_por_id:String(u.id||'')};const r=await C().from('extintas_descredenciamentos').insert(row).select('*').single();if(r.error)throw r.error;await C().from('extintas_acervo_recolhimentos').insert({chamado_id:r.data.id});return r.data;}
async function detalhe(id){let q=C().from('extintas_descredenciamentos').select('*').eq('id',id);q=qscope(q);const c=await q.single();if(c.error)throw c.error;const [a,i,h]=await Promise.all([C().from('extintas_acervo_recolhimentos').select('*').eq('chamado_id',id).maybeSingle(),C().from('extintas_inspecoes').select('*').eq('chamado_id',id).order('created_at',{ascending:false}),C().from('extintas_descredenciamento_historico').select('*').eq('chamado_id',id).order('created_at',{ascending:false})]);let itens=[];if(a.data?.id){const x=await C().from('extintas_acervo_itens').select('*').eq('recolhimento_id',a.data.id).order('ordem');if(x.error)throw x.error;itens=x.data||[];}return{chamado:c.data,acervo:a.data,inspecoes:i.data||[],historico:h.data||[],itens};}
async function garantirItens(acervoId){const ex=await C().from('extintas_acervo_itens').select('id').eq('recolhimento_id',acervoId).limit(1);if(ex.error)throw ex.error;if(ex.data?.length)return;const defs=[['PRONTUARIOS','Prontuários de alunos'],['DIARIOS','Diários de Classe'],['ATAS_FINAIS','Atas de Resultados Finais'],['ATAS_COMPLEMENTARES','Atas de Dependência / Adaptação / Classificação / Reclassificação']];const r=await C().from('extintas_acervo_itens').insert(defs.map((x,i)=>({recolhimento_id:acervoId,codigo:x[0],descricao:x[1],obrigatorio:true,condicao:'NAO_ENTREGUE',em_caixa:true,quantidade_caixas:0,ordem:(i+1)*10})));if(r.error)throw r.error;}
async function salvarItem(id,p){if(!['COMPLETO','INCOMPLETO','NAO_ENTREGUE','COM_AVARIA'].includes(String(p.condicao||'')))throw new Error('Condição documental inválida.');const r=await C().from('extintas_acervo_itens').update({condicao:p.condicao||null,em_caixa:p.em_caixa!==false,quantidade_caixas:p.em_caixa===false?null:Number(p.quantidade_caixas||0),observacao:p.observacao||null,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;}
async function adicionarItem(recolhimento_id,p){const r=await C().from('extintas_acervo_itens').insert({recolhimento_id,descricao:p.descricao,obrigatorio:false,condicao:p.condicao||'COMPLETO',em_caixa:p.em_caixa===true,quantidade_caixas:p.em_caixa?Number(p.quantidade_caixas||0):null,observacao:p.observacao||null,ordem:1000}).select('*').single();if(r.error)throw r.error;return r.data;}
async function salvarAcervo(id,p){const payload={situacao:p.situacao||'EM_RECOLHIMENTO',data_recolhimento:p.data_recolhimento||null,local_guarda:p.local_guarda||null,termo_referencia:p.termo_referencia||null,observacoes:p.observacoes||null,updated_at:new Date().toISOString()};['responsavel_entrega','documento_responsavel','contato_responsavel','unidade_recebedora','organizacao_alfabetica','estado_conservacao','inconformidades'].forEach(k=>{if(Object.prototype.hasOwnProperty.call(p,k))payload[k]=p[k]||null});const r=await C().from('extintas_acervo_recolhimentos').update(payload).eq('id',id);if(r.error)throw r.error;}
async function concluirAcervo(chamadoId){await chamadoNoEscopo(chamadoId);const u=U(),r=await C().rpc('sigee_extintas_concluir_recolhimento',{p_chamado_id:chamadoId,p_usuario_id:String(u.id||''),p_usuario_nome:u.nome||u.name||u.email||''});if(r.error)throw r.error;return r.data;}
async function salvarInspecao(chamadoId,p){await chamadoNoEscopo(chamadoId);if(!p.data_inspecao)throw new Error('Informe a data da inspeção.');if(!String(p.relatorio||'').trim())throw new Error('O relatório técnico da inspeção é obrigatório.');const u=U(),row={chamado_id:chamadoId,tipo:'SUSPEITA_EXTINCAO',data_inspecao:p.data_inspecao,tecnico_id:String(u.id||''),tecnico_nome:u.nome||u.name||'',desativacao_constatada:p.desativacao_constatada,escola_localizada:p.escola_localizada,responsavel_localizado:p.responsavel_localizado,acervo_localizado:p.acervo_localizado,acervo_recuperado:p.acervo_recuperado,relatorio:p.relatorio,evidencias:p.evidencias||null};const r=await C().from('extintas_inspecoes').insert(row);if(r.error)throw r.error;const upd=p.desativacao_constatada?{status:p.acervo_recuperado?'EM_RECOLHIMENTO':'AGUARDANDO_SEI_COMPULSORIO',etapa_atual:p.acervo_recuperado?'RECOLHIMENTO':'DESCREDENCIAMENTO_COMPULSORIO',desativacao_constatada:true,responsavel_localizado:p.responsavel_localizado,acervo_localizado:p.acervo_localizado}:{status:'SUSPEITA_NAO_CONFIRMADA',etapa_atual:'ENCERRADO',desativacao_constatada:false};const x=await C().from('extintas_descredenciamentos').update({...upd,updated_at:new Date().toISOString()}).eq('id',chamadoId);if(x.error)throw x.error;}

async function chamadoNoEscopo(id){let q=C().from('extintas_descredenciamentos').select('id,nte_id,status,etapa_atual').eq('id',id);q=qscope(q);const r=await q.maybeSingle();if(r.error)throw r.error;if(!r.data)throw new Error('Chamado não localizado ou fora do seu escopo de atuação.');return r.data;}
async function salvarTratativas(id,p){
  await chamadoNoEscopo(id);const u=U(),payload={contato_registro:p.contato_registro||null,instrucao_registro:p.instrucao_registro||null,atualizado_por_id:String(u.id||''),updated_at:new Date().toISOString()};
  const r=await C().from('extintas_descredenciamentos').update(payload).eq('id',id);if(r.error)throw r.error;
  await C().from('extintas_descredenciamento_historico').insert({chamado_id:id,evento:'TRATATIVAS_ATUALIZADAS',descricao:[p.contato_registro&&('Contato: '+p.contato_registro),p.instrucao_registro&&('Instrução: '+p.instrucao_registro)].filter(Boolean).join(' | '),usuario_id:String(u.id||''),usuario_nome:u.nome||u.name||u.email||''});
}
async function agendarAtividade(chamadoId,p){
  const z=await detalhe(chamadoId),c=z.chamado,u=U();
  const tipo=String(p.tipo||'').toUpperCase();
  if(!['INSPECAO_SUSPEITA_EXTINCAO','RECOLHIMENTO_ACERVO'].includes(tipo))throw new Error('Tipo de agenda inválido para Escolas Extintas.');
  if(!p.inicio)throw new Error('Informe a data e hora da atividade.');
  const row={tipo,titulo:(tipo==='RECOLHIMENTO_ACERVO'?'Recolhimento de acervo — ':'Inspeção de suspeita de extinção — ')+c.escola_nome,inicio:p.inicio,fim:p.fim||p.inicio,modalidade:'PRESENCIAL',local:p.local||null,motivo:p.motivo||null,objetivo:tipo==='RECOLHIMENTO_ACERVO'?'Recolher e conferir o acervo escolar disponível.':'Constatar a desativação da instituição e tentar localizar/recuperar o acervo escolar.',situacao:'AGENDADO',prioridade:p.prioridade||'NORMAL',observacoes:p.observacoes||null,comunicar_ntes:true,ntes:[Number(c.nte_id)].filter(Boolean),dominio:'ESCOLAS_EXTINTAS',escola_id:c.escola_id||null,chamado_extintas_id:c.id,legalizacao_processo_id:c.legalizacao_processo_id||null,numero_sei:c.numero_sei||c.numero_sei_compulsorio||null,criado_por_id:u.id||null,criado_por_nome:u.nome||u.name||'',criado_por_email:String(u.email||'').toLowerCase()||null,updated_at:new Date().toISOString()};
  const r=await C().from('gt_agenda').insert(row).select('*').single();if(r.error)throw r.error;
  await C().from('extintas_descredenciamento_historico').insert({chamado_id:c.id,evento:'AGENDA_CRIADA',descricao:`${tipo}: ${p.inicio}${p.local?' · '+p.local:''}`,usuario_id:String(u.id||''),usuario_nome:u.nome||u.name||u.email||''});
  return r.data;
}
async function registrarCompulsorio(id,p){await chamadoNoEscopo(id);if(!String(p.sei||'').trim())throw new Error('Informe o número do Processo SEI.');const r=await C().from('extintas_descredenciamentos').update({tipo:'COMPULSORIO',numero_sei_compulsorio:p.sei,status:'AGUARDANDO_MP',etapa_atual:'ENCAMINHAMENTO_MP',updated_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;}
async function registrarMP(id,p){await chamadoNoEscopo(id);if(!p.data)throw new Error('Informe a data do encaminhamento.');if(!String(p.referencia||'').trim())throw new Error('Informe a referência do encaminhamento ao Ministério Público.');const r=await C().from('extintas_descredenciamentos').update({encaminhado_mp:true,data_encaminhamento_mp:p.data,referencia_mp:p.referencia,status:'ENCAMINHADO_MP',etapa_atual:'ACOMPANHAMENTO',updated_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;}
async function historico(id){await chamadoNoEscopo(id);const r=await C().from('extintas_descredenciamento_historico').select('*').eq('chamado_id',id).order('created_at',{ascending:false});if(r.error)throw r.error;return r.data||[];}
w.SIGEE_EXTINTAS_DESC_SERVICE=Object.freeze({listar,escolasTerritorio,abrirSuspeita,detalhe,garantirItens,salvarItem,adicionarItem,salvarAcervo,concluirAcervo,salvarInspecao,salvarTratativas,agendarAtividade,registrarCompulsorio,registrarMP,historico,global,nte});})(window);
