/** SIGEE — Escolas Extintas / Descredenciamento e Acervo — 2026.09.15 */
(function(w){'use strict';if(w.SIGEE_EXTINTAS_DESC_SERVICE)return;
const C=()=>w.SIGEE_SUPABASE?.criarCliente?.()||w.SIGEE_SUPABASE_CLIENT||w.supabaseClient;
const U=()=>w.SIGEE_SESSION?.getUser?.()||w.usuarioLogado||{};
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim();
const perfil=()=>norm(U().perfil),global=()=>['MASTER','SEC'].includes(perfil());
const nte=()=>Number(U().nte_id||String(U().nte||'').match(/\d{1,2}/)?.[0]||0)||null;
function qscope(q){return global()?q:(nte()?q.eq('nte_id',nte()):q.eq('nte_id',-1));}
async function listar(){let q=C().from('extintas_descredenciamentos').select('*').order('updated_at',{ascending:false}).limit(1000);q=qscope(q);const r=await q;if(r.error)throw r.error;return r.data||[];}
async function escolasTerritorio(busca=''){let q=C().from('escolas_sigee').select('id,cod_mec,nome_escola,nome,municipio,nte_id,situacao_funcional,status_acervo,acervo').order('nome_escola').limit(80);if(!global()&&nte())q=q.eq('nte_id',nte());if(busca)q=q.or(`nome_escola.ilike.%${busca.replace(/[%(),]/g,'')}%,cod_mec.ilike.%${busca.replace(/[%(),]/g,'')}%`);const r=await q;if(r.error)throw r.error;return r.data||[];}
async function abrirSuspeita(p){const u=U(),e=(await C().from('escolas_sigee').select('*').eq('id',p.escola_id).single());if(e.error)throw e.error;if(!global()&&nte()&&Number(e.data.nte_id)!==nte())throw new Error('A escola não pertence ao território deste usuário.');const row={origem:'SUSPEITA_EXTINCAO',tipo:'SUSPEITA',escola_id:e.data.id,nte_id:e.data.nte_id,escola_nome:e.data.nome_escola||e.data.nome,municipio:e.data.municipio,status:'AGUARDANDO_INSPECAO',etapa_atual:'INSPECAO',motivo_suspeita:p.motivo,fonte_suspeita:p.fonte||null,criado_por_id:String(u.id||''),atualizado_por_id:String(u.id||'')};const r=await C().from('extintas_descredenciamentos').insert(row).select('*').single();if(r.error)throw r.error;await C().from('extintas_acervo_recolhimentos').insert({chamado_id:r.data.id});return r.data;}
async function detalhe(id){let q=C().from('extintas_descredenciamentos').select('*').eq('id',id);q=qscope(q);const c=await q.single();if(c.error)throw c.error;const [a,i,h]=await Promise.all([C().from('extintas_acervo_recolhimentos').select('*').eq('chamado_id',id).maybeSingle(),C().from('extintas_inspecoes').select('*').eq('chamado_id',id).order('created_at',{ascending:false}),C().from('extintas_descredenciamento_historico').select('*').eq('chamado_id',id).order('created_at',{ascending:false})]);let itens=[];if(a.data?.id){const x=await C().from('extintas_acervo_itens').select('*').eq('recolhimento_id',a.data.id).order('ordem');if(x.error)throw x.error;itens=x.data||[];}return{chamado:c.data,acervo:a.data,inspecoes:i.data||[],historico:h.data||[],itens};}
async function garantirItens(acervoId){const ex=await C().from('extintas_acervo_itens').select('id').eq('recolhimento_id',acervoId).limit(1);if(ex.error)throw ex.error;if(ex.data?.length)return;const defs=[['PRONTUARIOS','Prontuários de alunos'],['DIARIOS','Diários de Classe'],['ATAS_FINAIS','Atas de Resultados Finais'],['ATAS_COMPLEMENTARES','Atas de Dependência / Adaptação / Classificação / Reclassificação']];const r=await C().from('extintas_acervo_itens').insert(defs.map((x,i)=>({recolhimento_id:acervoId,codigo:x[0],descricao:x[1],obrigatorio:true,condicao:'NAO_ENTREGUE',em_caixa:true,quantidade_caixas:0,ordem:(i+1)*10})));if(r.error)throw r.error;}
async function salvarItem(id,p){const r=await C().from('extintas_acervo_itens').update({condicao:p.condicao||null,em_caixa:p.em_caixa!==false,quantidade_caixas:p.em_caixa===false?null:Number(p.quantidade_caixas||0),observacao:p.observacao||null,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;}
async function adicionarItem(recolhimento_id,p){const r=await C().from('extintas_acervo_itens').insert({recolhimento_id,descricao:p.descricao,obrigatorio:false,condicao:p.condicao||'COMPLETO',em_caixa:p.em_caixa===true,quantidade_caixas:p.em_caixa?Number(p.quantidade_caixas||0):null,observacao:p.observacao||null,ordem:1000}).select('*').single();if(r.error)throw r.error;return r.data;}
async function salvarAcervo(id,p){const r=await C().from('extintas_acervo_recolhimentos').update({situacao:p.situacao||'EM_RECOLHIMENTO',data_recolhimento:p.data_recolhimento||null,local_guarda:p.local_guarda||null,termo_referencia:p.termo_referencia||null,observacoes:p.observacoes||null,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;}
async function concluirAcervo(chamadoId){const u=U(),r=await C().rpc('sigee_extintas_concluir_recolhimento',{p_chamado_id:chamadoId,p_usuario_id:String(u.id||''),p_usuario_nome:u.nome||u.name||u.email||''});if(r.error)throw r.error;return r.data;}
async function salvarInspecao(chamadoId,p){const u=U(),row={chamado_id:chamadoId,tipo:'SUSPEITA_EXTINCAO',data_inspecao:p.data_inspecao,tecnico_id:String(u.id||''),tecnico_nome:u.nome||u.name||'',desativacao_constatada:p.desativacao_constatada,escola_localizada:p.escola_localizada,responsavel_localizado:p.responsavel_localizado,acervo_localizado:p.acervo_localizado,acervo_recuperado:p.acervo_recuperado,relatorio:p.relatorio,evidencias:p.evidencias||null};const r=await C().from('extintas_inspecoes').insert(row);if(r.error)throw r.error;const upd=p.desativacao_constatada?{status:p.acervo_recuperado?'EM_RECOLHIMENTO':'AGUARDANDO_SEI_COMPULSORIO',etapa_atual:p.acervo_recuperado?'RECOLHIMENTO':'DESCREDENCIAMENTO_COMPULSORIO',desativacao_constatada:true,responsavel_localizado:p.responsavel_localizado,acervo_localizado:p.acervo_localizado}:{status:'SUSPEITA_NAO_CONFIRMADA',etapa_atual:'ENCERRADO',desativacao_constatada:false};const x=await C().from('extintas_descredenciamentos').update({...upd,updated_at:new Date().toISOString()}).eq('id',chamadoId);if(x.error)throw x.error;}
async function registrarCompulsorio(id,p){const r=await C().from('extintas_descredenciamentos').update({tipo:'COMPULSORIO',numero_sei_compulsorio:p.sei,status:'AGUARDANDO_MP',etapa_atual:'ENCAMINHAMENTO_MP',updated_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;}
async function registrarMP(id,p){const r=await C().from('extintas_descredenciamentos').update({encaminhado_mp:true,data_encaminhamento_mp:p.data,referencia_mp:p.referencia,status:'ENCAMINHADO_MP',etapa_atual:'ACOMPANHAMENTO',updated_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;}
w.SIGEE_EXTINTAS_DESC_SERVICE=Object.freeze({listar,escolasTerritorio,abrirSuspeita,detalhe,garantirItens,salvarItem,adicionarItem,salvarAcervo,concluirAcervo,salvarInspecao,registrarCompulsorio,registrarMP,global,nte});})(window);
