/* SIGEE Enterprise - Controle de grupos, perfis e acessos individuais */
(function(){
'use strict';
const V='1.0.0';
const CHAVES=[
 ['dashboard.visualizar','Visualizar Dashboard','Dashboard'],
 ['processos.visualizar','Visualizar processos','Processos'],
 ['processos.criar','Criar solicitações','Processos'],
 ['processos.editar','Editar processos','Processos'],
 ['processos.movimentar','Executar movimentações','Processos'],
 ['processos.excluir','Excluir processos','Processos'],
 ['escolas.visualizar','Visualizar escolas','Escolas'],
 ['escolas.criar','Cadastrar escolas','Escolas'],
 ['escolas.editar','Editar escolas','Escolas'],
 ['escolas.excluir','Excluir escolas','Escolas'],
 ['usuarios.visualizar','Visualizar usuários','Usuários'],
 ['usuarios.criar','Cadastrar usuários','Usuários'],
 ['usuarios.editar','Editar usuários','Usuários'],
 ['usuarios.excluir','Excluir usuários','Usuários'],
 ['acessos.gerenciar','Gerenciar grupos, perfis e acessos','Administração'],
 ['logs.visualizar','Visualizar logs e conectados','Auditoria'],
 ['importar','Importar planilhas','Dados'],
 ['exportar','Exportar relatórios','Dados']
];
let grupos=[], perfis=[];
function sb(){try{return typeof obterSupabaseSIGEE==='function'?obterSupabaseSIGEE():(window.SIGEE_SUPABASE?.criarCliente?.()||window.supabaseClient);}catch(e){return null;}}
function user(){return window.usuarioLogado||null;}
function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();}
function isMaster(){return norm(user()?.perfil)==='master';}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function parse(v){if(!v)return{};if(typeof v==='object')return v;try{return JSON.parse(v);}catch(e){return{};}}
async function carregar(){const c=sb();if(!c)return;let r=await c.from('grupos_usuarios_sigee').select('*').order('nome');if(!r.error)grupos=r.data||[];r=await c.from('perfis_acesso_sigee').select('*').order('nome');if(!r.error)perfis=r.data||[];window.SIGEE_GRUPOS=grupos;window.SIGEE_PERFIS_ACESSO=perfis;}
function permissoesPerfil(u){const p=perfis.find(x=>String(x.id)===String(u?.perfil_acesso_id))||perfis.find(x=>norm(x.nome)===norm(u?.perfil));return parse(p?.permissoes);}
function permissoesEfetivas(u=user()){if(!u)return{};if(norm(u.perfil)==='master')return Object.fromEntries(CHAVES.map(x=>[x[0],true]));return Object.assign({},permissoesPerfil(u),parse(u.permissoes_override));}
function pode(chave){return permissoesEfetivas()[chave]===true;}
window.SIGEE_ACESSOS={versao:V,pode,permissoesEfetivas,carregar};
function injetarUI(){const sec=document.getElementById('aba-usuarios');if(!sec||document.getElementById('sigee-gestao-acessos'))return;const topo=sec.querySelector('.sigee-modulo-cabecalho');if(topo){const btn=topo.querySelector('button');if(btn)btn.textContent='➕ Cadastrar Usuário';topo.insertAdjacentHTML('beforeend','<button id="btn-gerenciar-acessos" onclick="SIGEE_ACESSOS_UI.abrir()" class="hidden bg-blue-900 hover:bg-blue-950 text-white font-bold px-4 py-2 rounded-lg text-xs shadow">🔐 Grupos, Perfis e Acessos</button>');}
 document.body.insertAdjacentHTML('beforeend',`<div id="sigee-gestao-acessos" class="hidden fixed inset-0 bg-blue-950/70 z-[99999] p-4 overflow-y-auto"><div class="bg-white max-w-6xl mx-auto rounded-2xl shadow-2xl overflow-hidden"><div class="bg-blue-950 text-white p-5 flex justify-between"><div><h2 class="font-black text-xl">🔐 Controle de Acessos</h2><p class="text-xs text-blue-200">Grupos, perfis personalizados e permissões individuais</p></div><button onclick="SIGEE_ACESSOS_UI.fechar()" class="font-black">✕</button></div><div class="p-5"><div class="flex gap-2 mb-5"><button onclick="SIGEE_ACESSOS_UI.aba('grupos')" class="px-4 py-2 rounded bg-blue-100 font-bold text-xs">Grupos</button><button onclick="SIGEE_ACESSOS_UI.aba('perfis')" class="px-4 py-2 rounded bg-blue-100 font-bold text-xs">Perfis</button><button onclick="SIGEE_ACESSOS_UI.aba('usuarios')" class="px-4 py-2 rounded bg-blue-100 font-bold text-xs">Acessos por usuário</button></div><div id="sigee-acessos-conteudo"></div></div></div></div>`);
 const modal=document.getElementById('modal-cadastro-usuario');const form=modal?.querySelector('form');if(form&&!document.getElementById('user-form-grupo')){const perfilBox=document.getElementById('user-form-perfil')?.closest('div');perfilBox?.insertAdjacentHTML('afterend',`<div><label class="block text-xs font-bold text-gray-700 uppercase mb-1">Grupo</label><select id="user-form-grupo" class="w-full p-2 border rounded-lg text-xs bg-gray-50"></select></div><div><label class="block text-xs font-bold text-gray-700 uppercase mb-1">Perfil de Acesso</label><select id="user-form-perfil-acesso" class="w-full p-2 border rounded-lg text-xs bg-gray-50"></select></div>`);}
}
function preencherSelects(){const g=document.getElementById('user-form-grupo'),p=document.getElementById('user-form-perfil-acesso');if(g)g.innerHTML='<option value="">Sem grupo</option>'+grupos.filter(x=>x.ativo!==false).map(x=>`<option value="${x.id}">${esc(x.nome)}</option>`).join('');if(p)p.innerHTML='<option value="">Usar perfil padrão</option>'+perfis.filter(x=>x.ativo!==false).map(x=>`<option value="${x.id}">${esc(x.nome)}</option>`).join('');}
async function abrir(){if(!isMaster())return alert('Apenas o usuário Master pode gerenciar acessos.');await carregar();document.getElementById('sigee-gestao-acessos').classList.remove('hidden');aba('grupos');}
function fechar(){document.getElementById('sigee-gestao-acessos')?.classList.add('hidden');}
function aba(tipo){const c=document.getElementById('sigee-acessos-conteudo');if(!c)return;if(tipo==='grupos')c.innerHTML=`<div class="flex justify-between mb-3"><h3 class="font-black text-blue-950">Grupos de usuários</h3><button onclick="SIGEE_ACESSOS_UI.novoGrupo()" class="bg-amber-500 text-white px-3 py-2 rounded text-xs font-bold">Novo grupo</button></div><div class="grid gap-2">${grupos.map(g=>`<div class="border rounded p-3 flex justify-between"><div><b>${esc(g.nome)}</b><p class="text-xs text-gray-500">${esc(g.descricao||'')}</p></div><div><button onclick="SIGEE_ACESSOS_UI.editarGrupo(${g.id})" class="text-blue-700 font-bold text-xs mr-3">Editar</button><button onclick="SIGEE_ACESSOS_UI.excluirGrupo(${g.id})" class="text-red-700 font-bold text-xs">Excluir</button></div></div>`).join('')||'<p class="text-gray-400">Nenhum grupo cadastrado.</p>'}</div>`;
if(tipo==='perfis')c.innerHTML=`<div class="flex justify-between mb-3"><h3 class="font-black text-blue-950">Perfis de acesso</h3><button onclick="SIGEE_ACESSOS_UI.novoPerfil()" class="bg-amber-500 text-white px-3 py-2 rounded text-xs font-bold">Novo perfil</button></div><div class="grid gap-2">${perfis.map(p=>`<div class="border rounded p-3 flex justify-between"><div><b>${esc(p.nome)}</b>${p.sistema?'<span class="ml-2 text-[10px] bg-gray-200 px-2 rounded">Sistema</span>':''}<p class="text-xs text-gray-500">${esc(p.descricao||'')}</p></div><button onclick="SIGEE_ACESSOS_UI.editarPerfil(${p.id})" class="text-blue-700 font-bold text-xs">Editar permissões</button></div>`).join('')}</div>`;
if(tipo==='usuarios'){const us=Array.isArray(window.usuariosDB)?window.usuariosDB:[];c.innerHTML=`<h3 class="font-black text-blue-950 mb-3">Acessos individuais</h3><div class="grid gap-2">${us.map(u=>`<div class="border rounded p-3 flex justify-between items-center"><div><b>${esc(u.nome)}</b><p class="text-xs text-gray-500">${esc(u.email)} • ${esc(u.perfil||'')}</p></div><button onclick="SIGEE_ACESSOS_UI.editarUsuario(${JSON.stringify(String(u.id))})" class="bg-blue-700 text-white px-3 py-2 rounded text-xs font-bold">Editar acessos</button></div>`).join('')}</div>`;}}
async function novoGrupo(id){const atual=id?grupos.find(x=>String(x.id)===String(id)):null;const nome=prompt('Nome do grupo:',atual?.nome||'');if(!nome)return;const descricao=prompt('Descrição:',atual?.descricao||'')||'';const c=sb();const q=atual?c.from('grupos_usuarios_sigee').update({nome,descricao,updated_at:new Date().toISOString()}).eq('id',id):c.from('grupos_usuarios_sigee').insert({nome,descricao});const r=await q;if(r.error)return alert(r.error.message);await carregar();preencherSelects();aba('grupos');window.registrarLog?.(`${atual?'Grupo editado':'Grupo criado'}: ${nome}`);}
async function excluirGrupo(id){if(!confirm('Excluir este grupo? Os usuários permanecerão cadastrados.'))return;const r=await sb().from('grupos_usuarios_sigee').delete().eq('id',id);if(r.error)return alert(r.error.message);await carregar();aba('grupos');}
function htmlPerms(vals={}){return CHAVES.map(([k,l,g])=>`<label class="flex gap-2 items-center border rounded p-2"><input type="checkbox" data-perm="${k}" ${vals[k]===true?'checked':''}><span><b class="text-xs">${esc(l)}</b><small class="block text-gray-400">${esc(g)}</small></span></label>`).join('');}
async function novoPerfil(id){const atual=id?perfis.find(x=>String(x.id)===String(id)):null;const c=document.getElementById('sigee-acessos-conteudo');c.innerHTML=`<h3 class="font-black mb-3">${atual?'Editar':'Novo'} perfil</h3><input id="pa-nome" class="w-full border p-2 rounded mb-2" placeholder="Nome" value="${esc(atual?.nome||'')}"><textarea id="pa-desc" class="w-full border p-2 rounded mb-3" placeholder="Descrição">${esc(atual?.descricao||'')}</textarea><div class="grid md:grid-cols-3 gap-2">${htmlPerms(parse(atual?.permissoes))}</div><div class="mt-4"><button onclick="SIGEE_ACESSOS_UI.salvarPerfil(${id||'null'})" class="bg-emerald-600 text-white px-4 py-2 rounded font-bold text-xs">Salvar perfil</button></div>`;}
async function salvarPerfil(id){const nome=document.getElementById('pa-nome').value.trim();if(!nome)return alert('Informe o nome.');const permissoes={};document.querySelectorAll('[data-perm]').forEach(x=>permissoes[x.dataset.perm]=x.checked);const payload={nome,descricao:document.getElementById('pa-desc').value,permissoes,updated_at:new Date().toISOString()};const q=id?sb().from('perfis_acesso_sigee').update(payload).eq('id',id):sb().from('perfis_acesso_sigee').insert(payload);const r=await q;if(r.error)return alert(r.error.message);await carregar();preencherSelects();aba('perfis');window.registrarLog?.(`Perfil de acesso ${id?'editado':'criado'}: ${nome}`);}
async function editarUsuario(id){const us=Array.isArray(window.usuariosDB)?window.usuariosDB:[];const u=us.find(x=>String(x.id)===String(id));if(!u)return;const base=permissoesPerfil(u),ov=parse(u.permissoes_override),ef=Object.assign({},base,ov);const c=document.getElementById('sigee-acessos-conteudo');c.innerHTML=`<h3 class="font-black mb-1">${esc(u.nome)}</h3><p class="text-xs text-gray-500 mb-3">${esc(u.email)}</p><div class="grid md:grid-cols-2 gap-3 mb-3"><label class="text-xs font-bold">Grupo<select id="ua-grupo" class="block w-full border p-2 rounded mt-1"><option value="">Sem grupo</option>${grupos.map(g=>`<option value="${g.id}" ${String(u.grupo_id)===String(g.id)?'selected':''}>${esc(g.nome)}</option>`).join('')}</select></label><label class="text-xs font-bold">Perfil de acesso<select id="ua-perfil" class="block w-full border p-2 rounded mt-1"><option value="">Perfil padrão</option>${perfis.map(p=>`<option value="${p.id}" ${String(u.perfil_acesso_id)===String(p.id)?'selected':''}>${esc(p.nome)}</option>`).join('')}</select></label></div><p class="text-xs mb-2">Marque a permissão efetiva desejada. As escolhas serão salvas como exceções individuais.</p><div class="grid md:grid-cols-3 gap-2">${htmlPerms(ef)}</div><button onclick="SIGEE_ACESSOS_UI.salvarUsuario(${JSON.stringify(String(id))})" class="mt-4 bg-emerald-600 text-white px-4 py-2 rounded font-bold text-xs">Salvar acessos do usuário</button>`;}
async function salvarUsuario(id){const us=Array.isArray(window.usuariosDB)?window.usuariosDB:[];const u=us.find(x=>String(x.id)===String(id));if(!u)return;const perfilId=document.getElementById('ua-perfil').value||null;const p=perfis.find(x=>String(x.id)===String(perfilId))||perfis.find(x=>norm(x.nome)===norm(u.perfil));const base=parse(p?.permissoes),ov={};document.querySelectorAll('[data-perm]').forEach(x=>{if(x.checked!==(base[x.dataset.perm]===true))ov[x.dataset.perm]=x.checked;});const payload={grupo_id:document.getElementById('ua-grupo').value||null,perfil_acesso_id:perfilId,permissoes_override:ov};const r=await sb().from('usuarios_sigee').update(payload).eq('id',id);if(r.error)return alert(r.error.message);Object.assign(u,payload);window.registrarLog?.(`Acessos individuais atualizados: ${u.email}`);alert('Acessos atualizados. Eles serão aplicados no próximo login do usuário.');aba('usuarios');}
function aplicar(){const u=user();if(!u)return;const master=isMaster();document.getElementById('btn-gerenciar-acessos')?.classList.toggle('hidden',!master);const map=[['menu-central-processos','processos.visualizar'],['menu-usuarios','usuarios.visualizar'],['menu-logs','logs.visualizar']];map.forEach(([id,k])=>document.getElementById(id)?.classList.toggle('hidden',!pode(k)));document.querySelectorAll('.export-only').forEach(x=>x.classList.toggle('hidden',!pode('exportar')));document.querySelectorAll('[onclick*="abrirFormularioNovaSolicitacao"]').forEach(x=>x.style.display=pode('processos.criar')?'':'none');document.querySelectorAll('[onclick*="abrirModalNovaEscola"]').forEach(x=>x.style.display=pode('escolas.criar')?'':'none');}
const oldAbrir=window.abrirModalEditarUsuarioMaster;window.abrirModalEditarUsuarioMaster=function(id){oldAbrir?.(id);setTimeout(()=>{const u=(window.usuariosDB||[]).find(x=>String(x.id)===String(id));preencherSelects();if(u){document.getElementById('user-form-grupo').value=u.grupo_id||'';document.getElementById('user-form-perfil-acesso').value=u.perfil_acesso_id||'';}},50);};
const oldSalvar=window.salvarNovoUsuarioFormularioMaster;window.salvarNovoUsuarioFormularioMaster=async function(e){const id=document.getElementById('user-form-id')?.value||null;await oldSalvar?.(e);const email=document.getElementById('user-form-email')?.value?.trim().toLowerCase();if(email){const payload={grupo_id:document.getElementById('user-form-grupo')?.value||null,perfil_acesso_id:document.getElementById('user-form-perfil-acesso')?.value||null};await sb()?.from('usuarios_sigee').update(payload).eq('email',email);const u=(window.usuariosDB||[]).find(x=>norm(x.email)===norm(email));if(u)Object.assign(u,payload);}};
window.SIGEE_ACESSOS_UI={abrir,fechar,aba,novoGrupo,editarGrupo:novoGrupo,excluirGrupo,novoPerfil,editarPerfil:novoPerfil,salvarPerfil,editarUsuario,salvarUsuario};
async function init(){injetarUI();await carregar();preencherSelects();aplicar();setTimeout(aplicar,1500);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,800));else setTimeout(init,800);
})();
